import com.squareup.kotlinpoet.*
import generators.generateApiTypes
import generators.generateDefinitionsFromComponents
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import utils.*

/** Entry */
fun main(args: Array<String>) {
    val argv = args.toList()
    fun arg(name: String, default: String? = null): String =
        argv.getOrNull(argv.indexOf(name) + 1) ?: default
        ?: error("Missing $name")

    // ---- Collect repeated --spec <file> [--prefix <Prefix>] pairs
    val specs = mutableListOf<SpecCfg>()
    run {
        var i = 0
        while (i < argv.size) {
            if (argv[i] == "--spec") {
                val p = argv.getOrNull(i + 1) ?: error("Missing value after --spec")
                var prefix = ""
                if (i + 2 < argv.size && argv[i + 2] == "--prefix") {
                    prefix = argv.getOrNull(i + 3) ?: ""
                    i += 2
                }
                specs += SpecCfg(Path.of(p), prefix)
                i += 2
            } else i++
        }
    }
    require(specs.isNotEmpty()) { "At least one --spec is required (use: --spec path [--prefix Prefix])" }

    val outRoot = Path.of(arg("--out"))
    val pkg = arg("--pkg")
    val typesFileName = arg("--typesFileName", "Models")

    specs.forEach { require(Files.exists(it.path)) { "Spec not found: ${it.path}" } }
    outRoot.createDirectories()

    // Parse all specs → OpenAPI 3
    val swaggerSpecs: List<Pair<SpecCfg, JsonObject>> = specs.map { it to readJson(it.path) }

    val fileBuilder = FileSpec.builder(pkg, typesFileName)
        .addFileComment("/* @generated by codegen. DO NOT EDIT BY HAND */")
        .addImport("kotlinx.serialization", "Serializable", "SerialName")
        .addImport("kotlinx.serialization.json", "JsonElement")

    generateDefinitionsFromComponents(swaggerSpecs, fileBuilder, pkg)
    generateApiTypes(swaggerSpecs, fileBuilder, pkg)
    fileBuilder.addAnnotation(
        AnnotationSpec.builder(Suppress::class)
            .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE) // -> @file:Suppress(...)
            .addMember("%S", "unused")
            .addMember("%S", "UNUSED_PARAMETER")
            .addMember("%S", "UNUSED_VARIABLE")
            .addMember("%S", "RedundantVisibilityModifier")
            .addMember("%S", "MemberVisibilityCanBePrivate")
            .addMember("%S", "RedundantSuspendModifier")
            .build()
    ).build().writeTo(outRoot.toFile())
}

private val JsonLoose = Json {
    ignoreUnknownKeys = false
    isLenient = true
    allowSpecialFloatingPointValues = true
}

fun readJson(path: Path): JsonObject {
    val raw = Files.readString(path)
    val el = try {
        JsonLoose.parseToJsonElement(raw)
    } catch (e: Exception) {
        error("Failed to parse JSON at $path: ${e.message}")
    }
    return el.jsonObjectOrFail("Top-level JSON must be an object at $path")
}

private fun JsonElement.jsonObjectOrFail(msg: String): JsonObject =
    this as? JsonObject ?: error(msg)

