/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKeyName Human-readable name for an API Key.
 * @param publicKey The public component of a cryptographic key pair used to sign messages and transactions.
 * @param expirationSeconds Optional window (in seconds) indicating how long the API Key should last.
 */
@Serializable

data class ApiApiKeyParams (

    /* Human-readable name for an API Key. */
    @SerialName(value = "apiKeyName")
    val apiKeyName: kotlin.String,

    /* The public component of a cryptographic key pair used to sign messages and transactions. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* Optional window (in seconds) indicating how long the API Key should last. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null

) {


}

