/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param paymentMethodId The payment method that was removed.
 */
@Serializable

data class BillingDeletePaymentMethodResult (

    /* The payment method that was removed. */
    @SerialName(value = "paymentMethodId")
    val paymentMethodId: kotlin.String

) {


}

