/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param number The account number of the customer's credit card.
 * @param cvv The verification digits of the customer's credit card.
 * @param expiryMonth The month that the credit card expires.
 * @param expiryYear The year that the credit card expires.
 * @param cardHolderEmail The email that will receive invoices for the credit card.
 * @param cardHolderName The name associated with the credit card.
 */
@Serializable

data class BillingSetPaymentMethodIntent (

    /* The account number of the customer's credit card. */
    @SerialName(value = "number")
    val number: kotlin.String,

    /* The verification digits of the customer's credit card. */
    @SerialName(value = "cvv")
    val cvv: kotlin.String,

    /* The month that the credit card expires. */
    @SerialName(value = "expiryMonth")
    val expiryMonth: kotlin.String,

    /* The year that the credit card expires. */
    @SerialName(value = "expiryYear")
    val expiryYear: kotlin.String,

    /* The email that will receive invoices for the credit card. */
    @SerialName(value = "cardHolderEmail")
    val cardHolderEmail: kotlin.String,

    /* The name associated with the credit card. */
    @SerialName(value = "cardHolderName")
    val cardHolderName: kotlin.String

) {


}

