/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param productId The id of the product being subscribed to.
 */
@Serializable

data class BillingActivateBillingTierResult (

    /* The id of the product being subscribed to. */
    @SerialName(value = "productId")
    val productId: kotlin.String

) {


}

