/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.V1TagType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tagId Unique identifier for a given Tag.
 * @param tagName Human-readable name for a Tag.
 * @param tagType 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class Datav1Tag (

    /* Unique identifier for a given Tag. */
    @SerialName(value = "tagId")
    val tagId: kotlin.String,

    /* Human-readable name for a Tag. */
    @SerialName(value = "tagName")
    val tagName: kotlin.String,

    @Contextual @SerialName(value = "tagType")
    val tagType: V1TagType,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp

) {


}

