/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.Immutablecommonv1PolicyEvaluation

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier for a given policy evaluation.
 * @param activityId Unique identifier for a given Activity.
 * @param organizationId Unique identifier for the Organization the Activity belongs to.
 * @param voteId Unique identifier for the Vote associated with this policy evaluation.
 * @param policyEvaluations Detailed evaluation result for each Policy that was run.
 * @param createdAt 
 */
@Serializable

data class Externalactivityv1PolicyEvaluation (

    /* Unique identifier for a given policy evaluation. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Unique identifier for a given Activity. */
    @SerialName(value = "activityId")
    val activityId: kotlin.String,

    /* Unique identifier for the Organization the Activity belongs to. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Unique identifier for the Vote associated with this policy evaluation. */
    @SerialName(value = "voteId")
    val voteId: kotlin.String,

    /* Detailed evaluation result for each Policy that was run. */
    @SerialName(value = "policyEvaluations")
    val policyEvaluations: kotlin.collections.List<Immutablecommonv1PolicyEvaluation>,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp

) {


}

