/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1CredentialType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param publicKey The public component of a cryptographic key pair used to sign messages and transactions.
 * @param type 
 */
@Serializable

data class Externaldatav1Credential (

    /* The public component of a cryptographic key pair used to sign messages and transactions. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: V1CredentialType

) {


}

