/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param seconds 
 * @param nanos 
 */
@Serializable

data class Externaldatav1Timestamp (

    @SerialName(value = "seconds")
    val seconds: kotlin.String,

    @SerialName(value = "nanos")
    val nanos: kotlin.String

) {


}

