/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AddressFormat

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param format 
 * @param address 
 */
@Serializable

data class Immutableactivityv1Address (

    @Contextual @SerialName(value = "format")
    val format: V1AddressFormat? = null,

    @SerialName(value = "address")
    val address: kotlin.String? = null

) {


}

