/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param providerName Human-readable name to identify a Provider.
 * @param oidcToken Base64 encoded OIDC token
 */
@Serializable

data class ProxyV1OauthProviderParams (

    /* Human-readable name to identify a Provider. */
    @SerialName(value = "providerName")
    val providerName: kotlin.String,

    /* Base64 encoded OIDC token */
    @SerialName(value = "oidcToken")
    val oidcToken: kotlin.String

) {


}

