/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ProxyV1WalletResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId 
 * @param userId Root user ID created for this sub-organization
 * @param wallet 
 */
@Serializable

data class ProxyV1SignupResponse (

    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Root user ID created for this sub-organization */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "wallet")
    val wallet: ProxyV1WalletResult? = null

) {


}

