/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabledProviders List of enabled authentication providers (e.g., 'facebook', 'google', 'apple', 'email', 'sms', 'passkey', 'wallet')
 * @param sessionExpirationSeconds Session expiration duration in seconds
 * @param organizationId The organization ID this configuration applies to
 * @param oauthClientIds Mapping of social login providers to their OAuth client IDs.
 * @param oauthRedirectUrl OAuth redirect URL to be used for social login flows.
 * @param otpAlphanumeric 
 * @param otpLength 
 */
@Serializable

data class ProxyV1GetWalletKitConfigResponse (

    /* List of enabled authentication providers (e.g., 'facebook', 'google', 'apple', 'email', 'sms', 'passkey', 'wallet') */
    @SerialName(value = "enabledProviders")
    val enabledProviders: kotlin.collections.List<kotlin.String>,

    /* Session expiration duration in seconds */
    @SerialName(value = "sessionExpirationSeconds")
    val sessionExpirationSeconds: kotlin.String,

    /* The organization ID this configuration applies to */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Mapping of social login providers to their OAuth client IDs. */
    @SerialName(value = "oauthClientIds")
    val oauthClientIds: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* OAuth redirect URL to be used for social login flows. */
    @SerialName(value = "oauthRedirectUrl")
    val oauthRedirectUrl: kotlin.String? = null,

    @SerialName(value = "otpAlphanumeric")
    val otpAlphanumeric: kotlin.Boolean? = null,

    @SerialName(value = "otpLength")
    val otpLength: kotlin.String? = null

) {


}

