/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ProxyV1AuthenticatorTransport

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param credentialId The cbor encoded then base64 url encoded id of the credential.
 * @param clientDataJson A base64 url encoded payload containing metadata about the signing context and the challenge.
 * @param attestationObject A base64 url encoded payload containing authenticator data and any attestation the webauthn provider chooses.
 * @param transports The type of authenticator transports.
 */
@Serializable

data class ProxyV1Attestation (

    /* The cbor encoded then base64 url encoded id of the credential. */
    @SerialName(value = "credentialId")
    val credentialId: kotlin.String,

    /* A base64 url encoded payload containing metadata about the signing context and the challenge. */
    @SerialName(value = "clientDataJson")
    val clientDataJson: kotlin.String,

    /* A base64 url encoded payload containing authenticator data and any attestation the webauthn provider chooses. */
    @SerialName(value = "attestationObject")
    val attestationObject: kotlin.String,

    /* The type of authenticator transports. */
    @SerialName(value = "transports")
    val transports: kotlin.collections.List<@Contextual ProxyV1AuthenticatorTransport>

) {


}

