/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: API_KEY_CURVE_P256,API_KEY_CURVE_SECP256K1,API_KEY_CURVE_ED25519
 */
@Serializable
enum class ProxyV1ApiKeyCurve(val value: kotlin.String) {

    @SerialName(value = "API_KEY_CURVE_P256")
    API_KEY_CURVE_P256("API_KEY_CURVE_P256"),

    @SerialName(value = "API_KEY_CURVE_SECP256K1")
    API_KEY_CURVE_SECP256K1("API_KEY_CURVE_SECP256K1"),

    @SerialName(value = "API_KEY_CURVE_ED25519")
    API_KEY_CURVE_ED25519("API_KEY_CURVE_ED25519");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ProxyV1ApiKeyCurve) "$data" else null

        /**
         * Returns a valid [ProxyV1ApiKeyCurve] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ProxyV1ApiKeyCurve? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


