/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ProxyV1WalletAccountParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletName Human-readable name for a Wallet.
 * @param accounts A list of wallet Accounts. This field, if not needed, should be an empty array in your request body.
 * @param mnemonicLength Length of mnemonic to generate the Wallet seed. Defaults to 12. Accepted values: 12, 15, 18, 21, 24.
 */
@Serializable

data class ProxyV1WalletParams (

    /* Human-readable name for a Wallet. */
    @SerialName(value = "walletName")
    val walletName: kotlin.String,

    /* A list of wallet Accounts. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "accounts")
    val accounts: kotlin.collections.List<ProxyV1WalletAccountParams>,

    /* Length of mnemonic to generate the Wallet seed. Defaults to 12. Accepted values: 12, 15, 18, 21, 24. */
    @SerialName(value = "mnemonicLength")
    val mnemonicLength: kotlin.Int? = null

) {


}

