/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ProxyV1AddressFormat
import com.turnkey.http.model.ProxyV1Curve
import com.turnkey.http.model.ProxyV1PathFormat

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param curve 
 * @param pathFormat 
 * @param path Path used to generate a wallet Account.
 * @param addressFormat 
 */
@Serializable

data class ProxyV1WalletAccountParams (

    @Contextual @SerialName(value = "curve")
    val curve: ProxyV1Curve,

    @Contextual @SerialName(value = "pathFormat")
    val pathFormat: ProxyV1PathFormat,

    /* Path used to generate a wallet Account. */
    @SerialName(value = "path")
    val path: kotlin.String,

    @Contextual @SerialName(value = "addressFormat")
    val addressFormat: ProxyV1AddressFormat

) {


}

