/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oidcToken A Turnkey issued OIDC token to be used with the LoginWithOAuth activity
 */
@Serializable

data class ProxyV1OAuth2AuthenticateResponse (

    /* A Turnkey issued OIDC token to be used with the LoginWithOAuth activity */
    @SerialName(value = "oidcToken")
    val oidcToken: kotlin.String

) {


}

