/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param session Signed JWT containing an expiry, public key, session type, user id, and organization id
 */
@Serializable

data class ProxyV1OAuthLoginResponse (

    /* Signed JWT containing an expiry, public key, session type, user id, and organization id */
    @SerialName(value = "session")
    val session: kotlin.String

) {


}

