/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ProxyV1ApiKeyParamsV2
import com.turnkey.http.model.ProxyV1AuthenticatorParamsV2
import com.turnkey.http.model.ProxyV1OauthProviderParams
import com.turnkey.http.model.ProxyV1WalletParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKeys A list of API Key parameters. This field, if not needed, should be an empty array in your request body.
 * @param authenticators A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body.
 * @param oauthProviders A list of Oauth providers. This field, if not needed, should be an empty array in your request body.
 * @param userEmail 
 * @param userPhoneNumber 
 * @param userTag 
 * @param userName 
 * @param organizationName 
 * @param verificationToken 
 * @param wallet 
 */
@Serializable

data class ProxyV1SignupRequest (

    /* A list of API Key parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "apiKeys")
    val apiKeys: kotlin.collections.List<ProxyV1ApiKeyParamsV2>,

    /* A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "authenticators")
    val authenticators: kotlin.collections.List<ProxyV1AuthenticatorParamsV2>,

    /* A list of Oauth providers. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "oauthProviders")
    val oauthProviders: kotlin.collections.List<ProxyV1OauthProviderParams>,

    @SerialName(value = "userEmail")
    val userEmail: kotlin.String? = null,

    @SerialName(value = "userPhoneNumber")
    val userPhoneNumber: kotlin.String? = null,

    @SerialName(value = "userTag")
    val userTag: kotlin.String? = null,

    @SerialName(value = "userName")
    val userName: kotlin.String? = null,

    @SerialName(value = "organizationName")
    val organizationName: kotlin.String? = null,

    @SerialName(value = "verificationToken")
    val verificationToken: kotlin.String? = null,

    @SerialName(value = "wallet")
    val wallet: ProxyV1WalletParams? = null

) {


}

