/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AuthenticatorParamsV2

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param invitationId Unique identifier for a given Invitation object.
 * @param userId Unique identifier for a given User.
 * @param authenticator 
 */
@Serializable

data class V1AcceptInvitationIntentV2 (

    /* Unique identifier for a given Invitation object. */
    @SerialName(value = "invitationId")
    val invitationId: kotlin.String,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "authenticator")
    val authenticator: V1AuthenticatorParamsV2

) {


}

