/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.RpcStatus
import com.turnkey.http.model.V1ActivityStatus
import com.turnkey.http.model.V1ActivityType
import com.turnkey.http.model.V1AppProof
import com.turnkey.http.model.V1Intent
import com.turnkey.http.model.V1Result
import com.turnkey.http.model.V1Vote

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier for a given Activity object.
 * @param organizationId Unique identifier for a given Organization.
 * @param status 
 * @param type 
 * @param intent 
 * @param result 
 * @param votes A list of objects representing a particular User's approval or rejection of a Consensus request, including all relevant metadata.
 * @param fingerprint An artifact verifying a User's action.
 * @param canApprove 
 * @param canReject 
 * @param createdAt 
 * @param updatedAt 
 * @param appProofs A list of app proofs generated by enclaves during activity execution, providing verifiable attestations of performed operations.
 * @param failure 
 */
@Serializable

data class V1Activity (

    /* Unique identifier for a given Activity object. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Unique identifier for a given Organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: V1ActivityStatus,

    @Contextual @SerialName(value = "type")
    val type: V1ActivityType,

    @SerialName(value = "intent")
    val intent: V1Intent,

    @SerialName(value = "result")
    val result: V1Result,

    /* A list of objects representing a particular User's approval or rejection of a Consensus request, including all relevant metadata. */
    @SerialName(value = "votes")
    val votes: kotlin.collections.List<V1Vote>,

    /* An artifact verifying a User's action. */
    @SerialName(value = "fingerprint")
    val fingerprint: kotlin.String,

    @SerialName(value = "canApprove")
    val canApprove: kotlin.Boolean,

    @SerialName(value = "canReject")
    val canReject: kotlin.Boolean,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp,

    /* A list of app proofs generated by enclaves during activity execution, providing verifiable attestations of performed operations. */
    @SerialName(value = "appProofs")
    val appProofs: kotlin.collections.List<V1AppProof>? = null,

    @SerialName(value = "failure")
    val failure: RpcStatus? = null

) {


}

