/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: ACTIVITY_STATUS_CREATED,ACTIVITY_STATUS_PENDING,ACTIVITY_STATUS_COMPLETED,ACTIVITY_STATUS_FAILED,ACTIVITY_STATUS_CONSENSUS_NEEDED,ACTIVITY_STATUS_REJECTED
 */
@Serializable
enum class V1ActivityStatus(val value: kotlin.String) {

    @SerialName(value = "ACTIVITY_STATUS_CREATED")
    ACTIVITY_STATUS_CREATED("ACTIVITY_STATUS_CREATED"),

    @SerialName(value = "ACTIVITY_STATUS_PENDING")
    ACTIVITY_STATUS_PENDING("ACTIVITY_STATUS_PENDING"),

    @SerialName(value = "ACTIVITY_STATUS_COMPLETED")
    ACTIVITY_STATUS_COMPLETED("ACTIVITY_STATUS_COMPLETED"),

    @SerialName(value = "ACTIVITY_STATUS_FAILED")
    ACTIVITY_STATUS_FAILED("ACTIVITY_STATUS_FAILED"),

    @SerialName(value = "ACTIVITY_STATUS_CONSENSUS_NEEDED")
    ACTIVITY_STATUS_CONSENSUS_NEEDED("ACTIVITY_STATUS_CONSENSUS_NEEDED"),

    @SerialName(value = "ACTIVITY_STATUS_REJECTED")
    ACTIVITY_STATUS_REJECTED("ACTIVITY_STATUS_REJECTED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1ActivityStatus) "$data" else null

        /**
         * Returns a valid [V1ActivityStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1ActivityStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


