/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param invitationId Unique identifier for a given Invitation.
 * @param userId Unique identifier for a given User.
 */
@Serializable

data class V1AcceptInvitationResult (

    /* Unique identifier for a given Invitation. */
    @SerialName(value = "invitationId")
    val invitationId: kotlin.String,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String

) {


}

