/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Credential
import com.turnkey.http.model.Externaldatav1Timestamp

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param credential 
 * @param apiKeyId Unique identifier for a given API Key.
 * @param apiKeyName Human-readable name for an API Key.
 * @param createdAt 
 * @param updatedAt 
 * @param expirationSeconds Optional window (in seconds) indicating how long the API Key should last.
 */
@Serializable

data class V1ApiKey (

    @SerialName(value = "credential")
    val credential: Externaldatav1Credential,

    /* Unique identifier for a given API Key. */
    @SerialName(value = "apiKeyId")
    val apiKeyId: kotlin.String,

    /* Human-readable name for an API Key. */
    @SerialName(value = "apiKeyName")
    val apiKeyName: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp,

    /* Optional window (in seconds) indicating how long the API Key should last. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null

) {


}

