/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fingerprint An artifact verifying a User's action.
 */
@Serializable

data class V1ApproveActivityIntent (

    /* An artifact verifying a User's action. */
    @SerialName(value = "fingerprint")
    val fingerprint: kotlin.String

) {


}

