/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ApiApiKeyParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userName The name of the new API-only User.
 * @param userTags A list of tags assigned to the new API-only User. This field, if not needed, should be an empty array in your request body.
 * @param apiKeys A list of API Key parameters. This field, if not needed, should be an empty array in your request body.
 * @param userEmail The email address for this API-only User (optional).
 */
@Serializable

data class V1ApiOnlyUserParams (

    /* The name of the new API-only User. */
    @SerialName(value = "userName")
    val userName: kotlin.String,

    /* A list of tags assigned to the new API-only User. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "userTags")
    val userTags: kotlin.collections.List<kotlin.String>,

    /* A list of API Key parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "apiKeys")
    val apiKeys: kotlin.collections.List<ApiApiKeyParams>,

    /* The email address for this API-only User (optional). */
    @SerialName(value = "userEmail")
    val userEmail: kotlin.String? = null

) {


}

