/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1SignatureScheme

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param scheme 
 * @param publicKey Ephemeral public key.
 * @param proofPayload JSON serialized AppProofPayload.
 * @param signature Signature over hashed proof_payload.
 */
@Serializable

data class V1AppProof (

    @Contextual @SerialName(value = "scheme")
    val scheme: V1SignatureScheme,

    /* Ephemeral public key. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* JSON serialized AppProofPayload. */
    @SerialName(value = "proofPayload")
    val proofPayload: kotlin.String,

    /* Signature over hashed proof_payload. */
    @SerialName(value = "signature")
    val signature: kotlin.String

) {


}

