/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1PublicKeyCredentialWithAttestation

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authenticatorName Human-readable name for an Authenticator.
 * @param userId Unique identifier for a given User.
 * @param attestation 
 * @param challenge Challenge presented for authentication purposes.
 */
@Serializable

data class V1AuthenticatorParams (

    /* Human-readable name for an Authenticator. */
    @SerialName(value = "authenticatorName")
    val authenticatorName: kotlin.String,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "attestation")
    val attestation: V1PublicKeyCredentialWithAttestation,

    /* Challenge presented for authentication purposes. */
    @SerialName(value = "challenge")
    val challenge: kotlin.String

) {


}

