/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: AUTHENTICATOR_TRANSPORT_BLE,AUTHENTICATOR_TRANSPORT_INTERNAL,AUTHENTICATOR_TRANSPORT_NFC,AUTHENTICATOR_TRANSPORT_USB,AUTHENTICATOR_TRANSPORT_HYBRID
 */
@Serializable
enum class V1AuthenticatorTransport(val value: kotlin.String) {

    @SerialName(value = "AUTHENTICATOR_TRANSPORT_BLE")
    AUTHENTICATOR_TRANSPORT_BLE("AUTHENTICATOR_TRANSPORT_BLE"),

    @SerialName(value = "AUTHENTICATOR_TRANSPORT_INTERNAL")
    AUTHENTICATOR_TRANSPORT_INTERNAL("AUTHENTICATOR_TRANSPORT_INTERNAL"),

    @SerialName(value = "AUTHENTICATOR_TRANSPORT_NFC")
    AUTHENTICATOR_TRANSPORT_NFC("AUTHENTICATOR_TRANSPORT_NFC"),

    @SerialName(value = "AUTHENTICATOR_TRANSPORT_USB")
    AUTHENTICATOR_TRANSPORT_USB("AUTHENTICATOR_TRANSPORT_USB"),

    @SerialName(value = "AUTHENTICATOR_TRANSPORT_HYBRID")
    AUTHENTICATOR_TRANSPORT_HYBRID("AUTHENTICATOR_TRANSPORT_HYBRID");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1AuthenticatorTransport) "$data" else null

        /**
         * Returns a valid [V1AuthenticatorTransport] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1AuthenticatorTransport? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


