/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AuthenticatorTransport

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param clientDataJson 
 * @param attestationObject 
 * @param transports 
 * @param authenticatorAttachment 
 */
@Serializable

data class V1AuthenticatorAttestationResponse (

    @SerialName(value = "clientDataJson")
    val clientDataJson: kotlin.String,

    @SerialName(value = "attestationObject")
    val attestationObject: kotlin.String,

    @SerialName(value = "transports")
    val transports: kotlin.collections.List<@Contextual V1AuthenticatorTransport>? = null,

    @SerialName(value = "authenticatorAttachment")
    val authenticatorAttachment: V1AuthenticatorAttestationResponse.AuthenticatorAttachment? = null

) {

    /**
     * 
     *
     * Values: crossMinusPlatform,platform
     */
    @Serializable
    enum class AuthenticatorAttachment(val value: kotlin.String) {
        @SerialName(value = "cross-platform") crossMinusPlatform("cross-platform"),
        @SerialName(value = "platform") platform("platform");
    }

}

