/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Credential
import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.V1AuthenticatorTransport

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param transports Types of transports that may be used by an Authenticator (e.g., USB, NFC, BLE).
 * @param attestationType 
 * @param aaguid Identifier indicating the type of the Security Key.
 * @param credentialId Unique identifier for a WebAuthn credential.
 * @param model The type of Authenticator device.
 * @param credential 
 * @param authenticatorId Unique identifier for a given Authenticator.
 * @param authenticatorName Human-readable name for an Authenticator.
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class V1Authenticator (

    /* Types of transports that may be used by an Authenticator (e.g., USB, NFC, BLE). */
    @SerialName(value = "transports")
    val transports: kotlin.collections.List<@Contextual V1AuthenticatorTransport>,

    @SerialName(value = "attestationType")
    val attestationType: kotlin.String,

    /* Identifier indicating the type of the Security Key. */
    @SerialName(value = "aaguid")
    val aaguid: kotlin.String,

    /* Unique identifier for a WebAuthn credential. */
    @SerialName(value = "credentialId")
    val credentialId: kotlin.String,

    /* The type of Authenticator device. */
    @SerialName(value = "model")
    val model: kotlin.String,

    @SerialName(value = "credential")
    val credential: Externaldatav1Credential,

    /* Unique identifier for a given Authenticator. */
    @SerialName(value = "authenticatorId")
    val authenticatorId: kotlin.String,

    /* Human-readable name for an Authenticator. */
    @SerialName(value = "authenticatorName")
    val authenticatorName: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp

) {


}

