/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyIds A list of Private Key IDs.
 */
@Serializable

data class V1CreatePrivateKeysResult (

    /* A list of Private Key IDs. */
    @SerialName(value = "privateKeyIds")
    val privateKeyIds: kotlin.collections.List<kotlin.String>

) {


}

