/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1UserParamsV2

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param users A list of Users.
 */
@Serializable

data class V1CreateUsersIntentV2 (

    /* A list of Users. */
    @SerialName(value = "users")
    val users: kotlin.collections.List<V1UserParamsV2>

) {


}

