/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1WalletAccountParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletId Unique identifier for a given Wallet.
 * @param accounts A list of wallet Accounts.
 */
@Serializable

data class V1CreateWalletAccountsIntent (

    /* Unique identifier for a given Wallet. */
    @SerialName(value = "walletId")
    val walletId: kotlin.String,

    /* A list of wallet Accounts. */
    @SerialName(value = "accounts")
    val accounts: kotlin.collections.List<V1WalletAccountParams>

) {


}

