/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AuthenticatorParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationName Human-readable name for an Organization.
 * @param rootEmail The root user's email address.
 * @param rootAuthenticator 
 * @param rootUserId Unique identifier for the root user object.
 */
@Serializable

data class V1CreateOrganizationIntent (

    /* Human-readable name for an Organization. */
    @SerialName(value = "organizationName")
    val organizationName: kotlin.String,

    /* The root user's email address. */
    @SerialName(value = "rootEmail")
    val rootEmail: kotlin.String,

    @SerialName(value = "rootAuthenticator")
    val rootAuthenticator: V1AuthenticatorParams,

    /* Unique identifier for the root user object. */
    @SerialName(value = "rootUserId")
    val rootUserId: kotlin.String? = null

) {


}

