/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1ApiOnlyUserParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiOnlyUsers A list of API-only Users to create.
 */
@Serializable

data class V1CreateApiOnlyUsersIntent (

    /* A list of API-only Users to create. */
    @SerialName(value = "apiOnlyUsers")
    val apiOnlyUsers: kotlin.collections.List<V1ApiOnlyUserParams>

) {


}

