/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param policyIds A list of unique identifiers for the created policies.
 */
@Serializable

data class V1CreatePoliciesResult (

    /* A list of unique identifiers for the created policies. */
    @SerialName(value = "policyIds")
    val policyIds: kotlin.collections.List<kotlin.String>

) {


}

