/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param addresses A list of derived addresses.
 */
@Serializable

data class V1CreateWalletAccountsResult (

    /* A list of derived addresses. */
    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<kotlin.String>

) {


}

