/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1InvitationParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param invitations A list of Invitations.
 */
@Serializable

data class V1CreateInvitationsIntent (

    /* A list of Invitations. */
    @SerialName(value = "invitations")
    val invitations: kotlin.collections.List<V1InvitationParams>

) {


}

