/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1ApiKeyParamsV2

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKeys A list of API Keys.
 * @param userId Unique identifier for a given User.
 */
@Serializable

data class V1CreateApiKeysIntentV2 (

    /* A list of API Keys. */
    @SerialName(value = "apiKeys")
    val apiKeys: kotlin.collections.List<V1ApiKeyParamsV2>,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String

) {


}

