/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1PrivateKeyParams
import com.turnkey.http.model.V1RootUserParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subOrganizationName Name for this sub-organization
 * @param rootUsers Root users to create within this sub-organization
 * @param rootQuorumThreshold The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users
 * @param privateKeys A list of Private Keys.
 */
@Serializable

data class V1CreateSubOrganizationIntentV3 (

    /* Name for this sub-organization */
    @SerialName(value = "subOrganizationName")
    val subOrganizationName: kotlin.String,

    /* Root users to create within this sub-organization */
    @SerialName(value = "rootUsers")
    val rootUsers: kotlin.collections.List<V1RootUserParams>,

    /* The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users */
    @SerialName(value = "rootQuorumThreshold")
    val rootQuorumThreshold: kotlin.Int,

    /* A list of Private Keys. */
    @SerialName(value = "privateKeys")
    val privateKeys: kotlin.collections.List<V1PrivateKeyParams>

) {


}

