/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1OauthProviderParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId The ID of the User to add an Oauth provider to
 * @param oauthProviders A list of Oauth providers.
 */
@Serializable

data class V1CreateOauthProvidersIntent (

    /* The ID of the User to add an Oauth provider to */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* A list of Oauth providers. */
    @SerialName(value = "oauthProviders")
    val oauthProviders: kotlin.collections.List<V1OauthProviderParams>

) {


}

