/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subOrganizationId 
 * @param rootUserIds 
 */
@Serializable

data class V1CreateSubOrganizationResult (

    @SerialName(value = "subOrganizationId")
    val subOrganizationId: kotlin.String,

    @SerialName(value = "rootUserIds")
    val rootUserIds: kotlin.collections.List<kotlin.String>? = null

) {


}

