/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AuthenticatorParamsV2

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authenticators A list of Authenticators.
 * @param userId Unique identifier for a given User.
 */
@Serializable

data class V1CreateAuthenticatorsIntentV2 (

    /* A list of Authenticators. */
    @SerialName(value = "authenticators")
    val authenticators: kotlin.collections.List<V1AuthenticatorParamsV2>,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String

) {


}

