/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1PrivateKeyResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subOrganizationId 
 * @param privateKeys A list of Private Key IDs and addresses.
 * @param rootUserIds 
 */
@Serializable

data class V1CreateSubOrganizationResultV3 (

    @SerialName(value = "subOrganizationId")
    val subOrganizationId: kotlin.String,

    /* A list of Private Key IDs and addresses. */
    @SerialName(value = "privateKeys")
    val privateKeys: kotlin.collections.List<V1PrivateKeyResult>,

    @SerialName(value = "rootUserIds")
    val rootUserIds: kotlin.collections.List<kotlin.String>? = null

) {


}

