/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1SmartContractInterfaceType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param smartContractAddress Corresponding contract address or program ID
 * @param smartContractInterface ABI/IDL as a JSON string
 * @param type 
 * @param label Human-readable name for a Smart Contract Interface.
 * @param notes Notes for a Smart Contract Interface.
 */
@Serializable

data class V1CreateSmartContractInterfaceIntent (

    /* Corresponding contract address or program ID */
    @SerialName(value = "smartContractAddress")
    val smartContractAddress: kotlin.String,

    /* ABI/IDL as a JSON string */
    @SerialName(value = "smartContractInterface")
    val smartContractInterface: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: V1SmartContractInterfaceType,

    /* Human-readable name for a Smart Contract Interface. */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* Notes for a Smart Contract Interface. */
    @SerialName(value = "notes")
    val notes: kotlin.String? = null

) {


}

