/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyTagName Human-readable name for a Private Key Tag.
 * @param privateKeyIds A list of Private Key IDs.
 */
@Serializable

data class V1CreatePrivateKeyTagIntent (

    /* Human-readable name for a Private Key Tag. */
    @SerialName(value = "privateKeyTagName")
    val privateKeyTagName: kotlin.String,

    /* A list of Private Key IDs. */
    @SerialName(value = "privateKeyIds")
    val privateKeyIds: kotlin.collections.List<kotlin.String>

) {


}

