/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1PrivateKeyParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeys A list of Private Keys.
 */
@Serializable

data class V1CreatePrivateKeysIntent (

    /* A list of Private Keys. */
    @SerialName(value = "privateKeys")
    val privateKeys: kotlin.collections.List<V1PrivateKeyParams>

) {


}

