/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1Effect
import com.turnkey.http.model.V1Selector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param policyName Human-readable name for a Policy.
 * @param selectors A list of simple functions each including a subject, target and boolean. See Policy Engine Language section for additional details.
 * @param effect 
 * @param notes 
 */
@Serializable

data class V1CreatePolicyIntent (

    /* Human-readable name for a Policy. */
    @SerialName(value = "policyName")
    val policyName: kotlin.String,

    /* A list of simple functions each including a subject, target and boolean. See Policy Engine Language section for additional details. */
    @SerialName(value = "selectors")
    val selectors: kotlin.collections.List<V1Selector>,

    @Contextual @SerialName(value = "effect")
    val effect: V1Effect,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null

) {


}

