/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given Organization. If the request is being made by a user and their Sub-Organization ID is unknown, this can be the Parent Organization ID. However, using the Sub-Organization ID is preferred due to performance reasons.
 * @param organizationName Human-readable name for an Organization.
 * @param userId Unique identifier for a given User.
 * @param username Human-readable name for a User.
 * @param apiKeyId Unique identifier for the created API key.
 * @param credentialBundle HPKE encrypted credential bundle
 */
@Serializable

data class V1CreateReadWriteSessionResult (

    /* Unique identifier for a given Organization. If the request is being made by a user and their Sub-Organization ID is unknown, this can be the Parent Organization ID. However, using the Sub-Organization ID is preferred due to performance reasons. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Human-readable name for an Organization. */
    @SerialName(value = "organizationName")
    val organizationName: kotlin.String,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Human-readable name for a User. */
    @SerialName(value = "username")
    val username: kotlin.String,

    /* Unique identifier for the created API key. */
    @SerialName(value = "apiKeyId")
    val apiKeyId: kotlin.String,

    /* HPKE encrypted credential bundle */
    @SerialName(value = "credentialBundle")
    val credentialBundle: kotlin.String

) {


}

