/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param invitationIds A list of Invitation IDs
 */
@Serializable

data class V1CreateInvitationsResult (

    /* A list of Invitation IDs */
    @SerialName(value = "invitationIds")
    val invitationIds: kotlin.collections.List<kotlin.String>

) {


}

