/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1WalletResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subOrganizationId 
 * @param wallet 
 * @param rootUserIds 
 */
@Serializable

data class V1CreateSubOrganizationResultV6 (

    @SerialName(value = "subOrganizationId")
    val subOrganizationId: kotlin.String,

    @SerialName(value = "wallet")
    val wallet: V1WalletResult? = null,

    @SerialName(value = "rootUserIds")
    val rootUserIds: kotlin.collections.List<kotlin.String>? = null

) {


}

