/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param targetPublicKey Client-side public key generated by the user, to which the read write session bundle (credentials) will be encrypted.
 * @param email Email of the user to create a read write session for
 * @param apiKeyName Optional human-readable name for an API Key. If none provided, default to Read Write Session - <Timestamp>
 * @param expirationSeconds Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used.
 */
@Serializable

data class V1CreateReadWriteSessionIntent (

    /* Client-side public key generated by the user, to which the read write session bundle (credentials) will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String,

    /* Email of the user to create a read write session for */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* Optional human-readable name for an API Key. If none provided, default to Read Write Session - <Timestamp> */
    @SerialName(value = "apiKeyName")
    val apiKeyName: kotlin.String? = null,

    /* Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null

) {


}

