/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param smartContractInterfaceId The ID of the created Smart Contract Interface.
 */
@Serializable

data class V1CreateSmartContractInterfaceResult (

    /* The ID of the created Smart Contract Interface. */
    @SerialName(value = "smartContractInterfaceId")
    val smartContractInterfaceId: kotlin.String

) {


}

