/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId Unique identifier for a given User.
 * @param authenticatorIds A list of Authenticator IDs.
 */
@Serializable

data class V1DeleteAuthenticatorsIntent (

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* A list of Authenticator IDs. */
    @SerialName(value = "authenticatorIds")
    val authenticatorIds: kotlin.collections.List<kotlin.String>

) {


}

