/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyIds A list of private key unique identifiers that were removed
 */
@Serializable

data class V1DeletePrivateKeysResult (

    /* A list of private key unique identifiers that were removed */
    @SerialName(value = "privateKeyIds")
    val privateKeyIds: kotlin.collections.List<kotlin.String>

) {


}

