/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userTagIds A list of User Tag IDs.
 * @param userIds A list of User IDs.
 */
@Serializable

data class V1DeleteUserTagsResult (

    /* A list of User Tag IDs. */
    @SerialName(value = "userTagIds")
    val userTagIds: kotlin.collections.List<kotlin.String>,

    /* A list of User IDs. */
    @SerialName(value = "userIds")
    val userIds: kotlin.collections.List<kotlin.String>

) {


}

