/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subOrganizationUuid Unique identifier of the sub organization that was removed
 */
@Serializable

data class V1DeleteSubOrganizationResult (

    /* Unique identifier of the sub organization that was removed */
    @SerialName(value = "subOrganizationUuid")
    val subOrganizationUuid: kotlin.String

) {


}

