/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oauth2CredentialId The ID of the OAuth 2.0 credential to delete
 */
@Serializable

data class V1DeleteOauth2CredentialIntent (

    /* The ID of the OAuth 2.0 credential to delete */
    @SerialName(value = "oauth2CredentialId")
    val oauth2CredentialId: kotlin.String

) {


}

