/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyIds List of unique identifiers for private keys within an organization
 * @param deleteWithoutExport Optional parameter for deleting the private keys, even if any have not been previously exported. If they have been exported, this field is ignored.
 */
@Serializable

data class V1DeletePrivateKeysIntent (

    /* List of unique identifiers for private keys within an organization */
    @SerialName(value = "privateKeyIds")
    val privateKeyIds: kotlin.collections.List<kotlin.String>,

    /* Optional parameter for deleting the private keys, even if any have not been previously exported. If they have been exported, this field is ignored. */
    @SerialName(value = "deleteWithoutExport")
    val deleteWithoutExport: kotlin.Boolean? = null

) {


}

