/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyId Unique identifier for a given Private Key.
 */
@Serializable

data class V1DisablePrivateKeyIntent (

    /* Unique identifier for a given Private Key. */
    @SerialName(value = "privateKeyId")
    val privateKeyId: kotlin.String

) {


}

