/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1EmailCustomizationParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email Email of the authenticating user.
 * @param targetPublicKey Client-side public key generated by the user, to which the email auth bundle (credentials) will be encrypted.
 * @param apiKeyName Optional human-readable name for an API Key. If none provided, default to Email Auth - <Timestamp>
 * @param expirationSeconds Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used.
 * @param emailCustomization 
 * @param invalidateExisting Invalidate all other previously generated Email Auth API keys
 * @param sendFromEmailAddress Optional custom email address from which to send the email
 * @param sendFromEmailSenderName Optional custom sender name for use with sendFromEmailAddress; if left empty, will default to 'Notifications'
 * @param replyToEmailAddress Optional custom email address to use as reply-to
 */
@Serializable

data class V1EmailAuthIntent (

    /* Email of the authenticating user. */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* Client-side public key generated by the user, to which the email auth bundle (credentials) will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String,

    /* Optional human-readable name for an API Key. If none provided, default to Email Auth - <Timestamp> */
    @SerialName(value = "apiKeyName")
    val apiKeyName: kotlin.String? = null,

    /* Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    @SerialName(value = "emailCustomization")
    val emailCustomization: V1EmailCustomizationParams? = null,

    /* Invalidate all other previously generated Email Auth API keys */
    @SerialName(value = "invalidateExisting")
    val invalidateExisting: kotlin.Boolean? = null,

    /* Optional custom email address from which to send the email */
    @SerialName(value = "sendFromEmailAddress")
    val sendFromEmailAddress: kotlin.String? = null,

    /* Optional custom sender name for use with sendFromEmailAddress; if left empty, will default to 'Notifications' */
    @SerialName(value = "sendFromEmailSenderName")
    val sendFromEmailSenderName: kotlin.String? = null,

    /* Optional custom email address to use as reply-to */
    @SerialName(value = "replyToEmailAddress")
    val replyToEmailAddress: kotlin.String? = null

) {


}

