/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param appName The name of the application.
 * @param logoUrl A URL pointing to a logo in PNG format. Note this logo will be resized to fit into 340px x 124px.
 * @param magicLinkTemplate A template for the URL to be used in a magic link button, e.g. `https://dapp.xyz/%s`. The auth bundle will be interpolated into the `%s`.
 * @param templateVariables JSON object containing key/value pairs to be used with custom templates.
 * @param templateId Unique identifier for a given Email Template. If not specified, the default is the most recent Email Template.
 */
@Serializable

data class V1EmailCustomizationParams (

    /* The name of the application. */
    @SerialName(value = "appName")
    val appName: kotlin.String? = null,

    /* A URL pointing to a logo in PNG format. Note this logo will be resized to fit into 340px x 124px. */
    @SerialName(value = "logoUrl")
    val logoUrl: kotlin.String? = null,

    /* A template for the URL to be used in a magic link button, e.g. `https://dapp.xyz/%s`. The auth bundle will be interpolated into the `%s`. */
    @SerialName(value = "magicLinkTemplate")
    val magicLinkTemplate: kotlin.String? = null,

    /* JSON object containing key/value pairs to be used with custom templates. */
    @SerialName(value = "templateVariables")
    val templateVariables: kotlin.String? = null,

    /* Unique identifier for a given Email Template. If not specified, the default is the most recent Email Template. */
    @SerialName(value = "templateId")
    val templateId: kotlin.String? = null

) {


}

