/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address Address to identify Wallet Account.
 * @param exportBundle Export bundle containing a private key encrypted by the client's target public key.
 */
@Serializable

data class V1ExportWalletAccountResult (

    /* Address to identify Wallet Account. */
    @SerialName(value = "address")
    val address: kotlin.String,

    /* Export bundle containing a private key encrypted by the client's target public key. */
    @SerialName(value = "exportBundle")
    val exportBundle: kotlin.String

) {


}

