/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address Address to identify Wallet Account.
 * @param targetPublicKey Client-side public key generated by the user, to which the export bundle will be encrypted.
 */
@Serializable

data class V1ExportWalletAccountIntent (

    /* Address to identify Wallet Account. */
    @SerialName(value = "address")
    val address: kotlin.String,

    /* Client-side public key generated by the user, to which the export bundle will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String

) {


}

