/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1MnemonicLanguage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletId Unique identifier for a given Wallet.
 * @param targetPublicKey Client-side public key generated by the user, to which the export bundle will be encrypted.
 * @param language 
 */
@Serializable

data class V1ExportWalletIntent (

    /* Unique identifier for a given Wallet. */
    @SerialName(value = "walletId")
    val walletId: kotlin.String,

    /* Client-side public key generated by the user, to which the export bundle will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String,

    @Contextual @SerialName(value = "language")
    val language: V1MnemonicLanguage? = null

) {


}

