/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY,FEATURE_NAME_WEBAUTHN_ORIGINS,FEATURE_NAME_EMAIL_AUTH,FEATURE_NAME_EMAIL_RECOVERY,FEATURE_NAME_WEBHOOK,FEATURE_NAME_SMS_AUTH,FEATURE_NAME_OTP_EMAIL_AUTH,FEATURE_NAME_AUTH_PROXY
 */
@Serializable
enum class V1FeatureName(val value: kotlin.String) {

    @SerialName(value = "FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY")
    FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY("FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY"),

    @SerialName(value = "FEATURE_NAME_WEBAUTHN_ORIGINS")
    FEATURE_NAME_WEBAUTHN_ORIGINS("FEATURE_NAME_WEBAUTHN_ORIGINS"),

    @SerialName(value = "FEATURE_NAME_EMAIL_AUTH")
    FEATURE_NAME_EMAIL_AUTH("FEATURE_NAME_EMAIL_AUTH"),

    @SerialName(value = "FEATURE_NAME_EMAIL_RECOVERY")
    FEATURE_NAME_EMAIL_RECOVERY("FEATURE_NAME_EMAIL_RECOVERY"),

    @SerialName(value = "FEATURE_NAME_WEBHOOK")
    FEATURE_NAME_WEBHOOK("FEATURE_NAME_WEBHOOK"),

    @SerialName(value = "FEATURE_NAME_SMS_AUTH")
    FEATURE_NAME_SMS_AUTH("FEATURE_NAME_SMS_AUTH"),

    @SerialName(value = "FEATURE_NAME_OTP_EMAIL_AUTH")
    FEATURE_NAME_OTP_EMAIL_AUTH("FEATURE_NAME_OTP_EMAIL_AUTH"),

    @SerialName(value = "FEATURE_NAME_AUTH_PROXY")
    FEATURE_NAME_AUTH_PROXY("FEATURE_NAME_AUTH_PROXY");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1FeatureName) "$data" else null

        /**
         * Returns a valid [V1FeatureName] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1FeatureName? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


