/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: FIAT_ON_RAMP_PROVIDER_COINBASE,FIAT_ON_RAMP_PROVIDER_MOONPAY
 */
@Serializable
enum class V1FiatOnRampProvider(val value: kotlin.String) {

    @SerialName(value = "FIAT_ON_RAMP_PROVIDER_COINBASE")
    FIAT_ON_RAMP_PROVIDER_COINBASE("FIAT_ON_RAMP_PROVIDER_COINBASE"),

    @SerialName(value = "FIAT_ON_RAMP_PROVIDER_MOONPAY")
    FIAT_ON_RAMP_PROVIDER_MOONPAY("FIAT_ON_RAMP_PROVIDER_MOONPAY");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1FiatOnRampProvider) "$data" else null

        /**
         * Returns a valid [V1FiatOnRampProvider] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1FiatOnRampProvider? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


