/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: FIAT_ON_RAMP_CRYPTO_CURRENCY_BTC,FIAT_ON_RAMP_CRYPTO_CURRENCY_ETH,FIAT_ON_RAMP_CRYPTO_CURRENCY_SOL,FIAT_ON_RAMP_CRYPTO_CURRENCY_USDC
 */
@Serializable
enum class V1FiatOnRampCryptoCurrency(val value: kotlin.String) {

    @SerialName(value = "FIAT_ON_RAMP_CRYPTO_CURRENCY_BTC")
    FIAT_ON_RAMP_CRYPTO_CURRENCY_BTC("FIAT_ON_RAMP_CRYPTO_CURRENCY_BTC"),

    @SerialName(value = "FIAT_ON_RAMP_CRYPTO_CURRENCY_ETH")
    FIAT_ON_RAMP_CRYPTO_CURRENCY_ETH("FIAT_ON_RAMP_CRYPTO_CURRENCY_ETH"),

    @SerialName(value = "FIAT_ON_RAMP_CRYPTO_CURRENCY_SOL")
    FIAT_ON_RAMP_CRYPTO_CURRENCY_SOL("FIAT_ON_RAMP_CRYPTO_CURRENCY_SOL"),

    @SerialName(value = "FIAT_ON_RAMP_CRYPTO_CURRENCY_USDC")
    FIAT_ON_RAMP_CRYPTO_CURRENCY_USDC("FIAT_ON_RAMP_CRYPTO_CURRENCY_USDC");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1FiatOnRampCryptoCurrency) "$data" else null

        /**
         * Returns a valid [V1FiatOnRampCryptoCurrency] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1FiatOnRampCryptoCurrency? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


