/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BITCOIN,FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_ETHEREUM,FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_SOLANA,FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BASE
 */
@Serializable
enum class V1FiatOnRampBlockchainNetwork(val value: kotlin.String) {

    @SerialName(value = "FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BITCOIN")
    FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BITCOIN("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BITCOIN"),

    @SerialName(value = "FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_ETHEREUM")
    FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_ETHEREUM("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_ETHEREUM"),

    @SerialName(value = "FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_SOLANA")
    FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_SOLANA("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_SOLANA"),

    @SerialName(value = "FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BASE")
    FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BASE("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BASE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1FiatOnRampBlockchainNetwork) "$data" else null

        /**
         * Returns a valid [V1FiatOnRampBlockchainNetwork] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1FiatOnRampBlockchainNetwork? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


