/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: FIAT_ON_RAMP_PAYMENT_METHOD_CREDIT_DEBIT_CARD,FIAT_ON_RAMP_PAYMENT_METHOD_APPLE_PAY,FIAT_ON_RAMP_PAYMENT_METHOD_GBP_BANK_TRANSFER,FIAT_ON_RAMP_PAYMENT_METHOD_GBP_OPEN_BANKING_PAYMENT,FIAT_ON_RAMP_PAYMENT_METHOD_GOOGLE_PAY,FIAT_ON_RAMP_PAYMENT_METHOD_SEPA_BANK_TRANSFER,FIAT_ON_RAMP_PAYMENT_METHOD_PIX_INSTANT_PAYMENT,FIAT_ON_RAMP_PAYMENT_METHOD_PAYPAL,FIAT_ON_RAMP_PAYMENT_METHOD_VENMO,FIAT_ON_RAMP_PAYMENT_METHOD_MOONPAY_BALANCE,FIAT_ON_RAMP_PAYMENT_METHOD_CRYPTO_ACCOUNT,FIAT_ON_RAMP_PAYMENT_METHOD_FIAT_WALLET,FIAT_ON_RAMP_PAYMENT_METHOD_ACH_BANK_ACCOUNT
 */
@Serializable
enum class V1FiatOnRampPaymentMethod(val value: kotlin.String) {

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_CREDIT_DEBIT_CARD")
    FIAT_ON_RAMP_PAYMENT_METHOD_CREDIT_DEBIT_CARD("FIAT_ON_RAMP_PAYMENT_METHOD_CREDIT_DEBIT_CARD"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_APPLE_PAY")
    FIAT_ON_RAMP_PAYMENT_METHOD_APPLE_PAY("FIAT_ON_RAMP_PAYMENT_METHOD_APPLE_PAY"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_GBP_BANK_TRANSFER")
    FIAT_ON_RAMP_PAYMENT_METHOD_GBP_BANK_TRANSFER("FIAT_ON_RAMP_PAYMENT_METHOD_GBP_BANK_TRANSFER"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_GBP_OPEN_BANKING_PAYMENT")
    FIAT_ON_RAMP_PAYMENT_METHOD_GBP_OPEN_BANKING_PAYMENT("FIAT_ON_RAMP_PAYMENT_METHOD_GBP_OPEN_BANKING_PAYMENT"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_GOOGLE_PAY")
    FIAT_ON_RAMP_PAYMENT_METHOD_GOOGLE_PAY("FIAT_ON_RAMP_PAYMENT_METHOD_GOOGLE_PAY"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_SEPA_BANK_TRANSFER")
    FIAT_ON_RAMP_PAYMENT_METHOD_SEPA_BANK_TRANSFER("FIAT_ON_RAMP_PAYMENT_METHOD_SEPA_BANK_TRANSFER"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_PIX_INSTANT_PAYMENT")
    FIAT_ON_RAMP_PAYMENT_METHOD_PIX_INSTANT_PAYMENT("FIAT_ON_RAMP_PAYMENT_METHOD_PIX_INSTANT_PAYMENT"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_PAYPAL")
    FIAT_ON_RAMP_PAYMENT_METHOD_PAYPAL("FIAT_ON_RAMP_PAYMENT_METHOD_PAYPAL"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_VENMO")
    FIAT_ON_RAMP_PAYMENT_METHOD_VENMO("FIAT_ON_RAMP_PAYMENT_METHOD_VENMO"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_MOONPAY_BALANCE")
    FIAT_ON_RAMP_PAYMENT_METHOD_MOONPAY_BALANCE("FIAT_ON_RAMP_PAYMENT_METHOD_MOONPAY_BALANCE"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_CRYPTO_ACCOUNT")
    FIAT_ON_RAMP_PAYMENT_METHOD_CRYPTO_ACCOUNT("FIAT_ON_RAMP_PAYMENT_METHOD_CRYPTO_ACCOUNT"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_FIAT_WALLET")
    FIAT_ON_RAMP_PAYMENT_METHOD_FIAT_WALLET("FIAT_ON_RAMP_PAYMENT_METHOD_FIAT_WALLET"),

    @SerialName(value = "FIAT_ON_RAMP_PAYMENT_METHOD_ACH_BANK_ACCOUNT")
    FIAT_ON_RAMP_PAYMENT_METHOD_ACH_BANK_ACCOUNT("FIAT_ON_RAMP_PAYMENT_METHOD_ACH_BANK_ACCOUNT");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1FiatOnRampPaymentMethod) "$data" else null

        /**
         * Returns a valid [V1FiatOnRampPaymentMethod] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1FiatOnRampPaymentMethod? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


