/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1Pagination

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for the parent organization. This is used to find sub-organizations within it.
 * @param filterType Specifies the type of filter to apply, i.e 'CREDENTIAL_ID', 'NAME', 'USERNAME', 'EMAIL', 'PHONE_NUMBER', 'OIDC_TOKEN', 'WALLET_ACCOUNT_ADDRESS' or 'PUBLIC_KEY'
 * @param filterValue The value of the filter to apply for the specified type. For example, a specific email or name string.
 * @param paginationOptions 
 */
@Serializable

data class V1GetSubOrgIdsRequest (

    /* Unique identifier for the parent organization. This is used to find sub-organizations within it. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Specifies the type of filter to apply, i.e 'CREDENTIAL_ID', 'NAME', 'USERNAME', 'EMAIL', 'PHONE_NUMBER', 'OIDC_TOKEN', 'WALLET_ACCOUNT_ADDRESS' or 'PUBLIC_KEY' */
    @SerialName(value = "filterType")
    val filterType: kotlin.String? = null,

    /* The value of the filter to apply for the specified type. For example, a specific email or name string. */
    @SerialName(value = "filterValue")
    val filterValue: kotlin.String? = null,

    @SerialName(value = "paginationOptions")
    val paginationOptions: V1Pagination? = null

) {


}

