/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1Pagination

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given organization.
 * @param walletId Unique identifier for a given wallet. If not provided, all accounts for the organization will be returned.
 * @param includeWalletDetails Optional flag to specify if the wallet details should be included in the response. Default = false.
 * @param paginationOptions 
 */
@Serializable

data class V1GetWalletAccountsRequest (

    /* Unique identifier for a given organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Unique identifier for a given wallet. If not provided, all accounts for the organization will be returned. */
    @SerialName(value = "walletId")
    val walletId: kotlin.String? = null,

    /* Optional flag to specify if the wallet details should be included in the response. Default = false. */
    @SerialName(value = "includeWalletDetails")
    val includeWalletDetails: kotlin.Boolean? = null,

    @SerialName(value = "paginationOptions")
    val paginationOptions: V1Pagination? = null

) {


}

