/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given organization.
 * @param userId Unique identifier for a given user.
 */
@Serializable

data class V1GetOauthProvidersRequest (

    /* Unique identifier for a given organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Unique identifier for a given user. */
    @SerialName(value = "userId")
    val userId: kotlin.String? = null

) {


}

