/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attestationDocument Raw (CBOR-encoded) attestation document.
 */
@Serializable

data class V1GetAttestationDocumentResponse (

    /* Raw (CBOR-encoded) attestation document. */
    @SerialName(value = "attestationDocument")
    val attestationDocument: kotlin.ByteArray

) {


}

