/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externalactivityv1PolicyEvaluation

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param policyEvaluations 
 */
@Serializable

data class V1GetPolicyEvaluationsResponse (

    @SerialName(value = "policyEvaluations")
    val policyEvaluations: kotlin.collections.List<Externalactivityv1PolicyEvaluation>

) {


}

