/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1SmartContractInterface

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param smartContractInterfaces A list of smart contract interfaces.
 */
@Serializable

data class V1GetSmartContractInterfacesResponse (

    /* A list of smart contract interfaces. */
    @SerialName(value = "smartContractInterfaces")
    val smartContractInterfaces: kotlin.collections.List<V1SmartContractInterface>

) {


}

