/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1ApiKey

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKeys A list of API keys.
 */
@Serializable

data class V1GetApiKeysResponse (

    /* A list of API keys. */
    @SerialName(value = "apiKeys")
    val apiKeys: kotlin.collections.List<V1ApiKey>

) {


}

