/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1OauthProvider

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oauthProviders A list of Oauth providers.
 */
@Serializable

data class V1GetOauthProvidersResponse (

    /* A list of Oauth providers. */
    @SerialName(value = "oauthProviders")
    val oauthProviders: kotlin.collections.List<V1OauthProvider>

) {


}

