/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given Organization.
 * @param oauth2CredentialId Unique identifier for a given OAuth 2.0 Credential.
 */
@Serializable

data class V1GetOauth2CredentialRequest (

    /* Unique identifier for a given Organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Unique identifier for a given OAuth 2.0 Credential. */
    @SerialName(value = "oauth2CredentialId")
    val oauth2CredentialId: kotlin.String

) {


}

