/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1ActivityStatus
import com.turnkey.http.model.V1ActivityType
import com.turnkey.http.model.V1Pagination

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given organization.
 * @param filterByStatus Array of activity statuses filtering which activities will be listed in the response.
 * @param paginationOptions 
 * @param filterByType Array of activity types filtering which activities will be listed in the response.
 */
@Serializable

data class V1GetActivitiesRequest (

    /* Unique identifier for a given organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Array of activity statuses filtering which activities will be listed in the response. */
    @SerialName(value = "filterByStatus")
    val filterByStatus: kotlin.collections.List<@Contextual V1ActivityStatus>? = null,

    @SerialName(value = "paginationOptions")
    val paginationOptions: V1Pagination? = null,

    /* Array of activity types filtering which activities will be listed in the response. */
    @SerialName(value = "filterByType")
    val filterByType: kotlin.collections.List<@Contextual V1ActivityType>? = null

) {


}

