/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given Organization.
 * @param ephemeralKey Hex encoded ephemeral public key.
 */
@Serializable

data class V1GetBootProofRequest (

    /* Unique identifier for a given Organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Hex encoded ephemeral public key. */
    @SerialName(value = "ephemeralKey")
    val ephemeralKey: kotlin.String

) {


}

