/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1WalletAccountParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId The ID of the User importing a Wallet.
 * @param walletName Human-readable name for a Wallet.
 * @param encryptedBundle Bundle containing a wallet mnemonic encrypted to the enclave's target public key.
 * @param accounts A list of wallet Accounts.
 */
@Serializable

data class V1ImportWalletIntent (

    /* The ID of the User importing a Wallet. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Human-readable name for a Wallet. */
    @SerialName(value = "walletName")
    val walletName: kotlin.String,

    /* Bundle containing a wallet mnemonic encrypted to the enclave's target public key. */
    @SerialName(value = "encryptedBundle")
    val encryptedBundle: kotlin.String,

    /* A list of wallet Accounts. */
    @SerialName(value = "accounts")
    val accounts: kotlin.collections.List<V1WalletAccountParams>

) {


}

