/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AddressFormat
import com.turnkey.http.model.V1Curve

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId The ID of the User importing a Private Key.
 * @param privateKeyName Human-readable name for a Private Key.
 * @param encryptedBundle Bundle containing a raw private key encrypted to the enclave's target public key.
 * @param curve 
 * @param addressFormats Cryptocurrency-specific formats for a derived address (e.g., Ethereum).
 */
@Serializable

data class V1ImportPrivateKeyIntent (

    /* The ID of the User importing a Private Key. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Human-readable name for a Private Key. */
    @SerialName(value = "privateKeyName")
    val privateKeyName: kotlin.String,

    /* Bundle containing a raw private key encrypted to the enclave's target public key. */
    @SerialName(value = "encryptedBundle")
    val encryptedBundle: kotlin.String,

    @Contextual @SerialName(value = "curve")
    val curve: V1Curve,

    /* Cryptocurrency-specific formats for a derived address (e.g., Ethereum). */
    @SerialName(value = "addressFormats")
    val addressFormats: kotlin.collections.List<@Contextual V1AddressFormat>

) {


}

