/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Immutableactivityv1Address

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyId Unique identifier for a Private Key.
 * @param addresses A list of addresses.
 */
@Serializable

data class V1ImportPrivateKeyResult (

    /* Unique identifier for a Private Key. */
    @SerialName(value = "privateKeyId")
    val privateKeyId: kotlin.String,

    /* A list of addresses. */
    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<Immutableactivityv1Address>

) {


}

