/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AccessType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param receiverUserName The name of the intended Invitation recipient.
 * @param receiverUserEmail The email address of the intended Invitation recipient.
 * @param receiverUserTags A list of tags assigned to the Invitation recipient. This field, if not needed, should be an empty array in your request body.
 * @param accessType 
 * @param senderUserId Unique identifier for the Sender of an Invitation.
 */
@Serializable

data class V1InvitationParams (

    /* The name of the intended Invitation recipient. */
    @SerialName(value = "receiverUserName")
    val receiverUserName: kotlin.String,

    /* The email address of the intended Invitation recipient. */
    @SerialName(value = "receiverUserEmail")
    val receiverUserEmail: kotlin.String,

    /* A list of tags assigned to the Invitation recipient. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "receiverUserTags")
    val receiverUserTags: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "accessType")
    val accessType: V1AccessType,

    /* Unique identifier for the Sender of an Invitation. */
    @SerialName(value = "senderUserId")
    val senderUserId: kotlin.String

) {


}

