/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1EmailCustomizationParams
import com.turnkey.http.model.V1SmsCustomizationParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param otpType Whether to send OTP via SMS or email. Possible values: OTP_TYPE_SMS, OTP_TYPE_EMAIL
 * @param contact Email or phone number to send the OTP code to
 * @param otpLength Optional length of the OTP code. Default = 9
 * @param emailCustomization 
 * @param smsCustomization 
 * @param userIdentifier Optional client-generated user identifier to enable per-user rate limiting for SMS auth. We recommend using a hash of the client-side IP address.
 * @param sendFromEmailAddress Optional custom email address from which to send the OTP email
 * @param alphanumeric Optional flag to specify if the OTP code should be alphanumeric (Crockford’s Base32). Default = true
 * @param sendFromEmailSenderName Optional custom sender name for use with sendFromEmailAddress; if left empty, will default to 'Notifications'
 * @param expirationSeconds Expiration window (in seconds) indicating how long the OTP is valid for. If not provided, a default of 5 minutes will be used. Maximum value is 600 seconds (10 minutes)
 * @param replyToEmailAddress Optional custom email address to use as reply-to
 */
@Serializable

data class V1InitOtpIntent (

    /* Whether to send OTP via SMS or email. Possible values: OTP_TYPE_SMS, OTP_TYPE_EMAIL */
    @SerialName(value = "otpType")
    val otpType: kotlin.String,

    /* Email or phone number to send the OTP code to */
    @SerialName(value = "contact")
    val contact: kotlin.String,

    /* Optional length of the OTP code. Default = 9 */
    @SerialName(value = "otpLength")
    val otpLength: kotlin.Int? = null,

    @SerialName(value = "emailCustomization")
    val emailCustomization: V1EmailCustomizationParams? = null,

    @SerialName(value = "smsCustomization")
    val smsCustomization: V1SmsCustomizationParams? = null,

    /* Optional client-generated user identifier to enable per-user rate limiting for SMS auth. We recommend using a hash of the client-side IP address. */
    @SerialName(value = "userIdentifier")
    val userIdentifier: kotlin.String? = null,

    /* Optional custom email address from which to send the OTP email */
    @SerialName(value = "sendFromEmailAddress")
    val sendFromEmailAddress: kotlin.String? = null,

    /* Optional flag to specify if the OTP code should be alphanumeric (Crockford’s Base32). Default = true */
    @SerialName(value = "alphanumeric")
    val alphanumeric: kotlin.Boolean? = null,

    /* Optional custom sender name for use with sendFromEmailAddress; if left empty, will default to 'Notifications' */
    @SerialName(value = "sendFromEmailSenderName")
    val sendFromEmailSenderName: kotlin.String? = null,

    /* Expiration window (in seconds) indicating how long the OTP is valid for. If not provided, a default of 5 minutes will be used. Maximum value is 600 seconds (10 minutes) */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    /* Optional custom email address to use as reply-to */
    @SerialName(value = "replyToEmailAddress")
    val replyToEmailAddress: kotlin.String? = null

) {


}

