/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1EmailCustomizationParams
import com.turnkey.http.model.V1SmsCustomizationParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param otpType Enum to specifiy whether to send OTP via SMS or email
 * @param contact Email or phone number to send the OTP code to
 * @param emailCustomization 
 * @param smsCustomization 
 * @param userIdentifier Optional client-generated user identifier to enable per-user rate limiting for SMS auth. We recommend using a hash of the client-side IP address.
 * @param sendFromEmailAddress Optional custom email address from which to send the OTP email
 * @param sendFromEmailSenderName Optional custom sender name for use with sendFromEmailAddress; if left empty, will default to 'Notifications'
 * @param replyToEmailAddress Optional custom email address to use as reply-to
 */
@Serializable

data class V1InitOtpAuthIntent (

    /* Enum to specifiy whether to send OTP via SMS or email */
    @SerialName(value = "otpType")
    val otpType: kotlin.String,

    /* Email or phone number to send the OTP code to */
    @SerialName(value = "contact")
    val contact: kotlin.String,

    @SerialName(value = "emailCustomization")
    val emailCustomization: V1EmailCustomizationParams? = null,

    @SerialName(value = "smsCustomization")
    val smsCustomization: V1SmsCustomizationParams? = null,

    /* Optional client-generated user identifier to enable per-user rate limiting for SMS auth. We recommend using a hash of the client-side IP address. */
    @SerialName(value = "userIdentifier")
    val userIdentifier: kotlin.String? = null,

    /* Optional custom email address from which to send the OTP email */
    @SerialName(value = "sendFromEmailAddress")
    val sendFromEmailAddress: kotlin.String? = null,

    /* Optional custom sender name for use with sendFromEmailAddress; if left empty, will default to 'Notifications' */
    @SerialName(value = "sendFromEmailSenderName")
    val sendFromEmailSenderName: kotlin.String? = null,

    /* Optional custom email address to use as reply-to */
    @SerialName(value = "replyToEmailAddress")
    val replyToEmailAddress: kotlin.String? = null

) {


}

