/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId The ID of the User importing a Private Key.
 */
@Serializable

data class V1InitImportPrivateKeyIntent (

    /* The ID of the User importing a Private Key. */
    @SerialName(value = "userId")
    val userId: kotlin.String

) {


}

