/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: INVITATION_STATUS_CREATED,INVITATION_STATUS_ACCEPTED,INVITATION_STATUS_REVOKED
 */
@Serializable
enum class V1InvitationStatus(val value: kotlin.String) {

    @SerialName(value = "INVITATION_STATUS_CREATED")
    INVITATION_STATUS_CREATED("INVITATION_STATUS_CREATED"),

    @SerialName(value = "INVITATION_STATUS_ACCEPTED")
    INVITATION_STATUS_ACCEPTED("INVITATION_STATUS_ACCEPTED"),

    @SerialName(value = "INVITATION_STATUS_REVOKED")
    INVITATION_STATUS_REVOKED("INVITATION_STATUS_REVOKED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1InvitationStatus) "$data" else null

        /**
         * Returns a valid [V1InvitationStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1InvitationStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


