/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.BillingActivateBillingTierIntent
import com.turnkey.http.model.BillingDeletePaymentMethodIntent
import com.turnkey.http.model.BillingSetPaymentMethodIntent
import com.turnkey.http.model.BillingSetPaymentMethodIntentV2
import com.turnkey.http.model.V1AcceptInvitationIntent
import com.turnkey.http.model.V1AcceptInvitationIntentV2
import com.turnkey.http.model.V1ApproveActivityIntent
import com.turnkey.http.model.V1CreateApiKeysIntent
import com.turnkey.http.model.V1CreateApiKeysIntentV2
import com.turnkey.http.model.V1CreateApiOnlyUsersIntent
import com.turnkey.http.model.V1CreateAuthenticatorsIntent
import com.turnkey.http.model.V1CreateAuthenticatorsIntentV2
import com.turnkey.http.model.V1CreateInvitationsIntent
import com.turnkey.http.model.V1CreateOauth2CredentialIntent
import com.turnkey.http.model.V1CreateOauthProvidersIntent
import com.turnkey.http.model.V1CreateOrganizationIntent
import com.turnkey.http.model.V1CreateOrganizationIntentV2
import com.turnkey.http.model.V1CreatePoliciesIntent
import com.turnkey.http.model.V1CreatePolicyIntent
import com.turnkey.http.model.V1CreatePolicyIntentV2
import com.turnkey.http.model.V1CreatePolicyIntentV3
import com.turnkey.http.model.V1CreatePrivateKeyTagIntent
import com.turnkey.http.model.V1CreatePrivateKeysIntent
import com.turnkey.http.model.V1CreatePrivateKeysIntentV2
import com.turnkey.http.model.V1CreateReadWriteSessionIntent
import com.turnkey.http.model.V1CreateReadWriteSessionIntentV2
import com.turnkey.http.model.V1CreateSmartContractInterfaceIntent
import com.turnkey.http.model.V1CreateSubOrganizationIntent
import com.turnkey.http.model.V1CreateSubOrganizationIntentV2
import com.turnkey.http.model.V1CreateSubOrganizationIntentV3
import com.turnkey.http.model.V1CreateSubOrganizationIntentV4
import com.turnkey.http.model.V1CreateSubOrganizationIntentV5
import com.turnkey.http.model.V1CreateSubOrganizationIntentV6
import com.turnkey.http.model.V1CreateSubOrganizationIntentV7
import com.turnkey.http.model.V1CreateUserTagIntent
import com.turnkey.http.model.V1CreateUsersIntent
import com.turnkey.http.model.V1CreateUsersIntentV2
import com.turnkey.http.model.V1CreateUsersIntentV3
import com.turnkey.http.model.V1CreateWalletAccountsIntent
import com.turnkey.http.model.V1CreateWalletIntent
import com.turnkey.http.model.V1DeleteApiKeysIntent
import com.turnkey.http.model.V1DeleteAuthenticatorsIntent
import com.turnkey.http.model.V1DeleteInvitationIntent
import com.turnkey.http.model.V1DeleteOauth2CredentialIntent
import com.turnkey.http.model.V1DeleteOauthProvidersIntent
import com.turnkey.http.model.V1DeleteOrganizationIntent
import com.turnkey.http.model.V1DeletePolicyIntent
import com.turnkey.http.model.V1DeletePrivateKeyTagsIntent
import com.turnkey.http.model.V1DeletePrivateKeysIntent
import com.turnkey.http.model.V1DeleteSmartContractInterfaceIntent
import com.turnkey.http.model.V1DeleteSubOrganizationIntent
import com.turnkey.http.model.V1DeleteUserTagsIntent
import com.turnkey.http.model.V1DeleteUsersIntent
import com.turnkey.http.model.V1DeleteWalletsIntent
import com.turnkey.http.model.V1DisablePrivateKeyIntent
import com.turnkey.http.model.V1EmailAuthIntent
import com.turnkey.http.model.V1EmailAuthIntentV2
import com.turnkey.http.model.V1ExportPrivateKeyIntent
import com.turnkey.http.model.V1ExportWalletAccountIntent
import com.turnkey.http.model.V1ExportWalletIntent
import com.turnkey.http.model.V1ImportPrivateKeyIntent
import com.turnkey.http.model.V1ImportWalletIntent
import com.turnkey.http.model.V1InitFiatOnRampIntent
import com.turnkey.http.model.V1InitImportPrivateKeyIntent
import com.turnkey.http.model.V1InitImportWalletIntent
import com.turnkey.http.model.V1InitOtpAuthIntent
import com.turnkey.http.model.V1InitOtpAuthIntentV2
import com.turnkey.http.model.V1InitOtpIntent
import com.turnkey.http.model.V1InitUserEmailRecoveryIntent
import com.turnkey.http.model.V1Oauth2AuthenticateIntent
import com.turnkey.http.model.V1OauthIntent
import com.turnkey.http.model.V1OauthLoginIntent
import com.turnkey.http.model.V1OtpAuthIntent
import com.turnkey.http.model.V1OtpLoginIntent
import com.turnkey.http.model.V1RecoverUserIntent
import com.turnkey.http.model.V1RejectActivityIntent
import com.turnkey.http.model.V1RemoveOrganizationFeatureIntent
import com.turnkey.http.model.V1SetOrganizationFeatureIntent
import com.turnkey.http.model.V1SignRawPayloadIntent
import com.turnkey.http.model.V1SignRawPayloadIntentV2
import com.turnkey.http.model.V1SignRawPayloadsIntent
import com.turnkey.http.model.V1SignTransactionIntent
import com.turnkey.http.model.V1SignTransactionIntentV2
import com.turnkey.http.model.V1StampLoginIntent
import com.turnkey.http.model.V1UpdateAllowedOriginsIntent
import com.turnkey.http.model.V1UpdateAuthProxyConfigIntent
import com.turnkey.http.model.V1UpdateOauth2CredentialIntent
import com.turnkey.http.model.V1UpdatePolicyIntent
import com.turnkey.http.model.V1UpdatePolicyIntentV2
import com.turnkey.http.model.V1UpdatePrivateKeyTagIntent
import com.turnkey.http.model.V1UpdateRootQuorumIntent
import com.turnkey.http.model.V1UpdateUserEmailIntent
import com.turnkey.http.model.V1UpdateUserIntent
import com.turnkey.http.model.V1UpdateUserNameIntent
import com.turnkey.http.model.V1UpdateUserPhoneNumberIntent
import com.turnkey.http.model.V1UpdateUserTagIntent
import com.turnkey.http.model.V1UpdateWalletIntent
import com.turnkey.http.model.V1VerifyOtpIntent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createOrganizationIntent 
 * @param createAuthenticatorsIntent 
 * @param createUsersIntent 
 * @param createPrivateKeysIntent 
 * @param signRawPayloadIntent 
 * @param createInvitationsIntent 
 * @param acceptInvitationIntent 
 * @param createPolicyIntent 
 * @param disablePrivateKeyIntent 
 * @param deleteUsersIntent 
 * @param deleteAuthenticatorsIntent 
 * @param deleteInvitationIntent 
 * @param deleteOrganizationIntent 
 * @param deletePolicyIntent 
 * @param createUserTagIntent 
 * @param deleteUserTagsIntent 
 * @param signTransactionIntent 
 * @param createApiKeysIntent 
 * @param deleteApiKeysIntent 
 * @param approveActivityIntent 
 * @param rejectActivityIntent 
 * @param createPrivateKeyTagIntent 
 * @param deletePrivateKeyTagsIntent 
 * @param createPolicyIntentV2 
 * @param setPaymentMethodIntent 
 * @param activateBillingTierIntent 
 * @param deletePaymentMethodIntent 
 * @param createPolicyIntentV3 
 * @param createApiOnlyUsersIntent 
 * @param updateRootQuorumIntent 
 * @param updateUserTagIntent 
 * @param updatePrivateKeyTagIntent 
 * @param createAuthenticatorsIntentV2 
 * @param acceptInvitationIntentV2 
 * @param createOrganizationIntentV2 
 * @param createUsersIntentV2 
 * @param createSubOrganizationIntent 
 * @param createSubOrganizationIntentV2 
 * @param updateAllowedOriginsIntent 
 * @param createPrivateKeysIntentV2 
 * @param updateUserIntent 
 * @param updatePolicyIntent 
 * @param setPaymentMethodIntentV2 
 * @param createSubOrganizationIntentV3 
 * @param createWalletIntent 
 * @param createWalletAccountsIntent 
 * @param initUserEmailRecoveryIntent 
 * @param recoverUserIntent 
 * @param setOrganizationFeatureIntent 
 * @param removeOrganizationFeatureIntent 
 * @param signRawPayloadIntentV2 
 * @param signTransactionIntentV2 
 * @param exportPrivateKeyIntent 
 * @param exportWalletIntent 
 * @param createSubOrganizationIntentV4 
 * @param emailAuthIntent 
 * @param exportWalletAccountIntent 
 * @param initImportWalletIntent 
 * @param importWalletIntent 
 * @param initImportPrivateKeyIntent 
 * @param importPrivateKeyIntent 
 * @param createPoliciesIntent 
 * @param signRawPayloadsIntent 
 * @param createReadOnlySessionIntent 
 * @param createOauthProvidersIntent 
 * @param deleteOauthProvidersIntent 
 * @param createSubOrganizationIntentV5 
 * @param oauthIntent 
 * @param createApiKeysIntentV2 
 * @param createReadWriteSessionIntent 
 * @param emailAuthIntentV2 
 * @param createSubOrganizationIntentV6 
 * @param deletePrivateKeysIntent 
 * @param deleteWalletsIntent 
 * @param createReadWriteSessionIntentV2 
 * @param deleteSubOrganizationIntent 
 * @param initOtpAuthIntent 
 * @param otpAuthIntent 
 * @param createSubOrganizationIntentV7 
 * @param updateWalletIntent 
 * @param updatePolicyIntentV2 
 * @param createUsersIntentV3 
 * @param initOtpAuthIntentV2 
 * @param initOtpIntent 
 * @param verifyOtpIntent 
 * @param otpLoginIntent 
 * @param stampLoginIntent 
 * @param oauthLoginIntent 
 * @param updateUserNameIntent 
 * @param updateUserEmailIntent 
 * @param updateUserPhoneNumberIntent 
 * @param initFiatOnRampIntent 
 * @param createSmartContractInterfaceIntent 
 * @param deleteSmartContractInterfaceIntent 
 * @param enableAuthProxyIntent 
 * @param disableAuthProxyIntent 
 * @param updateAuthProxyConfigIntent 
 * @param createOauth2CredentialIntent 
 * @param updateOauth2CredentialIntent 
 * @param deleteOauth2CredentialIntent 
 * @param oauth2AuthenticateIntent 
 */
@Serializable

data class V1Intent (

    @SerialName(value = "createOrganizationIntent")
    val createOrganizationIntent: V1CreateOrganizationIntent? = null,

    @SerialName(value = "createAuthenticatorsIntent")
    val createAuthenticatorsIntent: V1CreateAuthenticatorsIntent? = null,

    @SerialName(value = "createUsersIntent")
    val createUsersIntent: V1CreateUsersIntent? = null,

    @SerialName(value = "createPrivateKeysIntent")
    val createPrivateKeysIntent: V1CreatePrivateKeysIntent? = null,

    @SerialName(value = "signRawPayloadIntent")
    val signRawPayloadIntent: V1SignRawPayloadIntent? = null,

    @SerialName(value = "createInvitationsIntent")
    val createInvitationsIntent: V1CreateInvitationsIntent? = null,

    @SerialName(value = "acceptInvitationIntent")
    val acceptInvitationIntent: V1AcceptInvitationIntent? = null,

    @SerialName(value = "createPolicyIntent")
    val createPolicyIntent: V1CreatePolicyIntent? = null,

    @SerialName(value = "disablePrivateKeyIntent")
    val disablePrivateKeyIntent: V1DisablePrivateKeyIntent? = null,

    @SerialName(value = "deleteUsersIntent")
    val deleteUsersIntent: V1DeleteUsersIntent? = null,

    @SerialName(value = "deleteAuthenticatorsIntent")
    val deleteAuthenticatorsIntent: V1DeleteAuthenticatorsIntent? = null,

    @SerialName(value = "deleteInvitationIntent")
    val deleteInvitationIntent: V1DeleteInvitationIntent? = null,

    @SerialName(value = "deleteOrganizationIntent")
    val deleteOrganizationIntent: V1DeleteOrganizationIntent? = null,

    @SerialName(value = "deletePolicyIntent")
    val deletePolicyIntent: V1DeletePolicyIntent? = null,

    @SerialName(value = "createUserTagIntent")
    val createUserTagIntent: V1CreateUserTagIntent? = null,

    @SerialName(value = "deleteUserTagsIntent")
    val deleteUserTagsIntent: V1DeleteUserTagsIntent? = null,

    @SerialName(value = "signTransactionIntent")
    val signTransactionIntent: V1SignTransactionIntent? = null,

    @SerialName(value = "createApiKeysIntent")
    val createApiKeysIntent: V1CreateApiKeysIntent? = null,

    @SerialName(value = "deleteApiKeysIntent")
    val deleteApiKeysIntent: V1DeleteApiKeysIntent? = null,

    @SerialName(value = "approveActivityIntent")
    val approveActivityIntent: V1ApproveActivityIntent? = null,

    @SerialName(value = "rejectActivityIntent")
    val rejectActivityIntent: V1RejectActivityIntent? = null,

    @SerialName(value = "createPrivateKeyTagIntent")
    val createPrivateKeyTagIntent: V1CreatePrivateKeyTagIntent? = null,

    @SerialName(value = "deletePrivateKeyTagsIntent")
    val deletePrivateKeyTagsIntent: V1DeletePrivateKeyTagsIntent? = null,

    @SerialName(value = "createPolicyIntentV2")
    val createPolicyIntentV2: V1CreatePolicyIntentV2? = null,

    @SerialName(value = "setPaymentMethodIntent")
    val setPaymentMethodIntent: BillingSetPaymentMethodIntent? = null,

    @SerialName(value = "activateBillingTierIntent")
    val activateBillingTierIntent: BillingActivateBillingTierIntent? = null,

    @SerialName(value = "deletePaymentMethodIntent")
    val deletePaymentMethodIntent: BillingDeletePaymentMethodIntent? = null,

    @SerialName(value = "createPolicyIntentV3")
    val createPolicyIntentV3: V1CreatePolicyIntentV3? = null,

    @SerialName(value = "createApiOnlyUsersIntent")
    val createApiOnlyUsersIntent: V1CreateApiOnlyUsersIntent? = null,

    @SerialName(value = "updateRootQuorumIntent")
    val updateRootQuorumIntent: V1UpdateRootQuorumIntent? = null,

    @SerialName(value = "updateUserTagIntent")
    val updateUserTagIntent: V1UpdateUserTagIntent? = null,

    @SerialName(value = "updatePrivateKeyTagIntent")
    val updatePrivateKeyTagIntent: V1UpdatePrivateKeyTagIntent? = null,

    @SerialName(value = "createAuthenticatorsIntentV2")
    val createAuthenticatorsIntentV2: V1CreateAuthenticatorsIntentV2? = null,

    @SerialName(value = "acceptInvitationIntentV2")
    val acceptInvitationIntentV2: V1AcceptInvitationIntentV2? = null,

    @SerialName(value = "createOrganizationIntentV2")
    val createOrganizationIntentV2: V1CreateOrganizationIntentV2? = null,

    @SerialName(value = "createUsersIntentV2")
    val createUsersIntentV2: V1CreateUsersIntentV2? = null,

    @SerialName(value = "createSubOrganizationIntent")
    val createSubOrganizationIntent: V1CreateSubOrganizationIntent? = null,

    @SerialName(value = "createSubOrganizationIntentV2")
    val createSubOrganizationIntentV2: V1CreateSubOrganizationIntentV2? = null,

    @SerialName(value = "updateAllowedOriginsIntent")
    val updateAllowedOriginsIntent: V1UpdateAllowedOriginsIntent? = null,

    @SerialName(value = "createPrivateKeysIntentV2")
    val createPrivateKeysIntentV2: V1CreatePrivateKeysIntentV2? = null,

    @SerialName(value = "updateUserIntent")
    val updateUserIntent: V1UpdateUserIntent? = null,

    @SerialName(value = "updatePolicyIntent")
    val updatePolicyIntent: V1UpdatePolicyIntent? = null,

    @SerialName(value = "setPaymentMethodIntentV2")
    val setPaymentMethodIntentV2: BillingSetPaymentMethodIntentV2? = null,

    @SerialName(value = "createSubOrganizationIntentV3")
    val createSubOrganizationIntentV3: V1CreateSubOrganizationIntentV3? = null,

    @SerialName(value = "createWalletIntent")
    val createWalletIntent: V1CreateWalletIntent? = null,

    @SerialName(value = "createWalletAccountsIntent")
    val createWalletAccountsIntent: V1CreateWalletAccountsIntent? = null,

    @SerialName(value = "initUserEmailRecoveryIntent")
    val initUserEmailRecoveryIntent: V1InitUserEmailRecoveryIntent? = null,

    @SerialName(value = "recoverUserIntent")
    val recoverUserIntent: V1RecoverUserIntent? = null,

    @SerialName(value = "setOrganizationFeatureIntent")
    val setOrganizationFeatureIntent: V1SetOrganizationFeatureIntent? = null,

    @SerialName(value = "removeOrganizationFeatureIntent")
    val removeOrganizationFeatureIntent: V1RemoveOrganizationFeatureIntent? = null,

    @SerialName(value = "signRawPayloadIntentV2")
    val signRawPayloadIntentV2: V1SignRawPayloadIntentV2? = null,

    @SerialName(value = "signTransactionIntentV2")
    val signTransactionIntentV2: V1SignTransactionIntentV2? = null,

    @SerialName(value = "exportPrivateKeyIntent")
    val exportPrivateKeyIntent: V1ExportPrivateKeyIntent? = null,

    @SerialName(value = "exportWalletIntent")
    val exportWalletIntent: V1ExportWalletIntent? = null,

    @SerialName(value = "createSubOrganizationIntentV4")
    val createSubOrganizationIntentV4: V1CreateSubOrganizationIntentV4? = null,

    @SerialName(value = "emailAuthIntent")
    val emailAuthIntent: V1EmailAuthIntent? = null,

    @SerialName(value = "exportWalletAccountIntent")
    val exportWalletAccountIntent: V1ExportWalletAccountIntent? = null,

    @SerialName(value = "initImportWalletIntent")
    val initImportWalletIntent: V1InitImportWalletIntent? = null,

    @SerialName(value = "importWalletIntent")
    val importWalletIntent: V1ImportWalletIntent? = null,

    @SerialName(value = "initImportPrivateKeyIntent")
    val initImportPrivateKeyIntent: V1InitImportPrivateKeyIntent? = null,

    @SerialName(value = "importPrivateKeyIntent")
    val importPrivateKeyIntent: V1ImportPrivateKeyIntent? = null,

    @SerialName(value = "createPoliciesIntent")
    val createPoliciesIntent: V1CreatePoliciesIntent? = null,

    @SerialName(value = "signRawPayloadsIntent")
    val signRawPayloadsIntent: V1SignRawPayloadsIntent? = null,

    @Contextual @SerialName(value = "createReadOnlySessionIntent")
    val createReadOnlySessionIntent: kotlin.Any? = null,

    @SerialName(value = "createOauthProvidersIntent")
    val createOauthProvidersIntent: V1CreateOauthProvidersIntent? = null,

    @SerialName(value = "deleteOauthProvidersIntent")
    val deleteOauthProvidersIntent: V1DeleteOauthProvidersIntent? = null,

    @SerialName(value = "createSubOrganizationIntentV5")
    val createSubOrganizationIntentV5: V1CreateSubOrganizationIntentV5? = null,

    @SerialName(value = "oauthIntent")
    val oauthIntent: V1OauthIntent? = null,

    @SerialName(value = "createApiKeysIntentV2")
    val createApiKeysIntentV2: V1CreateApiKeysIntentV2? = null,

    @SerialName(value = "createReadWriteSessionIntent")
    val createReadWriteSessionIntent: V1CreateReadWriteSessionIntent? = null,

    @SerialName(value = "emailAuthIntentV2")
    val emailAuthIntentV2: V1EmailAuthIntentV2? = null,

    @SerialName(value = "createSubOrganizationIntentV6")
    val createSubOrganizationIntentV6: V1CreateSubOrganizationIntentV6? = null,

    @SerialName(value = "deletePrivateKeysIntent")
    val deletePrivateKeysIntent: V1DeletePrivateKeysIntent? = null,

    @SerialName(value = "deleteWalletsIntent")
    val deleteWalletsIntent: V1DeleteWalletsIntent? = null,

    @SerialName(value = "createReadWriteSessionIntentV2")
    val createReadWriteSessionIntentV2: V1CreateReadWriteSessionIntentV2? = null,

    @SerialName(value = "deleteSubOrganizationIntent")
    val deleteSubOrganizationIntent: V1DeleteSubOrganizationIntent? = null,

    @SerialName(value = "initOtpAuthIntent")
    val initOtpAuthIntent: V1InitOtpAuthIntent? = null,

    @SerialName(value = "otpAuthIntent")
    val otpAuthIntent: V1OtpAuthIntent? = null,

    @SerialName(value = "createSubOrganizationIntentV7")
    val createSubOrganizationIntentV7: V1CreateSubOrganizationIntentV7? = null,

    @SerialName(value = "updateWalletIntent")
    val updateWalletIntent: V1UpdateWalletIntent? = null,

    @SerialName(value = "updatePolicyIntentV2")
    val updatePolicyIntentV2: V1UpdatePolicyIntentV2? = null,

    @SerialName(value = "createUsersIntentV3")
    val createUsersIntentV3: V1CreateUsersIntentV3? = null,

    @SerialName(value = "initOtpAuthIntentV2")
    val initOtpAuthIntentV2: V1InitOtpAuthIntentV2? = null,

    @SerialName(value = "initOtpIntent")
    val initOtpIntent: V1InitOtpIntent? = null,

    @SerialName(value = "verifyOtpIntent")
    val verifyOtpIntent: V1VerifyOtpIntent? = null,

    @SerialName(value = "otpLoginIntent")
    val otpLoginIntent: V1OtpLoginIntent? = null,

    @SerialName(value = "stampLoginIntent")
    val stampLoginIntent: V1StampLoginIntent? = null,

    @SerialName(value = "oauthLoginIntent")
    val oauthLoginIntent: V1OauthLoginIntent? = null,

    @SerialName(value = "updateUserNameIntent")
    val updateUserNameIntent: V1UpdateUserNameIntent? = null,

    @SerialName(value = "updateUserEmailIntent")
    val updateUserEmailIntent: V1UpdateUserEmailIntent? = null,

    @SerialName(value = "updateUserPhoneNumberIntent")
    val updateUserPhoneNumberIntent: V1UpdateUserPhoneNumberIntent? = null,

    @SerialName(value = "initFiatOnRampIntent")
    val initFiatOnRampIntent: V1InitFiatOnRampIntent? = null,

    @SerialName(value = "createSmartContractInterfaceIntent")
    val createSmartContractInterfaceIntent: V1CreateSmartContractInterfaceIntent? = null,

    @SerialName(value = "deleteSmartContractInterfaceIntent")
    val deleteSmartContractInterfaceIntent: V1DeleteSmartContractInterfaceIntent? = null,

    @Contextual @SerialName(value = "enableAuthProxyIntent")
    val enableAuthProxyIntent: kotlin.Any? = null,

    @Contextual @SerialName(value = "disableAuthProxyIntent")
    val disableAuthProxyIntent: kotlin.Any? = null,

    @SerialName(value = "updateAuthProxyConfigIntent")
    val updateAuthProxyConfigIntent: V1UpdateAuthProxyConfigIntent? = null,

    @SerialName(value = "createOauth2CredentialIntent")
    val createOauth2CredentialIntent: V1CreateOauth2CredentialIntent? = null,

    @SerialName(value = "updateOauth2CredentialIntent")
    val updateOauth2CredentialIntent: V1UpdateOauth2CredentialIntent? = null,

    @SerialName(value = "deleteOauth2CredentialIntent")
    val deleteOauth2CredentialIntent: V1DeleteOauth2CredentialIntent? = null,

    @SerialName(value = "oauth2AuthenticateIntent")
    val oauth2AuthenticateIntent: V1Oauth2AuthenticateIntent? = null

) {


}

