/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param importBundle Import bundle containing a public key and signature to use for importing client data.
 */
@Serializable

data class V1InitImportWalletResult (

    /* Import bundle containing a public key and signature to use for importing client data. */
    @SerialName(value = "importBundle")
    val importBundle: kotlin.String

) {


}

