/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param otpId Unique identifier for an OTP authentication
 */
@Serializable

data class V1InitOtpResult (

    /* Unique identifier for an OTP authentication */
    @SerialName(value = "otpId")
    val otpId: kotlin.String

) {


}

