/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1EmailCustomizationParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email Email of the user starting recovery
 * @param targetPublicKey Client-side public key generated by the user, to which the recovery bundle will be encrypted.
 * @param expirationSeconds Expiration window (in seconds) indicating how long the recovery credential is valid for. If not provided, a default of 15 minutes will be used.
 * @param emailCustomization 
 */
@Serializable

data class V1InitUserEmailRecoveryIntent (

    /* Email of the user starting recovery */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* Client-side public key generated by the user, to which the recovery bundle will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String,

    /* Expiration window (in seconds) indicating how long the recovery credential is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    @SerialName(value = "emailCustomization")
    val emailCustomization: V1EmailCustomizationParams? = null

) {


}

