/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1FiatOnRampBlockchainNetwork
import com.turnkey.http.model.V1FiatOnRampCryptoCurrency
import com.turnkey.http.model.V1FiatOnRampCurrency
import com.turnkey.http.model.V1FiatOnRampPaymentMethod
import com.turnkey.http.model.V1FiatOnRampProvider

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param onrampProvider 
 * @param walletAddress Destination wallet address for the buy transaction.
 * @param network 
 * @param cryptoCurrencyCode 
 * @param fiatCurrencyCode 
 * @param fiatCurrencyAmount Specifies a preset fiat amount for the transaction, e.g., '100'. Must be greater than '20'. If not provided, the user will be prompted to enter an amount.
 * @param paymentMethod 
 * @param countryCode ISO 3166-1 two-digit country code for Coinbase representing the purchasing user’s country of residence, e.g., US, GB.
 * @param countrySubdivisionCode ISO 3166-2 two-digit country subdivision code for Coinbase representing the purchasing user’s subdivision of residence within their country, e.g. NY. Required if country_code=US.
 * @param sandboxMode Optional flag to indicate whether to use the sandbox mode to simulate transactions for the on-ramp provider. Default is false.
 * @param urlForSignature Optional MoonPay Widget URL to sign when using MoonPay client SDKs with URL Signing enabled.
 */
@Serializable

data class V1InitFiatOnRampIntent (

    @Contextual @SerialName(value = "onrampProvider")
    val onrampProvider: V1FiatOnRampProvider,

    /* Destination wallet address for the buy transaction. */
    @SerialName(value = "walletAddress")
    val walletAddress: kotlin.String,

    @Contextual @SerialName(value = "network")
    val network: V1FiatOnRampBlockchainNetwork,

    @Contextual @SerialName(value = "cryptoCurrencyCode")
    val cryptoCurrencyCode: V1FiatOnRampCryptoCurrency,

    @Contextual @SerialName(value = "fiatCurrencyCode")
    val fiatCurrencyCode: V1FiatOnRampCurrency? = null,

    /* Specifies a preset fiat amount for the transaction, e.g., '100'. Must be greater than '20'. If not provided, the user will be prompted to enter an amount. */
    @SerialName(value = "fiatCurrencyAmount")
    val fiatCurrencyAmount: kotlin.String? = null,

    @Contextual @SerialName(value = "paymentMethod")
    val paymentMethod: V1FiatOnRampPaymentMethod? = null,

    /* ISO 3166-1 two-digit country code for Coinbase representing the purchasing user’s country of residence, e.g., US, GB. */
    @SerialName(value = "countryCode")
    val countryCode: kotlin.String? = null,

    /* ISO 3166-2 two-digit country subdivision code for Coinbase representing the purchasing user’s subdivision of residence within their country, e.g. NY. Required if country_code=US. */
    @SerialName(value = "countrySubdivisionCode")
    val countrySubdivisionCode: kotlin.String? = null,

    /* Optional flag to indicate whether to use the sandbox mode to simulate transactions for the on-ramp provider. Default is false. */
    @SerialName(value = "sandboxMode")
    val sandboxMode: kotlin.Boolean? = null,

    /* Optional MoonPay Widget URL to sign when using MoonPay client SDKs with URL Signing enabled. */
    @SerialName(value = "urlForSignature")
    val urlForSignature: kotlin.String? = null

) {


}

