/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param onRampUrl Unique URL for a given fiat on-ramp flow.
 * @param onRampTransactionId Unique identifier used to retrieve transaction statuses for a given fiat on-ramp flow.
 * @param onRampUrlSignature Optional signature of the MoonPay Widget URL. The signature is generated if the Init Fiat On Ramp intent includes the urlForSignature field. The signature can be used to initialize the MoonPay SDKs when URL signing is enabled for your project.
 */
@Serializable

data class V1InitFiatOnRampResult (

    /* Unique URL for a given fiat on-ramp flow. */
    @SerialName(value = "onRampUrl")
    val onRampUrl: kotlin.String,

    /* Unique identifier used to retrieve transaction statuses for a given fiat on-ramp flow. */
    @SerialName(value = "onRampTransactionId")
    val onRampTransactionId: kotlin.String,

    /* Optional signature of the MoonPay Widget URL. The signature is generated if the Init Fiat On Ramp intent includes the urlForSignature field. The signature can be used to initialize the MoonPay SDKs when URL signing is enabled for your project. */
    @SerialName(value = "onRampUrlSignature")
    val onRampUrlSignature: kotlin.String? = null

) {


}

