/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Datav1Tag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyTags A list of private key tags.
 */
@Serializable

data class V1ListPrivateKeyTagsResponse (

    /* A list of private key tags. */
    @SerialName(value = "privateKeyTags")
    val privateKeyTags: kotlin.collections.List<Datav1Tag>

) {


}

