/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oauth2CredentialId The OAuth 2.0 credential id whose client_id and client_secret will be used in the OAuth 2.0 flow
 * @param authCode The auth_code provided by the OAuth 2.0 provider to the end user to be exchanged for a Bearer token in the OAuth 2.0 flow
 * @param redirectUri The URI the user is redirected to after they have authenticated with the OAuth 2.0 provider
 * @param codeVerifier The code verifier used by OAuth 2.0 PKCE providers
 * @param nonce An optional nonce used by the client to prevent replay/substitution of an ID token
 */
@Serializable

data class V1Oauth2AuthenticateIntent (

    /* The OAuth 2.0 credential id whose client_id and client_secret will be used in the OAuth 2.0 flow */
    @SerialName(value = "oauth2CredentialId")
    val oauth2CredentialId: kotlin.String,

    /* The auth_code provided by the OAuth 2.0 provider to the end user to be exchanged for a Bearer token in the OAuth 2.0 flow */
    @SerialName(value = "authCode")
    val authCode: kotlin.String,

    /* The URI the user is redirected to after they have authenticated with the OAuth 2.0 provider */
    @SerialName(value = "redirectUri")
    val redirectUri: kotlin.String,

    /* The code verifier used by OAuth 2.0 PKCE providers */
    @SerialName(value = "codeVerifier")
    val codeVerifier: kotlin.String,

    /* An optional nonce used by the client to prevent replay/substitution of an ID token */
    @SerialName(value = "nonce")
    val nonce: kotlin.String? = null

) {


}

