/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param providerId Unique identifier for an OAuth Provider
 * @param providerName Human-readable name to identify a Provider.
 * @param issuer The issuer of the token, typically a URL indicating the authentication server, e.g https://accounts.google.com
 * @param audience Expected audience ('aud' attribute of the signed token) which represents the app ID
 * @param subject Expected subject ('sub' attribute of the signed token) which represents the user ID
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class V1OauthProvider (

    /* Unique identifier for an OAuth Provider */
    @SerialName(value = "providerId")
    val providerId: kotlin.String,

    /* Human-readable name to identify a Provider. */
    @SerialName(value = "providerName")
    val providerName: kotlin.String,

    /* The issuer of the token, typically a URL indicating the authentication server, e.g https://accounts.google.com */
    @SerialName(value = "issuer")
    val issuer: kotlin.String,

    /* Expected audience ('aud' attribute of the signed token) which represents the app ID */
    @SerialName(value = "audience")
    val audience: kotlin.String,

    /* Expected subject ('sub' attribute of the signed token) which represents the user ID */
    @SerialName(value = "subject")
    val subject: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp

) {


}

