/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oidcToken Base64 encoded OIDC token issued by Turnkey to be used with the LoginWithOAuth activity
 */
@Serializable

data class V1Oauth2AuthenticateResult (

    /* Base64 encoded OIDC token issued by Turnkey to be used with the LoginWithOAuth activity */
    @SerialName(value = "oidcToken")
    val oidcToken: kotlin.String

) {


}

