/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: OAUTH2_PROVIDER_X,OAUTH2_PROVIDER_DISCORD
 */
@Serializable
enum class V1Oauth2Provider(val value: kotlin.String) {

    @SerialName(value = "OAUTH2_PROVIDER_X")
    OAUTH2_PROVIDER_X("OAUTH2_PROVIDER_X"),

    @SerialName(value = "OAUTH2_PROVIDER_DISCORD")
    OAUTH2_PROVIDER_DISCORD("OAUTH2_PROVIDER_DISCORD");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1Oauth2Provider) "$data" else null

        /**
         * Returns a valid [V1Oauth2Provider] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1Oauth2Provider? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


