/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oidcToken Base64 encoded OIDC token
 * @param targetPublicKey Client-side public key generated by the user, to which the oauth bundle (credentials) will be encrypted.
 * @param apiKeyName Optional human-readable name for an API Key. If none provided, default to Oauth - <Timestamp>
 * @param expirationSeconds Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used.
 * @param invalidateExisting Invalidate all other previously generated Oauth API keys
 */
@Serializable

data class V1OauthIntent (

    /* Base64 encoded OIDC token */
    @SerialName(value = "oidcToken")
    val oidcToken: kotlin.String,

    /* Client-side public key generated by the user, to which the oauth bundle (credentials) will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String,

    /* Optional human-readable name for an API Key. If none provided, default to Oauth - <Timestamp> */
    @SerialName(value = "apiKeyName")
    val apiKeyName: kotlin.String? = null,

    /* Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    /* Invalidate all other previously generated Oauth API keys */
    @SerialName(value = "invalidateExisting")
    val invalidateExisting: kotlin.Boolean? = null

) {


}

