/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId Unique identifier for the authenticating User.
 * @param apiKeyId Unique identifier for the created API key.
 * @param credentialBundle HPKE encrypted credential bundle
 */
@Serializable

data class V1OauthResult (

    /* Unique identifier for the authenticating User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Unique identifier for the created API key. */
    @SerialName(value = "apiKeyId")
    val apiKeyId: kotlin.String,

    /* HPKE encrypted credential bundle */
    @SerialName(value = "credentialBundle")
    val credentialBundle: kotlin.String

) {


}

