/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: OPERATOR_EQUAL,OPERATOR_MORE_THAN,OPERATOR_MORE_THAN_OR_EQUAL,OPERATOR_LESS_THAN,OPERATOR_LESS_THAN_OR_EQUAL,OPERATOR_CONTAINS,OPERATOR_NOT_EQUAL,OPERATOR_IN,OPERATOR_NOT_IN,OPERATOR_CONTAINS_ONE,OPERATOR_CONTAINS_ALL
 */
@Serializable
enum class V1Operator(val value: kotlin.String) {

    @SerialName(value = "OPERATOR_EQUAL")
    OPERATOR_EQUAL("OPERATOR_EQUAL"),

    @SerialName(value = "OPERATOR_MORE_THAN")
    OPERATOR_MORE_THAN("OPERATOR_MORE_THAN"),

    @SerialName(value = "OPERATOR_MORE_THAN_OR_EQUAL")
    OPERATOR_MORE_THAN_OR_EQUAL("OPERATOR_MORE_THAN_OR_EQUAL"),

    @SerialName(value = "OPERATOR_LESS_THAN")
    OPERATOR_LESS_THAN("OPERATOR_LESS_THAN"),

    @SerialName(value = "OPERATOR_LESS_THAN_OR_EQUAL")
    OPERATOR_LESS_THAN_OR_EQUAL("OPERATOR_LESS_THAN_OR_EQUAL"),

    @SerialName(value = "OPERATOR_CONTAINS")
    OPERATOR_CONTAINS("OPERATOR_CONTAINS"),

    @SerialName(value = "OPERATOR_NOT_EQUAL")
    OPERATOR_NOT_EQUAL("OPERATOR_NOT_EQUAL"),

    @SerialName(value = "OPERATOR_IN")
    OPERATOR_IN("OPERATOR_IN"),

    @SerialName(value = "OPERATOR_NOT_IN")
    OPERATOR_NOT_IN("OPERATOR_NOT_IN"),

    @SerialName(value = "OPERATOR_CONTAINS_ONE")
    OPERATOR_CONTAINS_ONE("OPERATOR_CONTAINS_ONE"),

    @SerialName(value = "OPERATOR_CONTAINS_ALL")
    OPERATOR_CONTAINS_ALL("OPERATOR_CONTAINS_ALL");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1Operator) "$data" else null

        /**
         * Returns a valid [V1Operator] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1Operator? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


