/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param otpId ID representing the result of an init OTP activity.
 * @param otpCode OTP sent out to a user's contact (email or SMS)
 * @param targetPublicKey Client-side public key generated by the user, to which the OTP bundle (credentials) will be encrypted.
 * @param apiKeyName Optional human-readable name for an API Key. If none provided, default to OTP Auth - <Timestamp>
 * @param expirationSeconds Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used.
 * @param invalidateExisting Invalidate all other previously generated OTP Auth API keys
 */
@Serializable

data class V1OtpAuthIntent (

    /* ID representing the result of an init OTP activity. */
    @SerialName(value = "otpId")
    val otpId: kotlin.String,

    /* OTP sent out to a user's contact (email or SMS) */
    @SerialName(value = "otpCode")
    val otpCode: kotlin.String,

    /* Client-side public key generated by the user, to which the OTP bundle (credentials) will be encrypted. */
    @SerialName(value = "targetPublicKey")
    val targetPublicKey: kotlin.String,

    /* Optional human-readable name for an API Key. If none provided, default to OTP Auth - <Timestamp> */
    @SerialName(value = "apiKeyName")
    val apiKeyName: kotlin.String? = null,

    /* Expiration window (in seconds) indicating how long the API key is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    /* Invalidate all other previously generated OTP Auth API keys */
    @SerialName(value = "invalidateExisting")
    val invalidateExisting: kotlin.Boolean? = null

) {


}

