/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param verificationToken Signed JWT containing a unique id, expiry, verification type, contact
 * @param publicKey Client-side public key generated by the user, which will be conditionally added to org data based on the validity of the verification token
 * @param expirationSeconds Expiration window (in seconds) indicating how long the Session is valid for. If not provided, a default of 15 minutes will be used.
 * @param invalidateExisting Invalidate all other previously generated Login API keys
 * @param clientSignature Optional signature associated with the public key passed into the verification step. This must be a hex-encoded ECDSA signature over the verification token. Only required if a public key was provided during the verification step.
 */
@Serializable

data class V1OtpLoginIntent (

    /* Signed JWT containing a unique id, expiry, verification type, contact */
    @SerialName(value = "verificationToken")
    val verificationToken: kotlin.String,

    /* Client-side public key generated by the user, which will be conditionally added to org data based on the validity of the verification token */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* Expiration window (in seconds) indicating how long the Session is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    /* Invalidate all other previously generated Login API keys */
    @SerialName(value = "invalidateExisting")
    val invalidateExisting: kotlin.Boolean? = null,

    /* Optional signature associated with the public key passed into the verification step. This must be a hex-encoded ECDSA signature over the verification token. Only required if a public key was provided during the verification step. */
    @SerialName(value = "clientSignature")
    val clientSignature: kotlin.String? = null

) {


}

