/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: OUTCOME_ALLOW,OUTCOME_DENY_EXPLICIT,OUTCOME_DENY_IMPLICIT,OUTCOME_REQUIRES_CONSENSUS,OUTCOME_REJECTED,OUTCOME_ERROR
 */
@Serializable
enum class V1Outcome(val value: kotlin.String) {

    @SerialName(value = "OUTCOME_ALLOW")
    OUTCOME_ALLOW("OUTCOME_ALLOW"),

    @SerialName(value = "OUTCOME_DENY_EXPLICIT")
    OUTCOME_DENY_EXPLICIT("OUTCOME_DENY_EXPLICIT"),

    @SerialName(value = "OUTCOME_DENY_IMPLICIT")
    OUTCOME_DENY_IMPLICIT("OUTCOME_DENY_IMPLICIT"),

    @SerialName(value = "OUTCOME_REQUIRES_CONSENSUS")
    OUTCOME_REQUIRES_CONSENSUS("OUTCOME_REQUIRES_CONSENSUS"),

    @SerialName(value = "OUTCOME_REJECTED")
    OUTCOME_REJECTED("OUTCOME_REJECTED"),

    @SerialName(value = "OUTCOME_ERROR")
    OUTCOME_ERROR("OUTCOME_ERROR");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V1Outcome) "$data" else null

        /**
         * Returns a valid [V1Outcome] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V1Outcome? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


