/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param limit A limit of the number of object to be returned, between 1 and 100. Defaults to 10.
 * @param before A pagination cursor. This is an object ID that enables you to fetch all objects before this ID.
 * @param after A pagination cursor. This is an object ID that enables you to fetch all objects after this ID.
 */
@Serializable

data class V1Pagination (

    /* A limit of the number of object to be returned, between 1 and 100. Defaults to 10. */
    @SerialName(value = "limit")
    val limit: kotlin.String? = null,

    /* A pagination cursor. This is an object ID that enables you to fetch all objects before this ID. */
    @SerialName(value = "before")
    val before: kotlin.String? = null,

    /* A pagination cursor. This is an object ID that enables you to fetch all objects after this ID. */
    @SerialName(value = "after")
    val after: kotlin.String? = null

) {


}

