/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.V1Effect

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param policyId Unique identifier for a given Policy.
 * @param policyName Human-readable name for a Policy.
 * @param effect 
 * @param createdAt 
 * @param updatedAt 
 * @param notes Human-readable notes added by a User to describe a particular policy.
 * @param consensus A consensus expression that evalutes to true or false.
 * @param condition A condition expression that evalutes to true or false.
 */
@Serializable

data class V1Policy (

    /* Unique identifier for a given Policy. */
    @SerialName(value = "policyId")
    val policyId: kotlin.String,

    /* Human-readable name for a Policy. */
    @SerialName(value = "policyName")
    val policyName: kotlin.String,

    @Contextual @SerialName(value = "effect")
    val effect: V1Effect,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp,

    /* Human-readable notes added by a User to describe a particular policy. */
    @SerialName(value = "notes")
    val notes: kotlin.String,

    /* A consensus expression that evalutes to true or false. */
    @SerialName(value = "consensus")
    val consensus: kotlin.String,

    /* A condition expression that evalutes to true or false. */
    @SerialName(value = "condition")
    val condition: kotlin.String

) {


}

