/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Address
import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.V1Curve

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyId Unique identifier for a given Private Key.
 * @param publicKey The public component of a cryptographic key pair used to sign messages and transactions.
 * @param privateKeyName Human-readable name for a Private Key.
 * @param curve 
 * @param addresses Derived cryptocurrency addresses for a given Private Key.
 * @param privateKeyTags A list of Private Key Tag IDs.
 * @param createdAt 
 * @param updatedAt 
 * @param exported True when a given Private Key is exported, false otherwise.
 * @param imported True when a given Private Key is imported, false otherwise.
 */
@Serializable

data class V1PrivateKey (

    /* Unique identifier for a given Private Key. */
    @SerialName(value = "privateKeyId")
    val privateKeyId: kotlin.String,

    /* The public component of a cryptographic key pair used to sign messages and transactions. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* Human-readable name for a Private Key. */
    @SerialName(value = "privateKeyName")
    val privateKeyName: kotlin.String,

    @Contextual @SerialName(value = "curve")
    val curve: V1Curve,

    /* Derived cryptocurrency addresses for a given Private Key. */
    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<Externaldatav1Address>,

    /* A list of Private Key Tag IDs. */
    @SerialName(value = "privateKeyTags")
    val privateKeyTags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp,

    /* True when a given Private Key is exported, false otherwise. */
    @SerialName(value = "exported")
    val exported: kotlin.Boolean,

    /* True when a given Private Key is imported, false otherwise. */
    @SerialName(value = "imported")
    val imported: kotlin.Boolean

) {


}

