/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AddressFormat
import com.turnkey.http.model.V1Curve

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyName Human-readable name for a Private Key.
 * @param curve 
 * @param privateKeyTags A list of Private Key Tag IDs. This field, if not needed, should be an empty array in your request body.
 * @param addressFormats Cryptocurrency-specific formats for a derived address (e.g., Ethereum).
 */
@Serializable

data class V1PrivateKeyParams (

    /* Human-readable name for a Private Key. */
    @SerialName(value = "privateKeyName")
    val privateKeyName: kotlin.String,

    @Contextual @SerialName(value = "curve")
    val curve: V1Curve,

    /* A list of Private Key Tag IDs. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "privateKeyTags")
    val privateKeyTags: kotlin.collections.List<kotlin.String>,

    /* Cryptocurrency-specific formats for a derived address (e.g., Ethereum). */
    @SerialName(value = "addressFormats")
    val addressFormats: kotlin.collections.List<@Contextual V1AddressFormat>

) {


}

