/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1AuthenticatorAttestationResponse
import com.turnkey.http.model.V1SimpleClientExtensionResults

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param type 
 * @param rawId 
 * @param response 
 * @param clientExtensionResults 
 * @param authenticatorAttachment 
 */
@Serializable

data class V1PublicKeyCredentialWithAttestation (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "type")
    val type: V1PublicKeyCredentialWithAttestation.Type,

    @SerialName(value = "rawId")
    val rawId: kotlin.String,

    @SerialName(value = "response")
    val response: V1AuthenticatorAttestationResponse,

    @SerialName(value = "clientExtensionResults")
    val clientExtensionResults: V1SimpleClientExtensionResults,

    @SerialName(value = "authenticatorAttachment")
    val authenticatorAttachment: V1PublicKeyCredentialWithAttestation.AuthenticatorAttachment? = null

) {

    /**
     * 
     *
     * Values: publicMinusKey
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "public-key") publicMinusKey("public-key");
    }
    /**
     * 
     *
     * Values: crossMinusPlatform,platform
     */
    @Serializable
    enum class AuthenticatorAttachment(val value: kotlin.String) {
        @SerialName(value = "cross-platform") crossMinusPlatform("cross-platform"),
        @SerialName(value = "platform") platform("platform");
    }

}

