/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1RejectActivityIntent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param timestampMs Timestamp (in milliseconds) of the request, used to verify liveness of user requests.
 * @param organizationId Unique identifier for a given Organization.
 * @param parameters 
 */
@Serializable

data class V1RejectActivityRequest (

    @SerialName(value = "type")
    val type: V1RejectActivityRequest.Type,

    /* Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    @SerialName(value = "timestampMs")
    val timestampMs: kotlin.String,

    /* Unique identifier for a given Organization. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    @SerialName(value = "parameters")
    val parameters: V1RejectActivityIntent

) {

    /**
     * 
     *
     * Values: ACTIVITY_TYPE_REJECT_ACTIVITY
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ACTIVITY_TYPE_REJECT_ACTIVITY") ACTIVITY_TYPE_REJECT_ACTIVITY("ACTIVITY_TYPE_REJECT_ACTIVITY");
    }

}

