/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authenticatorId ID of the authenticator created.
 */
@Serializable

data class V1RecoverUserResult (

    /* ID of the authenticator created. */
    @SerialName(value = "authenticatorId")
    val authenticatorId: kotlin.collections.List<kotlin.String>

) {


}

