/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.BillingActivateBillingTierResult
import com.turnkey.http.model.BillingDeletePaymentMethodResult
import com.turnkey.http.model.BillingSetPaymentMethodResult
import com.turnkey.http.model.V1AcceptInvitationResult
import com.turnkey.http.model.V1CreateApiKeysResult
import com.turnkey.http.model.V1CreateApiOnlyUsersResult
import com.turnkey.http.model.V1CreateAuthenticatorsResult
import com.turnkey.http.model.V1CreateInvitationsResult
import com.turnkey.http.model.V1CreateOauth2CredentialResult
import com.turnkey.http.model.V1CreateOauthProvidersResult
import com.turnkey.http.model.V1CreateOrganizationResult
import com.turnkey.http.model.V1CreatePoliciesResult
import com.turnkey.http.model.V1CreatePolicyResult
import com.turnkey.http.model.V1CreatePrivateKeyTagResult
import com.turnkey.http.model.V1CreatePrivateKeysResult
import com.turnkey.http.model.V1CreatePrivateKeysResultV2
import com.turnkey.http.model.V1CreateReadOnlySessionResult
import com.turnkey.http.model.V1CreateReadWriteSessionResult
import com.turnkey.http.model.V1CreateReadWriteSessionResultV2
import com.turnkey.http.model.V1CreateSmartContractInterfaceResult
import com.turnkey.http.model.V1CreateSubOrganizationResult
import com.turnkey.http.model.V1CreateSubOrganizationResultV3
import com.turnkey.http.model.V1CreateSubOrganizationResultV4
import com.turnkey.http.model.V1CreateSubOrganizationResultV5
import com.turnkey.http.model.V1CreateSubOrganizationResultV6
import com.turnkey.http.model.V1CreateSubOrganizationResultV7
import com.turnkey.http.model.V1CreateUserTagResult
import com.turnkey.http.model.V1CreateUsersResult
import com.turnkey.http.model.V1CreateWalletAccountsResult
import com.turnkey.http.model.V1CreateWalletResult
import com.turnkey.http.model.V1DeleteApiKeysResult
import com.turnkey.http.model.V1DeleteAuthenticatorsResult
import com.turnkey.http.model.V1DeleteInvitationResult
import com.turnkey.http.model.V1DeleteOauth2CredentialResult
import com.turnkey.http.model.V1DeleteOauthProvidersResult
import com.turnkey.http.model.V1DeleteOrganizationResult
import com.turnkey.http.model.V1DeletePolicyResult
import com.turnkey.http.model.V1DeletePrivateKeyTagsResult
import com.turnkey.http.model.V1DeletePrivateKeysResult
import com.turnkey.http.model.V1DeleteSmartContractInterfaceResult
import com.turnkey.http.model.V1DeleteSubOrganizationResult
import com.turnkey.http.model.V1DeleteUserTagsResult
import com.turnkey.http.model.V1DeleteUsersResult
import com.turnkey.http.model.V1DeleteWalletsResult
import com.turnkey.http.model.V1DisablePrivateKeyResult
import com.turnkey.http.model.V1EmailAuthResult
import com.turnkey.http.model.V1EnableAuthProxyResult
import com.turnkey.http.model.V1ExportPrivateKeyResult
import com.turnkey.http.model.V1ExportWalletAccountResult
import com.turnkey.http.model.V1ExportWalletResult
import com.turnkey.http.model.V1ImportPrivateKeyResult
import com.turnkey.http.model.V1ImportWalletResult
import com.turnkey.http.model.V1InitFiatOnRampResult
import com.turnkey.http.model.V1InitImportPrivateKeyResult
import com.turnkey.http.model.V1InitImportWalletResult
import com.turnkey.http.model.V1InitOtpAuthResult
import com.turnkey.http.model.V1InitOtpAuthResultV2
import com.turnkey.http.model.V1InitOtpResult
import com.turnkey.http.model.V1InitUserEmailRecoveryResult
import com.turnkey.http.model.V1Oauth2AuthenticateResult
import com.turnkey.http.model.V1OauthLoginResult
import com.turnkey.http.model.V1OauthResult
import com.turnkey.http.model.V1OtpAuthResult
import com.turnkey.http.model.V1OtpLoginResult
import com.turnkey.http.model.V1RecoverUserResult
import com.turnkey.http.model.V1RemoveOrganizationFeatureResult
import com.turnkey.http.model.V1SetOrganizationFeatureResult
import com.turnkey.http.model.V1SignRawPayloadResult
import com.turnkey.http.model.V1SignRawPayloadsResult
import com.turnkey.http.model.V1SignTransactionResult
import com.turnkey.http.model.V1StampLoginResult
import com.turnkey.http.model.V1UpdateAuthProxyConfigResult
import com.turnkey.http.model.V1UpdateOauth2CredentialResult
import com.turnkey.http.model.V1UpdatePolicyResult
import com.turnkey.http.model.V1UpdatePolicyResultV2
import com.turnkey.http.model.V1UpdatePrivateKeyTagResult
import com.turnkey.http.model.V1UpdateUserEmailResult
import com.turnkey.http.model.V1UpdateUserNameResult
import com.turnkey.http.model.V1UpdateUserPhoneNumberResult
import com.turnkey.http.model.V1UpdateUserResult
import com.turnkey.http.model.V1UpdateUserTagResult
import com.turnkey.http.model.V1UpdateWalletResult
import com.turnkey.http.model.V1VerifyOtpResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createOrganizationResult 
 * @param createAuthenticatorsResult 
 * @param createUsersResult 
 * @param createPrivateKeysResult 
 * @param createInvitationsResult 
 * @param acceptInvitationResult 
 * @param signRawPayloadResult 
 * @param createPolicyResult 
 * @param disablePrivateKeyResult 
 * @param deleteUsersResult 
 * @param deleteAuthenticatorsResult 
 * @param deleteInvitationResult 
 * @param deleteOrganizationResult 
 * @param deletePolicyResult 
 * @param createUserTagResult 
 * @param deleteUserTagsResult 
 * @param signTransactionResult 
 * @param deleteApiKeysResult 
 * @param createApiKeysResult 
 * @param createPrivateKeyTagResult 
 * @param deletePrivateKeyTagsResult 
 * @param setPaymentMethodResult 
 * @param activateBillingTierResult 
 * @param deletePaymentMethodResult 
 * @param createApiOnlyUsersResult 
 * @param updateRootQuorumResult 
 * @param updateUserTagResult 
 * @param updatePrivateKeyTagResult 
 * @param createSubOrganizationResult 
 * @param updateAllowedOriginsResult 
 * @param createPrivateKeysResultV2 
 * @param updateUserResult 
 * @param updatePolicyResult 
 * @param createSubOrganizationResultV3 
 * @param createWalletResult 
 * @param createWalletAccountsResult 
 * @param initUserEmailRecoveryResult 
 * @param recoverUserResult 
 * @param setOrganizationFeatureResult 
 * @param removeOrganizationFeatureResult 
 * @param exportPrivateKeyResult 
 * @param exportWalletResult 
 * @param createSubOrganizationResultV4 
 * @param emailAuthResult 
 * @param exportWalletAccountResult 
 * @param initImportWalletResult 
 * @param importWalletResult 
 * @param initImportPrivateKeyResult 
 * @param importPrivateKeyResult 
 * @param createPoliciesResult 
 * @param signRawPayloadsResult 
 * @param createReadOnlySessionResult 
 * @param createOauthProvidersResult 
 * @param deleteOauthProvidersResult 
 * @param createSubOrganizationResultV5 
 * @param oauthResult 
 * @param createReadWriteSessionResult 
 * @param createSubOrganizationResultV6 
 * @param deletePrivateKeysResult 
 * @param deleteWalletsResult 
 * @param createReadWriteSessionResultV2 
 * @param deleteSubOrganizationResult 
 * @param initOtpAuthResult 
 * @param otpAuthResult 
 * @param createSubOrganizationResultV7 
 * @param updateWalletResult 
 * @param updatePolicyResultV2 
 * @param initOtpAuthResultV2 
 * @param initOtpResult 
 * @param verifyOtpResult 
 * @param otpLoginResult 
 * @param stampLoginResult 
 * @param oauthLoginResult 
 * @param updateUserNameResult 
 * @param updateUserEmailResult 
 * @param updateUserPhoneNumberResult 
 * @param initFiatOnRampResult 
 * @param createSmartContractInterfaceResult 
 * @param deleteSmartContractInterfaceResult 
 * @param enableAuthProxyResult 
 * @param disableAuthProxyResult 
 * @param updateAuthProxyConfigResult 
 * @param createOauth2CredentialResult 
 * @param updateOauth2CredentialResult 
 * @param deleteOauth2CredentialResult 
 * @param oauth2AuthenticateResult 
 */
@Serializable

data class V1Result (

    @SerialName(value = "createOrganizationResult")
    val createOrganizationResult: V1CreateOrganizationResult? = null,

    @SerialName(value = "createAuthenticatorsResult")
    val createAuthenticatorsResult: V1CreateAuthenticatorsResult? = null,

    @SerialName(value = "createUsersResult")
    val createUsersResult: V1CreateUsersResult? = null,

    @SerialName(value = "createPrivateKeysResult")
    val createPrivateKeysResult: V1CreatePrivateKeysResult? = null,

    @SerialName(value = "createInvitationsResult")
    val createInvitationsResult: V1CreateInvitationsResult? = null,

    @SerialName(value = "acceptInvitationResult")
    val acceptInvitationResult: V1AcceptInvitationResult? = null,

    @SerialName(value = "signRawPayloadResult")
    val signRawPayloadResult: V1SignRawPayloadResult? = null,

    @SerialName(value = "createPolicyResult")
    val createPolicyResult: V1CreatePolicyResult? = null,

    @SerialName(value = "disablePrivateKeyResult")
    val disablePrivateKeyResult: V1DisablePrivateKeyResult? = null,

    @SerialName(value = "deleteUsersResult")
    val deleteUsersResult: V1DeleteUsersResult? = null,

    @SerialName(value = "deleteAuthenticatorsResult")
    val deleteAuthenticatorsResult: V1DeleteAuthenticatorsResult? = null,

    @SerialName(value = "deleteInvitationResult")
    val deleteInvitationResult: V1DeleteInvitationResult? = null,

    @SerialName(value = "deleteOrganizationResult")
    val deleteOrganizationResult: V1DeleteOrganizationResult? = null,

    @SerialName(value = "deletePolicyResult")
    val deletePolicyResult: V1DeletePolicyResult? = null,

    @SerialName(value = "createUserTagResult")
    val createUserTagResult: V1CreateUserTagResult? = null,

    @SerialName(value = "deleteUserTagsResult")
    val deleteUserTagsResult: V1DeleteUserTagsResult? = null,

    @SerialName(value = "signTransactionResult")
    val signTransactionResult: V1SignTransactionResult? = null,

    @SerialName(value = "deleteApiKeysResult")
    val deleteApiKeysResult: V1DeleteApiKeysResult? = null,

    @SerialName(value = "createApiKeysResult")
    val createApiKeysResult: V1CreateApiKeysResult? = null,

    @SerialName(value = "createPrivateKeyTagResult")
    val createPrivateKeyTagResult: V1CreatePrivateKeyTagResult? = null,

    @SerialName(value = "deletePrivateKeyTagsResult")
    val deletePrivateKeyTagsResult: V1DeletePrivateKeyTagsResult? = null,

    @SerialName(value = "setPaymentMethodResult")
    val setPaymentMethodResult: BillingSetPaymentMethodResult? = null,

    @SerialName(value = "activateBillingTierResult")
    val activateBillingTierResult: BillingActivateBillingTierResult? = null,

    @SerialName(value = "deletePaymentMethodResult")
    val deletePaymentMethodResult: BillingDeletePaymentMethodResult? = null,

    @SerialName(value = "createApiOnlyUsersResult")
    val createApiOnlyUsersResult: V1CreateApiOnlyUsersResult? = null,

    @Contextual @SerialName(value = "updateRootQuorumResult")
    val updateRootQuorumResult: kotlin.Any? = null,

    @SerialName(value = "updateUserTagResult")
    val updateUserTagResult: V1UpdateUserTagResult? = null,

    @SerialName(value = "updatePrivateKeyTagResult")
    val updatePrivateKeyTagResult: V1UpdatePrivateKeyTagResult? = null,

    @SerialName(value = "createSubOrganizationResult")
    val createSubOrganizationResult: V1CreateSubOrganizationResult? = null,

    @Contextual @SerialName(value = "updateAllowedOriginsResult")
    val updateAllowedOriginsResult: kotlin.Any? = null,

    @SerialName(value = "createPrivateKeysResultV2")
    val createPrivateKeysResultV2: V1CreatePrivateKeysResultV2? = null,

    @SerialName(value = "updateUserResult")
    val updateUserResult: V1UpdateUserResult? = null,

    @SerialName(value = "updatePolicyResult")
    val updatePolicyResult: V1UpdatePolicyResult? = null,

    @SerialName(value = "createSubOrganizationResultV3")
    val createSubOrganizationResultV3: V1CreateSubOrganizationResultV3? = null,

    @SerialName(value = "createWalletResult")
    val createWalletResult: V1CreateWalletResult? = null,

    @SerialName(value = "createWalletAccountsResult")
    val createWalletAccountsResult: V1CreateWalletAccountsResult? = null,

    @SerialName(value = "initUserEmailRecoveryResult")
    val initUserEmailRecoveryResult: V1InitUserEmailRecoveryResult? = null,

    @SerialName(value = "recoverUserResult")
    val recoverUserResult: V1RecoverUserResult? = null,

    @SerialName(value = "setOrganizationFeatureResult")
    val setOrganizationFeatureResult: V1SetOrganizationFeatureResult? = null,

    @SerialName(value = "removeOrganizationFeatureResult")
    val removeOrganizationFeatureResult: V1RemoveOrganizationFeatureResult? = null,

    @SerialName(value = "exportPrivateKeyResult")
    val exportPrivateKeyResult: V1ExportPrivateKeyResult? = null,

    @SerialName(value = "exportWalletResult")
    val exportWalletResult: V1ExportWalletResult? = null,

    @SerialName(value = "createSubOrganizationResultV4")
    val createSubOrganizationResultV4: V1CreateSubOrganizationResultV4? = null,

    @SerialName(value = "emailAuthResult")
    val emailAuthResult: V1EmailAuthResult? = null,

    @SerialName(value = "exportWalletAccountResult")
    val exportWalletAccountResult: V1ExportWalletAccountResult? = null,

    @SerialName(value = "initImportWalletResult")
    val initImportWalletResult: V1InitImportWalletResult? = null,

    @SerialName(value = "importWalletResult")
    val importWalletResult: V1ImportWalletResult? = null,

    @SerialName(value = "initImportPrivateKeyResult")
    val initImportPrivateKeyResult: V1InitImportPrivateKeyResult? = null,

    @SerialName(value = "importPrivateKeyResult")
    val importPrivateKeyResult: V1ImportPrivateKeyResult? = null,

    @SerialName(value = "createPoliciesResult")
    val createPoliciesResult: V1CreatePoliciesResult? = null,

    @SerialName(value = "signRawPayloadsResult")
    val signRawPayloadsResult: V1SignRawPayloadsResult? = null,

    @SerialName(value = "createReadOnlySessionResult")
    val createReadOnlySessionResult: V1CreateReadOnlySessionResult? = null,

    @SerialName(value = "createOauthProvidersResult")
    val createOauthProvidersResult: V1CreateOauthProvidersResult? = null,

    @SerialName(value = "deleteOauthProvidersResult")
    val deleteOauthProvidersResult: V1DeleteOauthProvidersResult? = null,

    @SerialName(value = "createSubOrganizationResultV5")
    val createSubOrganizationResultV5: V1CreateSubOrganizationResultV5? = null,

    @SerialName(value = "oauthResult")
    val oauthResult: V1OauthResult? = null,

    @SerialName(value = "createReadWriteSessionResult")
    val createReadWriteSessionResult: V1CreateReadWriteSessionResult? = null,

    @SerialName(value = "createSubOrganizationResultV6")
    val createSubOrganizationResultV6: V1CreateSubOrganizationResultV6? = null,

    @SerialName(value = "deletePrivateKeysResult")
    val deletePrivateKeysResult: V1DeletePrivateKeysResult? = null,

    @SerialName(value = "deleteWalletsResult")
    val deleteWalletsResult: V1DeleteWalletsResult? = null,

    @SerialName(value = "createReadWriteSessionResultV2")
    val createReadWriteSessionResultV2: V1CreateReadWriteSessionResultV2? = null,

    @SerialName(value = "deleteSubOrganizationResult")
    val deleteSubOrganizationResult: V1DeleteSubOrganizationResult? = null,

    @SerialName(value = "initOtpAuthResult")
    val initOtpAuthResult: V1InitOtpAuthResult? = null,

    @SerialName(value = "otpAuthResult")
    val otpAuthResult: V1OtpAuthResult? = null,

    @SerialName(value = "createSubOrganizationResultV7")
    val createSubOrganizationResultV7: V1CreateSubOrganizationResultV7? = null,

    @SerialName(value = "updateWalletResult")
    val updateWalletResult: V1UpdateWalletResult? = null,

    @SerialName(value = "updatePolicyResultV2")
    val updatePolicyResultV2: V1UpdatePolicyResultV2? = null,

    @SerialName(value = "initOtpAuthResultV2")
    val initOtpAuthResultV2: V1InitOtpAuthResultV2? = null,

    @SerialName(value = "initOtpResult")
    val initOtpResult: V1InitOtpResult? = null,

    @SerialName(value = "verifyOtpResult")
    val verifyOtpResult: V1VerifyOtpResult? = null,

    @SerialName(value = "otpLoginResult")
    val otpLoginResult: V1OtpLoginResult? = null,

    @SerialName(value = "stampLoginResult")
    val stampLoginResult: V1StampLoginResult? = null,

    @SerialName(value = "oauthLoginResult")
    val oauthLoginResult: V1OauthLoginResult? = null,

    @SerialName(value = "updateUserNameResult")
    val updateUserNameResult: V1UpdateUserNameResult? = null,

    @SerialName(value = "updateUserEmailResult")
    val updateUserEmailResult: V1UpdateUserEmailResult? = null,

    @SerialName(value = "updateUserPhoneNumberResult")
    val updateUserPhoneNumberResult: V1UpdateUserPhoneNumberResult? = null,

    @SerialName(value = "initFiatOnRampResult")
    val initFiatOnRampResult: V1InitFiatOnRampResult? = null,

    @SerialName(value = "createSmartContractInterfaceResult")
    val createSmartContractInterfaceResult: V1CreateSmartContractInterfaceResult? = null,

    @SerialName(value = "deleteSmartContractInterfaceResult")
    val deleteSmartContractInterfaceResult: V1DeleteSmartContractInterfaceResult? = null,

    @SerialName(value = "enableAuthProxyResult")
    val enableAuthProxyResult: V1EnableAuthProxyResult? = null,

    @Contextual @SerialName(value = "disableAuthProxyResult")
    val disableAuthProxyResult: kotlin.Any? = null,

    @SerialName(value = "updateAuthProxyConfigResult")
    val updateAuthProxyConfigResult: V1UpdateAuthProxyConfigResult? = null,

    @SerialName(value = "createOauth2CredentialResult")
    val createOauth2CredentialResult: V1CreateOauth2CredentialResult? = null,

    @SerialName(value = "updateOauth2CredentialResult")
    val updateOauth2CredentialResult: V1UpdateOauth2CredentialResult? = null,

    @SerialName(value = "deleteOauth2CredentialResult")
    val deleteOauth2CredentialResult: V1DeleteOauth2CredentialResult? = null,

    @SerialName(value = "oauth2AuthenticateResult")
    val oauth2AuthenticateResult: V1Oauth2AuthenticateResult? = null

) {


}

