/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1ApiKeyParamsV2
import com.turnkey.http.model.V1AuthenticatorParamsV2
import com.turnkey.http.model.V1OauthProviderParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userName Human-readable name for a User.
 * @param apiKeys A list of API Key parameters. This field, if not needed, should be an empty array in your request body.
 * @param authenticators A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body.
 * @param oauthProviders A list of Oauth providers. This field, if not needed, should be an empty array in your request body.
 * @param userEmail The user's email address.
 * @param userPhoneNumber The user's phone number in E.164 format e.g. +13214567890
 */
@Serializable

data class V1RootUserParamsV4 (

    /* Human-readable name for a User. */
    @SerialName(value = "userName")
    val userName: kotlin.String,

    /* A list of API Key parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "apiKeys")
    val apiKeys: kotlin.collections.List<V1ApiKeyParamsV2>,

    /* A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "authenticators")
    val authenticators: kotlin.collections.List<V1AuthenticatorParamsV2>,

    /* A list of Oauth providers. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "oauthProviders")
    val oauthProviders: kotlin.collections.List<V1OauthProviderParams>,

    /* The user's email address. */
    @SerialName(value = "userEmail")
    val userEmail: kotlin.String? = null,

    /* The user's phone number in E.164 format e.g. +13214567890 */
    @SerialName(value = "userPhoneNumber")
    val userPhoneNumber: kotlin.String? = null

) {


}

