/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1FeatureName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param `value` Optional value for the feature. Will override existing values if feature is already set.
 */
@Serializable

data class V1SetOrganizationFeatureIntent (

    @Contextual @SerialName(value = "name")
    val name: V1FeatureName,

    /* Optional value for the feature. Will override existing values if feature is already set. */
    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

