/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1Operator

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subject 
 * @param `operator` 
 * @param targets 
 */
@Serializable

data class V1SelectorV2 (

    @SerialName(value = "subject")
    val subject: kotlin.String? = null,

    @Contextual @SerialName(value = "operator")
    val `operator`: V1Operator? = null,

    @SerialName(value = "targets")
    val targets: kotlin.collections.List<kotlin.String>? = null

) {


}

