/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param r Component of an ECSDA signature.
 * @param s Component of an ECSDA signature.
 * @param v Component of an ECSDA signature.
 */
@Serializable

data class V1SignRawPayloadResult (

    /* Component of an ECSDA signature. */
    @SerialName(value = "r")
    val r: kotlin.String,

    /* Component of an ECSDA signature. */
    @SerialName(value = "s")
    val s: kotlin.String,

    /* Component of an ECSDA signature. */
    @SerialName(value = "v")
    val v: kotlin.String

) {


}

