/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1HashFunction
import com.turnkey.http.model.V1PayloadEncoding

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param signWith A Wallet account address, Private Key address, or Private Key identifier.
 * @param payloads An array of raw unsigned payloads to be signed.
 * @param encoding 
 * @param hashFunction 
 */
@Serializable

data class V1SignRawPayloadsIntent (

    /* A Wallet account address, Private Key address, or Private Key identifier. */
    @SerialName(value = "signWith")
    val signWith: kotlin.String,

    /* An array of raw unsigned payloads to be signed. */
    @SerialName(value = "payloads")
    val payloads: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "encoding")
    val encoding: V1PayloadEncoding,

    @Contextual @SerialName(value = "hashFunction")
    val hashFunction: V1HashFunction

) {


}

