/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1HashFunction
import com.turnkey.http.model.V1PayloadEncoding

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyId Unique identifier for a given Private Key.
 * @param payload Raw unsigned payload to be signed.
 * @param encoding 
 * @param hashFunction 
 */
@Serializable

data class V1SignRawPayloadIntent (

    /* Unique identifier for a given Private Key. */
    @SerialName(value = "privateKeyId")
    val privateKeyId: kotlin.String,

    /* Raw unsigned payload to be signed. */
    @SerialName(value = "payload")
    val payload: kotlin.String,

    @Contextual @SerialName(value = "encoding")
    val encoding: V1PayloadEncoding,

    @Contextual @SerialName(value = "hashFunction")
    val hashFunction: V1HashFunction

) {


}

