/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1TransactionType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param signWith A Wallet account address, Private Key address, or Private Key identifier.
 * @param unsignedTransaction Raw unsigned transaction to be signed
 * @param type 
 */
@Serializable

data class V1SignTransactionIntentV2 (

    /* A Wallet account address, Private Key address, or Private Key identifier. */
    @SerialName(value = "signWith")
    val signWith: kotlin.String,

    /* Raw unsigned transaction to be signed */
    @SerialName(value = "unsignedTransaction")
    val unsignedTransaction: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: V1TransactionType

) {


}

