/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1SignRawPayloadResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param signatures 
 */
@Serializable

data class V1SignRawPayloadsResult (

    @SerialName(value = "signatures")
    val signatures: kotlin.collections.List<V1SignRawPayloadResult>? = null

) {


}

