/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId The Organization the Smart Contract Interface belongs to.
 * @param smartContractInterfaceId Unique identifier for a given Smart Contract Interface (ABI or IDL).
 * @param smartContractAddress The address corresponding to the Smart Contract or Program.
 * @param smartContractInterface The JSON corresponding to the Smart Contract Interface (ABI or IDL).
 * @param type The type corresponding to the Smart Contract Interface (either ETHEREUM or SOLANA).
 * @param label The label corresponding to the Smart Contract Interface (either ETHEREUM or SOLANA).
 * @param notes The notes corresponding to the Smart Contract Interface (either ETHEREUM or SOLANA).
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class V1SmartContractInterface (

    /* The Organization the Smart Contract Interface belongs to. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Unique identifier for a given Smart Contract Interface (ABI or IDL). */
    @SerialName(value = "smartContractInterfaceId")
    val smartContractInterfaceId: kotlin.String,

    /* The address corresponding to the Smart Contract or Program. */
    @SerialName(value = "smartContractAddress")
    val smartContractAddress: kotlin.String,

    /* The JSON corresponding to the Smart Contract Interface (ABI or IDL). */
    @SerialName(value = "smartContractInterface")
    val smartContractInterface: kotlin.String,

    /* The type corresponding to the Smart Contract Interface (either ETHEREUM or SOLANA). */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* The label corresponding to the Smart Contract Interface (either ETHEREUM or SOLANA). */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* The notes corresponding to the Smart Contract Interface (either ETHEREUM or SOLANA). */
    @SerialName(value = "notes")
    val notes: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp

) {


}

