/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param publicKey Client-side public key generated by the user, which will be conditionally added to org data based on the passkey stamp associated with this request
 * @param expirationSeconds Expiration window (in seconds) indicating how long the Session is valid for. If not provided, a default of 15 minutes will be used.
 * @param invalidateExisting Invalidate all other previously generated Login API keys
 */
@Serializable

data class V1StampLoginIntent (

    /* Client-side public key generated by the user, which will be conditionally added to org data based on the passkey stamp associated with this request */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* Expiration window (in seconds) indicating how long the Session is valid for. If not provided, a default of 15 minutes will be used. */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    /* Invalidate all other previously generated Login API keys */
    @SerialName(value = "invalidateExisting")
    val invalidateExisting: kotlin.Boolean? = null

) {


}

