/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param organizationId Unique identifier for a given organization. If the request is being made by a WebAuthN user and their sub-organization ID is unknown, this can be the parent organization ID; using the sub-organization ID when possible is preferred due to performance reasons.
 * @param isSetLimit Whether or not to set a limit on this request.
 * @param limit Rate limit to set for org, if is_set_limit is set to true.
 */
@Serializable

data class V1TestRateLimitsRequest (

    /* Unique identifier for a given organization. If the request is being made by a WebAuthN user and their sub-organization ID is unknown, this can be the parent organization ID; using the sub-organization ID when possible is preferred due to performance reasons. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Whether or not to set a limit on this request. */
    @SerialName(value = "isSetLimit")
    val isSetLimit: kotlin.Boolean,

    /* Rate limit to set for org, if is_set_limit is set to true. */
    @SerialName(value = "limit")
    val limit: kotlin.Long

) {


}

