/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1Effect

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param policyId Unique identifier for a given Policy.
 * @param policyName Human-readable name for a Policy.
 * @param policyEffect 
 * @param policyCondition The condition expression that triggers the Effect (optional).
 * @param policyConsensus The consensus expression that triggers the Effect (optional).
 * @param policyNotes Accompanying notes for a Policy (optional).
 */
@Serializable

data class V1UpdatePolicyIntentV2 (

    /* Unique identifier for a given Policy. */
    @SerialName(value = "policyId")
    val policyId: kotlin.String,

    /* Human-readable name for a Policy. */
    @SerialName(value = "policyName")
    val policyName: kotlin.String? = null,

    @Contextual @SerialName(value = "policyEffect")
    val policyEffect: V1Effect? = null,

    /* The condition expression that triggers the Effect (optional). */
    @SerialName(value = "policyCondition")
    val policyCondition: kotlin.String? = null,

    /* The consensus expression that triggers the Effect (optional). */
    @SerialName(value = "policyConsensus")
    val policyConsensus: kotlin.String? = null,

    /* Accompanying notes for a Policy (optional). */
    @SerialName(value = "policyNotes")
    val policyNotes: kotlin.String? = null

) {


}

