/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param policyId Unique identifier for a given Policy.
 */
@Serializable

data class V1UpdatePolicyResult (

    /* Unique identifier for a given Policy. */
    @SerialName(value = "policyId")
    val policyId: kotlin.String

) {


}

