/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId Unique identifier of the User whose email was updated.
 */
@Serializable

data class V1UpdateUserEmailResult (

    /* Unique identifier of the User whose email was updated. */
    @SerialName(value = "userId")
    val userId: kotlin.String

) {


}

