/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId Unique identifier for a given User.
 * @param userPhoneNumber The user's phone number in E.164 format e.g. +13214567890. Setting this to an empty string will remove the user's phone number.
 * @param verificationToken Signed JWT containing a unique id, expiry, verification type, contact
 */
@Serializable

data class V1UpdateUserPhoneNumberIntent (

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* The user's phone number in E.164 format e.g. +13214567890. Setting this to an empty string will remove the user's phone number. */
    @SerialName(value = "userPhoneNumber")
    val userPhoneNumber: kotlin.String,

    /* Signed JWT containing a unique id, expiry, verification type, contact */
    @SerialName(value = "verificationToken")
    val verificationToken: kotlin.String? = null

) {


}

