/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1EmailCustomizationParams
import com.turnkey.http.model.V1SmsCustomizationParams
import com.turnkey.http.model.V1WalletKitSettingsParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param allowedOrigins Updated list of allowed origins for CORS.
 * @param allowedAuthMethods Updated list of allowed proxy authentication methods.
 * @param sendFromEmailAddress Custom 'from' address for auth-related emails.
 * @param replyToEmailAddress Custom reply-to address for auth-related emails.
 * @param emailAuthTemplateId Template ID for email-auth messages.
 * @param otpTemplateId Template ID for OTP SMS messages.
 * @param emailCustomizationParams 
 * @param smsCustomizationParams 
 * @param walletKitSettings 
 * @param otpExpirationSeconds OTP code lifetime in seconds.
 * @param verificationTokenExpirationSeconds Verification-token lifetime in seconds.
 * @param sessionExpirationSeconds Session lifetime in seconds.
 * @param otpAlphanumeric Enable alphanumeric OTP codes.
 * @param otpLength Desired OTP code length (6–9).
 */
@Serializable

data class V1UpdateAuthProxyConfigIntent (

    /* Updated list of allowed origins for CORS. */
    @SerialName(value = "allowedOrigins")
    val allowedOrigins: kotlin.collections.List<kotlin.String>? = null,

    /* Updated list of allowed proxy authentication methods. */
    @SerialName(value = "allowedAuthMethods")
    val allowedAuthMethods: kotlin.collections.List<kotlin.String>? = null,

    /* Custom 'from' address for auth-related emails. */
    @SerialName(value = "sendFromEmailAddress")
    val sendFromEmailAddress: kotlin.String? = null,

    /* Custom reply-to address for auth-related emails. */
    @SerialName(value = "replyToEmailAddress")
    val replyToEmailAddress: kotlin.String? = null,

    /* Template ID for email-auth messages. */
    @SerialName(value = "emailAuthTemplateId")
    val emailAuthTemplateId: kotlin.String? = null,

    /* Template ID for OTP SMS messages. */
    @SerialName(value = "otpTemplateId")
    val otpTemplateId: kotlin.String? = null,

    @SerialName(value = "emailCustomizationParams")
    val emailCustomizationParams: V1EmailCustomizationParams? = null,

    @SerialName(value = "smsCustomizationParams")
    val smsCustomizationParams: V1SmsCustomizationParams? = null,

    @SerialName(value = "walletKitSettings")
    val walletKitSettings: V1WalletKitSettingsParams? = null,

    /* OTP code lifetime in seconds. */
    @SerialName(value = "otpExpirationSeconds")
    val otpExpirationSeconds: kotlin.Int? = null,

    /* Verification-token lifetime in seconds. */
    @SerialName(value = "verificationTokenExpirationSeconds")
    val verificationTokenExpirationSeconds: kotlin.Int? = null,

    /* Session lifetime in seconds. */
    @SerialName(value = "sessionExpirationSeconds")
    val sessionExpirationSeconds: kotlin.Int? = null,

    /* Enable alphanumeric OTP codes. */
    @SerialName(value = "otpAlphanumeric")
    val otpAlphanumeric: kotlin.Boolean? = null,

    /* Desired OTP code length (6–9). */
    @SerialName(value = "otpLength")
    val otpLength: kotlin.Int? = null

) {


}

