/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId Unique identifier for a given User.
 * @param userName Human-readable name for a User.
 * @param userEmail The user's email address.
 * @param userTagIds An updated list of User Tags to apply to this User. This field, if not needed, should be an empty array in your request body.
 * @param userPhoneNumber The user's phone number in E.164 format e.g. +13214567890
 */
@Serializable

data class V1UpdateUserIntent (

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Human-readable name for a User. */
    @SerialName(value = "userName")
    val userName: kotlin.String? = null,

    /* The user's email address. */
    @SerialName(value = "userEmail")
    val userEmail: kotlin.String? = null,

    /* An updated list of User Tags to apply to this User. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "userTagIds")
    val userTagIds: kotlin.collections.List<kotlin.String>? = null,

    /* The user's phone number in E.164 format e.g. +13214567890 */
    @SerialName(value = "userPhoneNumber")
    val userPhoneNumber: kotlin.String? = null

) {


}

