/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privateKeyTagId Unique identifier for a given Private Key Tag.
 * @param addPrivateKeyIds A list of Private Keys IDs to add this tag to.
 * @param removePrivateKeyIds A list of Private Key IDs to remove this tag from.
 * @param newPrivateKeyTagName The new, human-readable name for the tag with the given ID.
 */
@Serializable

data class V1UpdatePrivateKeyTagIntent (

    /* Unique identifier for a given Private Key Tag. */
    @SerialName(value = "privateKeyTagId")
    val privateKeyTagId: kotlin.String,

    /* A list of Private Keys IDs to add this tag to. */
    @SerialName(value = "addPrivateKeyIds")
    val addPrivateKeyIds: kotlin.collections.List<kotlin.String>,

    /* A list of Private Key IDs to remove this tag from. */
    @SerialName(value = "removePrivateKeyIds")
    val removePrivateKeyIds: kotlin.collections.List<kotlin.String>,

    /* The new, human-readable name for the tag with the given ID. */
    @SerialName(value = "newPrivateKeyTagName")
    val newPrivateKeyTagName: kotlin.String? = null

) {


}

