/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configId Unique identifier for a given User. (representing the turnkey signer user id)
 */
@Serializable

data class V1UpdateAuthProxyConfigResult (

    /* Unique identifier for a given User. (representing the turnkey signer user id) */
    @SerialName(value = "configId")
    val configId: kotlin.String? = null

) {


}

