/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param allowedOrigins Additional origins requests are allowed from besides Turnkey origins
 */
@Serializable

data class V1UpdateAllowedOriginsIntent (

    /* Additional origins requests are allowed from besides Turnkey origins */
    @SerialName(value = "allowedOrigins")
    val allowedOrigins: kotlin.collections.List<kotlin.String>

) {


}

