/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletId Unique identifier for a given Wallet.
 * @param walletName Human-readable name for a Wallet.
 */
@Serializable

data class V1UpdateWalletIntent (

    /* Unique identifier for a given Wallet. */
    @SerialName(value = "walletId")
    val walletId: kotlin.String,

    /* Human-readable name for a Wallet. */
    @SerialName(value = "walletName")
    val walletName: kotlin.String? = null

) {


}

