/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userTagId Unique identifier for a given User Tag.
 * @param addUserIds A list of User IDs to add this tag to.
 * @param removeUserIds A list of User IDs to remove this tag from.
 * @param newUserTagName The new, human-readable name for the tag with the given ID.
 */
@Serializable

data class V1UpdateUserTagIntent (

    /* Unique identifier for a given User Tag. */
    @SerialName(value = "userTagId")
    val userTagId: kotlin.String,

    /* A list of User IDs to add this tag to. */
    @SerialName(value = "addUserIds")
    val addUserIds: kotlin.collections.List<kotlin.String>,

    /* A list of User IDs to remove this tag from. */
    @SerialName(value = "removeUserIds")
    val removeUserIds: kotlin.collections.List<kotlin.String>,

    /* The new, human-readable name for the tag with the given ID. */
    @SerialName(value = "newUserTagName")
    val newUserTagName: kotlin.String? = null

) {


}

