/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.V1Oauth2Provider

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param oauth2CredentialId The ID of the OAuth 2.0 credential to update
 * @param provider 
 * @param clientId The Client ID issued by the OAuth 2.0 provider
 * @param encryptedClientSecret The client secret issued by the OAuth 2.0 provider encrypted to the TLS Fetcher quorum key
 */
@Serializable

data class V1UpdateOauth2CredentialIntent (

    /* The ID of the OAuth 2.0 credential to update */
    @SerialName(value = "oauth2CredentialId")
    val oauth2CredentialId: kotlin.String,

    @Contextual @SerialName(value = "provider")
    val provider: V1Oauth2Provider,

    /* The Client ID issued by the OAuth 2.0 provider */
    @SerialName(value = "clientId")
    val clientId: kotlin.String,

    /* The client secret issued by the OAuth 2.0 provider encrypted to the TLS Fetcher quorum key */
    @SerialName(value = "encryptedClientSecret")
    val encryptedClientSecret: kotlin.String

) {


}

