/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.ApiApiKeyParams
import com.turnkey.http.model.V1AccessType
import com.turnkey.http.model.V1AuthenticatorParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userName Human-readable name for a User.
 * @param accessType 
 * @param apiKeys A list of API Key parameters. This field, if not needed, should be an empty array in your request body.
 * @param authenticators A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body.
 * @param userTags A list of User Tag IDs. This field, if not needed, should be an empty array in your request body.
 * @param userEmail The user's email address.
 */
@Serializable

data class V1UserParams (

    /* Human-readable name for a User. */
    @SerialName(value = "userName")
    val userName: kotlin.String,

    @Contextual @SerialName(value = "accessType")
    val accessType: V1AccessType,

    /* A list of API Key parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "apiKeys")
    val apiKeys: kotlin.collections.List<ApiApiKeyParams>,

    /* A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "authenticators")
    val authenticators: kotlin.collections.List<V1AuthenticatorParams>,

    /* A list of User Tag IDs. This field, if not needed, should be an empty array in your request body. */
    @SerialName(value = "userTags")
    val userTags: kotlin.collections.List<kotlin.String>,

    /* The user's email address. */
    @SerialName(value = "userEmail")
    val userEmail: kotlin.String? = null

) {


}

