/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param otpId ID representing the result of an init OTP activity.
 * @param otpCode OTP sent out to a user's contact (email or SMS)
 * @param expirationSeconds Expiration window (in seconds) indicating how long the verification token is valid for. If not provided, a default of 1 hour will be used. Maximum value is 86400 seconds (24 hours)
 * @param publicKey Client-side public key generated by the user, which will be added to the JWT response and verified in subsequent requests via a client proof signature
 */
@Serializable

data class V1VerifyOtpIntent (

    /* ID representing the result of an init OTP activity. */
    @SerialName(value = "otpId")
    val otpId: kotlin.String,

    /* OTP sent out to a user's contact (email or SMS) */
    @SerialName(value = "otpCode")
    val otpCode: kotlin.String,

    /* Expiration window (in seconds) indicating how long the verification token is valid for. If not provided, a default of 1 hour will be used. Maximum value is 86400 seconds (24 hours) */
    @SerialName(value = "expirationSeconds")
    val expirationSeconds: kotlin.String? = null,

    /* Client-side public key generated by the user, which will be added to the JWT response and verified in subsequent requests via a client proof signature */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String? = null

) {


}

