/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.V1User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier for a given Vote object.
 * @param userId Unique identifier for a given User.
 * @param user 
 * @param activityId Unique identifier for a given Activity object.
 * @param selection 
 * @param message The raw message being signed within a Vote.
 * @param publicKey The public component of a cryptographic key pair used to sign messages and transactions.
 * @param signature The signature applied to a particular vote.
 * @param scheme Method used to produce a signature.
 * @param createdAt 
 */
@Serializable

data class V1Vote (

    /* Unique identifier for a given Vote object. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Unique identifier for a given User. */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "user")
    val user: V1User,

    /* Unique identifier for a given Activity object. */
    @SerialName(value = "activityId")
    val activityId: kotlin.String,

    @SerialName(value = "selection")
    val selection: V1Vote.Selection,

    /* The raw message being signed within a Vote. */
    @SerialName(value = "message")
    val message: kotlin.String,

    /* The public component of a cryptographic key pair used to sign messages and transactions. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* The signature applied to a particular vote. */
    @SerialName(value = "signature")
    val signature: kotlin.String,

    /* Method used to produce a signature. */
    @SerialName(value = "scheme")
    val scheme: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp

) {

    /**
     * 
     *
     * Values: VOTE_SELECTION_APPROVED,VOTE_SELECTION_REJECTED
     */
    @Serializable
    enum class Selection(val value: kotlin.String) {
        @SerialName(value = "VOTE_SELECTION_APPROVED") VOTE_SELECTION_APPROVED("VOTE_SELECTION_APPROVED"),
        @SerialName(value = "VOTE_SELECTION_REJECTED") VOTE_SELECTION_REJECTED("VOTE_SELECTION_REJECTED");
    }

}

