/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletId Unique identifier for a given Wallet.
 * @param walletName Human-readable name for a Wallet.
 * @param createdAt 
 * @param updatedAt 
 * @param exported True when a given Wallet is exported, false otherwise.
 * @param imported True when a given Wallet is imported, false otherwise.
 */
@Serializable

data class V1Wallet (

    /* Unique identifier for a given Wallet. */
    @SerialName(value = "walletId")
    val walletId: kotlin.String,

    /* Human-readable name for a Wallet. */
    @SerialName(value = "walletName")
    val walletName: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp,

    /* True when a given Wallet is exported, false otherwise. */
    @SerialName(value = "exported")
    val exported: kotlin.Boolean,

    /* True when a given Wallet is imported, false otherwise. */
    @SerialName(value = "imported")
    val imported: kotlin.Boolean

) {


}

