/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabledSocialProviders List of enabled social login providers (e.g., 'apple', 'google', 'facebook')
 * @param oauthClientIds Mapping of social login providers to their Oauth client IDs.
 * @param oauthRedirectUrl Oauth redirect URL to be used for social login flows.
 */
@Serializable

data class V1WalletKitSettingsParams (

    /* List of enabled social login providers (e.g., 'apple', 'google', 'facebook') */
    @SerialName(value = "enabledSocialProviders")
    val enabledSocialProviders: kotlin.collections.List<kotlin.String>? = null,

    /* Mapping of social login providers to their Oauth client IDs. */
    @SerialName(value = "oauthClientIds")
    val oauthClientIds: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Oauth redirect URL to be used for social login flows. */
    @SerialName(value = "oauthRedirectUrl")
    val oauthRedirectUrl: kotlin.String? = null

) {


}

