/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model

import com.turnkey.http.model.Externaldatav1Timestamp
import com.turnkey.http.model.V1AddressFormat
import com.turnkey.http.model.V1Curve
import com.turnkey.http.model.V1PathFormat
import com.turnkey.http.model.V1Wallet

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletAccountId Unique identifier for a given Wallet Account.
 * @param organizationId The Organization the Account belongs to.
 * @param walletId The Wallet the Account was derived from.
 * @param curve 
 * @param pathFormat 
 * @param path Path used to generate the Account.
 * @param addressFormat 
 * @param address Address generated using the Wallet seed and Account parameters.
 * @param createdAt 
 * @param updatedAt 
 * @param publicKey The public component of this wallet account's underlying cryptographic key pair.
 * @param walletDetails 
 */
@Serializable

data class V1WalletAccount (

    /* Unique identifier for a given Wallet Account. */
    @SerialName(value = "walletAccountId")
    val walletAccountId: kotlin.String,

    /* The Organization the Account belongs to. */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* The Wallet the Account was derived from. */
    @SerialName(value = "walletId")
    val walletId: kotlin.String,

    @Contextual @SerialName(value = "curve")
    val curve: V1Curve,

    @Contextual @SerialName(value = "pathFormat")
    val pathFormat: V1PathFormat,

    /* Path used to generate the Account. */
    @SerialName(value = "path")
    val path: kotlin.String,

    @Contextual @SerialName(value = "addressFormat")
    val addressFormat: V1AddressFormat,

    /* Address generated using the Wallet seed and Account parameters. */
    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: Externaldatav1Timestamp,

    @SerialName(value = "updatedAt")
    val updatedAt: Externaldatav1Timestamp,

    /* The public component of this wallet account's underlying cryptographic key pair. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String? = null,

    @SerialName(value = "walletDetails")
    val walletDetails: V1Wallet? = null

) {


}

