/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.turnkey.http.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param credentialId A base64 url encoded Unique identifier for a given credential.
 * @param clientDataJson A base64 encoded payload containing metadata about the signing context and the challenge.
 * @param authenticatorData A base64 encoded payload containing metadata about the authenticator.
 * @param signature The base64 url encoded signature bytes contained within the WebAuthn assertion response.
 */
@Serializable

data class V1WebAuthnStamp (

    /* A base64 url encoded Unique identifier for a given credential. */
    @SerialName(value = "credentialId")
    val credentialId: kotlin.String,

    /* A base64 encoded payload containing metadata about the signing context and the challenge. */
    @SerialName(value = "clientDataJson")
    val clientDataJson: kotlin.String,

    /* A base64 encoded payload containing metadata about the authenticator. */
    @SerialName(value = "authenticatorData")
    val authenticatorData: kotlin.String,

    /* The base64 url encoded signature bytes contained within the WebAuthn assertion response. */
    @SerialName(value = "signature")
    val signature: kotlin.String

) {


}

