// /* @generated by codegen. DO NOT EDIT BY HAND */
package com.turnkey.http

import ProxyTGetAccountBody
import ProxyTGetWalletKitConfigBody
import ProxyTInitOtpBody
import ProxyTOAuth2AuthenticateBody
import ProxyTOAuthLoginBody
import ProxyTOtpLoginBody
import ProxyTSignupBody
import ProxyTVerifyOtpBody
import TApproveActivityBody
import TCreateApiKeysBody
import TCreateApiOnlyUsersBody
import TCreateAuthenticatorsBody
import TCreateInvitationsBody
import TCreateOauth2CredentialBody
import TCreateOauthProvidersBody
import TCreatePoliciesBody
import TCreatePolicyBody
import TCreatePrivateKeyTagBody
import TCreatePrivateKeysBody
import TCreateReadOnlySessionBody
import TCreateReadWriteSessionBody
import TCreateSmartContractInterfaceBody
import TCreateSubOrganizationBody
import TCreateUserTagBody
import TCreateUsersBody
import TCreateWalletAccountsBody
import TCreateWalletBody
import TDeleteApiKeysBody
import TDeleteAuthenticatorsBody
import TDeleteInvitationBody
import TDeleteOauth2CredentialBody
import TDeleteOauthProvidersBody
import TDeletePolicyBody
import TDeletePrivateKeyTagsBody
import TDeletePrivateKeysBody
import TDeleteSmartContractInterfaceBody
import TDeleteSubOrganizationBody
import TDeleteUserTagsBody
import TDeleteUsersBody
import TDeleteWalletsBody
import TEmailAuthBody
import TExportPrivateKeyBody
import TExportWalletAccountBody
import TExportWalletBody
import TGetActivitiesBody
import TGetActivityBody
import TGetApiKeyBody
import TGetApiKeysBody
import TGetAppProofsBody
import TGetAttestationDocumentBody
import TGetAuthenticatorBody
import TGetAuthenticatorsBody
import TGetBootProofBody
import TGetLatestBootProofBody
import TGetOauth2CredentialBody
import TGetOauthProvidersBody
import TGetOrganizationBody
import TGetOrganizationConfigsBody
import TGetPoliciesBody
import TGetPolicyBody
import TGetPolicyEvaluationsBody
import TGetPrivateKeyBody
import TGetPrivateKeysBody
import TGetSmartContractInterfaceBody
import TGetSmartContractInterfacesBody
import TGetSubOrgIdsBody
import TGetUserBody
import TGetUsersBody
import TGetVerifiedSubOrgIdsBody
import TGetWalletAccountBody
import TGetWalletAccountsBody
import TGetWalletBody
import TGetWalletsBody
import TGetWhoamiBody
import TImportPrivateKeyBody
import TImportWalletBody
import TInitFiatOnRampBody
import TInitImportPrivateKeyBody
import TInitImportWalletBody
import TInitOtpAuthBody
import TInitOtpBody
import TInitUserEmailRecoveryBody
import TListOauth2CredentialsBody
import TListPrivateKeyTagsBody
import TListUserTagsBody
import TOauth2AuthenticateBody
import TOauthBody
import TOauthLoginBody
import TOtpAuthBody
import TOtpLoginBody
import TRecoverUserBody
import TRejectActivityBody
import TRemoveOrganizationFeatureBody
import TSetOrganizationFeatureBody
import TSignRawPayloadBody
import TSignRawPayloadsBody
import TSignTransactionBody
import TStampLoginBody
import TTestRateLimitsBody
import TUpdateOauth2CredentialBody
import TUpdatePolicyBody
import TUpdatePrivateKeyTagBody
import TUpdateRootQuorumBody
import TUpdateUserBody
import TUpdateUserEmailBody
import TUpdateUserNameBody
import TUpdateUserPhoneNumberBody
import TUpdateUserTagBody
import TUpdateWalletBody
import TVerifyOtpBody
import V1Activity
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
public enum class V1AccessType {
  @SerialName("ACCESS_TYPE_WEB")
  ACCESS_TYPE_WEB,
  @SerialName("ACCESS_TYPE_API")
  ACCESS_TYPE_API,
  @SerialName("ACCESS_TYPE_ALL")
  ACCESS_TYPE_ALL,
}

@Serializable
public enum class V1ActivityStatus {
  @SerialName("ACTIVITY_STATUS_CREATED")
  ACTIVITY_STATUS_CREATED,
  @SerialName("ACTIVITY_STATUS_PENDING")
  ACTIVITY_STATUS_PENDING,
  @SerialName("ACTIVITY_STATUS_COMPLETED")
  ACTIVITY_STATUS_COMPLETED,
  @SerialName("ACTIVITY_STATUS_FAILED")
  ACTIVITY_STATUS_FAILED,
  @SerialName("ACTIVITY_STATUS_CONSENSUS_NEEDED")
  ACTIVITY_STATUS_CONSENSUS_NEEDED,
  @SerialName("ACTIVITY_STATUS_REJECTED")
  ACTIVITY_STATUS_REJECTED,
}

@Serializable
public enum class V1ActivityType {
  @SerialName("ACTIVITY_TYPE_CREATE_API_KEYS")
  ACTIVITY_TYPE_CREATE_API_KEYS,
  @SerialName("ACTIVITY_TYPE_CREATE_USERS")
  ACTIVITY_TYPE_CREATE_USERS,
  @SerialName("ACTIVITY_TYPE_CREATE_PRIVATE_KEYS")
  ACTIVITY_TYPE_CREATE_PRIVATE_KEYS,
  @SerialName("ACTIVITY_TYPE_SIGN_RAW_PAYLOAD")
  ACTIVITY_TYPE_SIGN_RAW_PAYLOAD,
  @SerialName("ACTIVITY_TYPE_CREATE_INVITATIONS")
  ACTIVITY_TYPE_CREATE_INVITATIONS,
  @SerialName("ACTIVITY_TYPE_ACCEPT_INVITATION")
  ACTIVITY_TYPE_ACCEPT_INVITATION,
  @SerialName("ACTIVITY_TYPE_CREATE_POLICY")
  ACTIVITY_TYPE_CREATE_POLICY,
  @SerialName("ACTIVITY_TYPE_DISABLE_PRIVATE_KEY")
  ACTIVITY_TYPE_DISABLE_PRIVATE_KEY,
  @SerialName("ACTIVITY_TYPE_DELETE_USERS")
  ACTIVITY_TYPE_DELETE_USERS,
  @SerialName("ACTIVITY_TYPE_DELETE_API_KEYS")
  ACTIVITY_TYPE_DELETE_API_KEYS,
  @SerialName("ACTIVITY_TYPE_DELETE_INVITATION")
  ACTIVITY_TYPE_DELETE_INVITATION,
  @SerialName("ACTIVITY_TYPE_DELETE_ORGANIZATION")
  ACTIVITY_TYPE_DELETE_ORGANIZATION,
  @SerialName("ACTIVITY_TYPE_DELETE_POLICY")
  ACTIVITY_TYPE_DELETE_POLICY,
  @SerialName("ACTIVITY_TYPE_CREATE_USER_TAG")
  ACTIVITY_TYPE_CREATE_USER_TAG,
  @SerialName("ACTIVITY_TYPE_DELETE_USER_TAGS")
  ACTIVITY_TYPE_DELETE_USER_TAGS,
  @SerialName("ACTIVITY_TYPE_CREATE_ORGANIZATION")
  ACTIVITY_TYPE_CREATE_ORGANIZATION,
  @SerialName("ACTIVITY_TYPE_SIGN_TRANSACTION")
  ACTIVITY_TYPE_SIGN_TRANSACTION,
  @SerialName("ACTIVITY_TYPE_APPROVE_ACTIVITY")
  ACTIVITY_TYPE_APPROVE_ACTIVITY,
  @SerialName("ACTIVITY_TYPE_REJECT_ACTIVITY")
  ACTIVITY_TYPE_REJECT_ACTIVITY,
  @SerialName("ACTIVITY_TYPE_DELETE_AUTHENTICATORS")
  ACTIVITY_TYPE_DELETE_AUTHENTICATORS,
  @SerialName("ACTIVITY_TYPE_CREATE_AUTHENTICATORS")
  ACTIVITY_TYPE_CREATE_AUTHENTICATORS,
  @SerialName("ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG")
  ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG,
  @SerialName("ACTIVITY_TYPE_DELETE_PRIVATE_KEY_TAGS")
  ACTIVITY_TYPE_DELETE_PRIVATE_KEY_TAGS,
  @SerialName("ACTIVITY_TYPE_SET_PAYMENT_METHOD")
  ACTIVITY_TYPE_SET_PAYMENT_METHOD,
  @SerialName("ACTIVITY_TYPE_ACTIVATE_BILLING_TIER")
  ACTIVITY_TYPE_ACTIVATE_BILLING_TIER,
  @SerialName("ACTIVITY_TYPE_DELETE_PAYMENT_METHOD")
  ACTIVITY_TYPE_DELETE_PAYMENT_METHOD,
  @SerialName("ACTIVITY_TYPE_CREATE_POLICY_V2")
  ACTIVITY_TYPE_CREATE_POLICY_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_POLICY_V3")
  ACTIVITY_TYPE_CREATE_POLICY_V3,
  @SerialName("ACTIVITY_TYPE_CREATE_API_ONLY_USERS")
  ACTIVITY_TYPE_CREATE_API_ONLY_USERS,
  @SerialName("ACTIVITY_TYPE_UPDATE_ROOT_QUORUM")
  ACTIVITY_TYPE_UPDATE_ROOT_QUORUM,
  @SerialName("ACTIVITY_TYPE_UPDATE_USER_TAG")
  ACTIVITY_TYPE_UPDATE_USER_TAG,
  @SerialName("ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG")
  ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG,
  @SerialName("ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2")
  ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_ORGANIZATION_V2")
  ACTIVITY_TYPE_CREATE_ORGANIZATION_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_USERS_V2")
  ACTIVITY_TYPE_CREATE_USERS_V2,
  @SerialName("ACTIVITY_TYPE_ACCEPT_INVITATION_V2")
  ACTIVITY_TYPE_ACCEPT_INVITATION_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V2")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V2,
  @SerialName("ACTIVITY_TYPE_UPDATE_ALLOWED_ORIGINS")
  ACTIVITY_TYPE_UPDATE_ALLOWED_ORIGINS,
  @SerialName("ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2")
  ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2,
  @SerialName("ACTIVITY_TYPE_UPDATE_USER")
  ACTIVITY_TYPE_UPDATE_USER,
  @SerialName("ACTIVITY_TYPE_UPDATE_POLICY")
  ACTIVITY_TYPE_UPDATE_POLICY,
  @SerialName("ACTIVITY_TYPE_SET_PAYMENT_METHOD_V2")
  ACTIVITY_TYPE_SET_PAYMENT_METHOD_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V3")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V3,
  @SerialName("ACTIVITY_TYPE_CREATE_WALLET")
  ACTIVITY_TYPE_CREATE_WALLET,
  @SerialName("ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS")
  ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS,
  @SerialName("ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY")
  ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY,
  @SerialName("ACTIVITY_TYPE_RECOVER_USER")
  ACTIVITY_TYPE_RECOVER_USER,
  @SerialName("ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE")
  ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE,
  @SerialName("ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE")
  ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE,
  @SerialName("ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2")
  ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2,
  @SerialName("ACTIVITY_TYPE_SIGN_TRANSACTION_V2")
  ACTIVITY_TYPE_SIGN_TRANSACTION_V2,
  @SerialName("ACTIVITY_TYPE_EXPORT_PRIVATE_KEY")
  ACTIVITY_TYPE_EXPORT_PRIVATE_KEY,
  @SerialName("ACTIVITY_TYPE_EXPORT_WALLET")
  ACTIVITY_TYPE_EXPORT_WALLET,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V4")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V4,
  @SerialName("ACTIVITY_TYPE_EMAIL_AUTH")
  ACTIVITY_TYPE_EMAIL_AUTH,
  @SerialName("ACTIVITY_TYPE_EXPORT_WALLET_ACCOUNT")
  ACTIVITY_TYPE_EXPORT_WALLET_ACCOUNT,
  @SerialName("ACTIVITY_TYPE_INIT_IMPORT_WALLET")
  ACTIVITY_TYPE_INIT_IMPORT_WALLET,
  @SerialName("ACTIVITY_TYPE_IMPORT_WALLET")
  ACTIVITY_TYPE_IMPORT_WALLET,
  @SerialName("ACTIVITY_TYPE_INIT_IMPORT_PRIVATE_KEY")
  ACTIVITY_TYPE_INIT_IMPORT_PRIVATE_KEY,
  @SerialName("ACTIVITY_TYPE_IMPORT_PRIVATE_KEY")
  ACTIVITY_TYPE_IMPORT_PRIVATE_KEY,
  @SerialName("ACTIVITY_TYPE_CREATE_POLICIES")
  ACTIVITY_TYPE_CREATE_POLICIES,
  @SerialName("ACTIVITY_TYPE_SIGN_RAW_PAYLOADS")
  ACTIVITY_TYPE_SIGN_RAW_PAYLOADS,
  @SerialName("ACTIVITY_TYPE_CREATE_READ_ONLY_SESSION")
  ACTIVITY_TYPE_CREATE_READ_ONLY_SESSION,
  @SerialName("ACTIVITY_TYPE_CREATE_OAUTH_PROVIDERS")
  ACTIVITY_TYPE_CREATE_OAUTH_PROVIDERS,
  @SerialName("ACTIVITY_TYPE_DELETE_OAUTH_PROVIDERS")
  ACTIVITY_TYPE_DELETE_OAUTH_PROVIDERS,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V5")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V5,
  @SerialName("ACTIVITY_TYPE_OAUTH")
  ACTIVITY_TYPE_OAUTH,
  @SerialName("ACTIVITY_TYPE_CREATE_API_KEYS_V2")
  ACTIVITY_TYPE_CREATE_API_KEYS_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION")
  ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION,
  @SerialName("ACTIVITY_TYPE_EMAIL_AUTH_V2")
  ACTIVITY_TYPE_EMAIL_AUTH_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V6")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V6,
  @SerialName("ACTIVITY_TYPE_DELETE_PRIVATE_KEYS")
  ACTIVITY_TYPE_DELETE_PRIVATE_KEYS,
  @SerialName("ACTIVITY_TYPE_DELETE_WALLETS")
  ACTIVITY_TYPE_DELETE_WALLETS,
  @SerialName("ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2")
  ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2,
  @SerialName("ACTIVITY_TYPE_DELETE_SUB_ORGANIZATION")
  ACTIVITY_TYPE_DELETE_SUB_ORGANIZATION,
  @SerialName("ACTIVITY_TYPE_INIT_OTP_AUTH")
  ACTIVITY_TYPE_INIT_OTP_AUTH,
  @SerialName("ACTIVITY_TYPE_OTP_AUTH")
  ACTIVITY_TYPE_OTP_AUTH,
  @SerialName("ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7")
  ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7,
  @SerialName("ACTIVITY_TYPE_UPDATE_WALLET")
  ACTIVITY_TYPE_UPDATE_WALLET,
  @SerialName("ACTIVITY_TYPE_UPDATE_POLICY_V2")
  ACTIVITY_TYPE_UPDATE_POLICY_V2,
  @SerialName("ACTIVITY_TYPE_CREATE_USERS_V3")
  ACTIVITY_TYPE_CREATE_USERS_V3,
  @SerialName("ACTIVITY_TYPE_INIT_OTP_AUTH_V2")
  ACTIVITY_TYPE_INIT_OTP_AUTH_V2,
  @SerialName("ACTIVITY_TYPE_INIT_OTP")
  ACTIVITY_TYPE_INIT_OTP,
  @SerialName("ACTIVITY_TYPE_VERIFY_OTP")
  ACTIVITY_TYPE_VERIFY_OTP,
  @SerialName("ACTIVITY_TYPE_OTP_LOGIN")
  ACTIVITY_TYPE_OTP_LOGIN,
  @SerialName("ACTIVITY_TYPE_STAMP_LOGIN")
  ACTIVITY_TYPE_STAMP_LOGIN,
  @SerialName("ACTIVITY_TYPE_OAUTH_LOGIN")
  ACTIVITY_TYPE_OAUTH_LOGIN,
  @SerialName("ACTIVITY_TYPE_UPDATE_USER_NAME")
  ACTIVITY_TYPE_UPDATE_USER_NAME,
  @SerialName("ACTIVITY_TYPE_UPDATE_USER_EMAIL")
  ACTIVITY_TYPE_UPDATE_USER_EMAIL,
  @SerialName("ACTIVITY_TYPE_UPDATE_USER_PHONE_NUMBER")
  ACTIVITY_TYPE_UPDATE_USER_PHONE_NUMBER,
  @SerialName("ACTIVITY_TYPE_INIT_FIAT_ON_RAMP")
  ACTIVITY_TYPE_INIT_FIAT_ON_RAMP,
  @SerialName("ACTIVITY_TYPE_CREATE_SMART_CONTRACT_INTERFACE")
  ACTIVITY_TYPE_CREATE_SMART_CONTRACT_INTERFACE,
  @SerialName("ACTIVITY_TYPE_DELETE_SMART_CONTRACT_INTERFACE")
  ACTIVITY_TYPE_DELETE_SMART_CONTRACT_INTERFACE,
  @SerialName("ACTIVITY_TYPE_ENABLE_AUTH_PROXY")
  ACTIVITY_TYPE_ENABLE_AUTH_PROXY,
  @SerialName("ACTIVITY_TYPE_DISABLE_AUTH_PROXY")
  ACTIVITY_TYPE_DISABLE_AUTH_PROXY,
  @SerialName("ACTIVITY_TYPE_UPDATE_AUTH_PROXY_CONFIG")
  ACTIVITY_TYPE_UPDATE_AUTH_PROXY_CONFIG,
  @SerialName("ACTIVITY_TYPE_CREATE_OAUTH2_CREDENTIAL")
  ACTIVITY_TYPE_CREATE_OAUTH2_CREDENTIAL,
  @SerialName("ACTIVITY_TYPE_UPDATE_OAUTH2_CREDENTIAL")
  ACTIVITY_TYPE_UPDATE_OAUTH2_CREDENTIAL,
  @SerialName("ACTIVITY_TYPE_DELETE_OAUTH2_CREDENTIAL")
  ACTIVITY_TYPE_DELETE_OAUTH2_CREDENTIAL,
  @SerialName("ACTIVITY_TYPE_OAUTH2_AUTHENTICATE")
  ACTIVITY_TYPE_OAUTH2_AUTHENTICATE,
}

@Serializable
public enum class V1AddressFormat {
  @SerialName("ADDRESS_FORMAT_UNCOMPRESSED")
  ADDRESS_FORMAT_UNCOMPRESSED,
  @SerialName("ADDRESS_FORMAT_COMPRESSED")
  ADDRESS_FORMAT_COMPRESSED,
  @SerialName("ADDRESS_FORMAT_ETHEREUM")
  ADDRESS_FORMAT_ETHEREUM,
  @SerialName("ADDRESS_FORMAT_SOLANA")
  ADDRESS_FORMAT_SOLANA,
  @SerialName("ADDRESS_FORMAT_COSMOS")
  ADDRESS_FORMAT_COSMOS,
  @SerialName("ADDRESS_FORMAT_TRON")
  ADDRESS_FORMAT_TRON,
  @SerialName("ADDRESS_FORMAT_SUI")
  ADDRESS_FORMAT_SUI,
  @SerialName("ADDRESS_FORMAT_APTOS")
  ADDRESS_FORMAT_APTOS,
  @SerialName("ADDRESS_FORMAT_BITCOIN_MAINNET_P2PKH")
  ADDRESS_FORMAT_BITCOIN_MAINNET_P2PKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_MAINNET_P2SH")
  ADDRESS_FORMAT_BITCOIN_MAINNET_P2SH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_MAINNET_P2WPKH")
  ADDRESS_FORMAT_BITCOIN_MAINNET_P2WPKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_MAINNET_P2WSH")
  ADDRESS_FORMAT_BITCOIN_MAINNET_P2WSH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_MAINNET_P2TR")
  ADDRESS_FORMAT_BITCOIN_MAINNET_P2TR,
  @SerialName("ADDRESS_FORMAT_BITCOIN_TESTNET_P2PKH")
  ADDRESS_FORMAT_BITCOIN_TESTNET_P2PKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_TESTNET_P2SH")
  ADDRESS_FORMAT_BITCOIN_TESTNET_P2SH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_TESTNET_P2WPKH")
  ADDRESS_FORMAT_BITCOIN_TESTNET_P2WPKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_TESTNET_P2WSH")
  ADDRESS_FORMAT_BITCOIN_TESTNET_P2WSH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_TESTNET_P2TR")
  ADDRESS_FORMAT_BITCOIN_TESTNET_P2TR,
  @SerialName("ADDRESS_FORMAT_BITCOIN_SIGNET_P2PKH")
  ADDRESS_FORMAT_BITCOIN_SIGNET_P2PKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_SIGNET_P2SH")
  ADDRESS_FORMAT_BITCOIN_SIGNET_P2SH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_SIGNET_P2WPKH")
  ADDRESS_FORMAT_BITCOIN_SIGNET_P2WPKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_SIGNET_P2WSH")
  ADDRESS_FORMAT_BITCOIN_SIGNET_P2WSH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_SIGNET_P2TR")
  ADDRESS_FORMAT_BITCOIN_SIGNET_P2TR,
  @SerialName("ADDRESS_FORMAT_BITCOIN_REGTEST_P2PKH")
  ADDRESS_FORMAT_BITCOIN_REGTEST_P2PKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_REGTEST_P2SH")
  ADDRESS_FORMAT_BITCOIN_REGTEST_P2SH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_REGTEST_P2WPKH")
  ADDRESS_FORMAT_BITCOIN_REGTEST_P2WPKH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_REGTEST_P2WSH")
  ADDRESS_FORMAT_BITCOIN_REGTEST_P2WSH,
  @SerialName("ADDRESS_FORMAT_BITCOIN_REGTEST_P2TR")
  ADDRESS_FORMAT_BITCOIN_REGTEST_P2TR,
  @SerialName("ADDRESS_FORMAT_SEI")
  ADDRESS_FORMAT_SEI,
  @SerialName("ADDRESS_FORMAT_XLM")
  ADDRESS_FORMAT_XLM,
  @SerialName("ADDRESS_FORMAT_DOGE_MAINNET")
  ADDRESS_FORMAT_DOGE_MAINNET,
  @SerialName("ADDRESS_FORMAT_DOGE_TESTNET")
  ADDRESS_FORMAT_DOGE_TESTNET,
  @SerialName("ADDRESS_FORMAT_TON_V3R2")
  ADDRESS_FORMAT_TON_V3R2,
  @SerialName("ADDRESS_FORMAT_TON_V4R2")
  ADDRESS_FORMAT_TON_V4R2,
  @SerialName("ADDRESS_FORMAT_TON_V5R1")
  ADDRESS_FORMAT_TON_V5R1,
  @SerialName("ADDRESS_FORMAT_XRP")
  ADDRESS_FORMAT_XRP,
}

@Serializable
public enum class V1ApiKeyCurve {
  @SerialName("API_KEY_CURVE_P256")
  API_KEY_CURVE_P256,
  @SerialName("API_KEY_CURVE_SECP256K1")
  API_KEY_CURVE_SECP256K1,
  @SerialName("API_KEY_CURVE_ED25519")
  API_KEY_CURVE_ED25519,
}

@Serializable
public enum class V1AuthenticatorTransport {
  @SerialName("AUTHENTICATOR_TRANSPORT_BLE")
  AUTHENTICATOR_TRANSPORT_BLE,
  @SerialName("AUTHENTICATOR_TRANSPORT_INTERNAL")
  AUTHENTICATOR_TRANSPORT_INTERNAL,
  @SerialName("AUTHENTICATOR_TRANSPORT_NFC")
  AUTHENTICATOR_TRANSPORT_NFC,
  @SerialName("AUTHENTICATOR_TRANSPORT_USB")
  AUTHENTICATOR_TRANSPORT_USB,
  @SerialName("AUTHENTICATOR_TRANSPORT_HYBRID")
  AUTHENTICATOR_TRANSPORT_HYBRID,
}

@Serializable
public enum class V1CredentialType {
  @SerialName("CREDENTIAL_TYPE_WEBAUTHN_AUTHENTICATOR")
  CREDENTIAL_TYPE_WEBAUTHN_AUTHENTICATOR,
  @SerialName("CREDENTIAL_TYPE_API_KEY_P256")
  CREDENTIAL_TYPE_API_KEY_P256,
  @SerialName("CREDENTIAL_TYPE_RECOVER_USER_KEY_P256")
  CREDENTIAL_TYPE_RECOVER_USER_KEY_P256,
  @SerialName("CREDENTIAL_TYPE_API_KEY_SECP256K1")
  CREDENTIAL_TYPE_API_KEY_SECP256K1,
  @SerialName("CREDENTIAL_TYPE_EMAIL_AUTH_KEY_P256")
  CREDENTIAL_TYPE_EMAIL_AUTH_KEY_P256,
  @SerialName("CREDENTIAL_TYPE_API_KEY_ED25519")
  CREDENTIAL_TYPE_API_KEY_ED25519,
  @SerialName("CREDENTIAL_TYPE_OTP_AUTH_KEY_P256")
  CREDENTIAL_TYPE_OTP_AUTH_KEY_P256,
  @SerialName("CREDENTIAL_TYPE_READ_WRITE_SESSION_KEY_P256")
  CREDENTIAL_TYPE_READ_WRITE_SESSION_KEY_P256,
  @SerialName("CREDENTIAL_TYPE_OAUTH_KEY_P256")
  CREDENTIAL_TYPE_OAUTH_KEY_P256,
  @SerialName("CREDENTIAL_TYPE_LOGIN")
  CREDENTIAL_TYPE_LOGIN,
}

@Serializable
public enum class V1Curve {
  @SerialName("CURVE_SECP256K1")
  CURVE_SECP256K1,
  @SerialName("CURVE_ED25519")
  CURVE_ED25519,
}

@Serializable
public enum class V1Effect {
  @SerialName("EFFECT_ALLOW")
  EFFECT_ALLOW,
  @SerialName("EFFECT_DENY")
  EFFECT_DENY,
}

@Serializable
public enum class V1FeatureName {
  @SerialName("FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY")
  FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY,
  @SerialName("FEATURE_NAME_WEBAUTHN_ORIGINS")
  FEATURE_NAME_WEBAUTHN_ORIGINS,
  @SerialName("FEATURE_NAME_EMAIL_AUTH")
  FEATURE_NAME_EMAIL_AUTH,
  @SerialName("FEATURE_NAME_EMAIL_RECOVERY")
  FEATURE_NAME_EMAIL_RECOVERY,
  @SerialName("FEATURE_NAME_WEBHOOK")
  FEATURE_NAME_WEBHOOK,
  @SerialName("FEATURE_NAME_SMS_AUTH")
  FEATURE_NAME_SMS_AUTH,
  @SerialName("FEATURE_NAME_OTP_EMAIL_AUTH")
  FEATURE_NAME_OTP_EMAIL_AUTH,
  @SerialName("FEATURE_NAME_AUTH_PROXY")
  FEATURE_NAME_AUTH_PROXY,
}

@Serializable
public enum class V1FiatOnRampBlockchainNetwork {
  @SerialName("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BITCOIN")
  FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BITCOIN,
  @SerialName("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_ETHEREUM")
  FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_ETHEREUM,
  @SerialName("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_SOLANA")
  FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_SOLANA,
  @SerialName("FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BASE")
  FIAT_ON_RAMP_BLOCKCHAIN_NETWORK_BASE,
}

@Serializable
public enum class V1FiatOnRampCryptoCurrency {
  @SerialName("FIAT_ON_RAMP_CRYPTO_CURRENCY_BTC")
  FIAT_ON_RAMP_CRYPTO_CURRENCY_BTC,
  @SerialName("FIAT_ON_RAMP_CRYPTO_CURRENCY_ETH")
  FIAT_ON_RAMP_CRYPTO_CURRENCY_ETH,
  @SerialName("FIAT_ON_RAMP_CRYPTO_CURRENCY_SOL")
  FIAT_ON_RAMP_CRYPTO_CURRENCY_SOL,
  @SerialName("FIAT_ON_RAMP_CRYPTO_CURRENCY_USDC")
  FIAT_ON_RAMP_CRYPTO_CURRENCY_USDC,
}

@Serializable
public enum class V1FiatOnRampCurrency {
  @SerialName("FIAT_ON_RAMP_CURRENCY_AUD")
  FIAT_ON_RAMP_CURRENCY_AUD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_BGN")
  FIAT_ON_RAMP_CURRENCY_BGN,
  @SerialName("FIAT_ON_RAMP_CURRENCY_BRL")
  FIAT_ON_RAMP_CURRENCY_BRL,
  @SerialName("FIAT_ON_RAMP_CURRENCY_CAD")
  FIAT_ON_RAMP_CURRENCY_CAD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_CHF")
  FIAT_ON_RAMP_CURRENCY_CHF,
  @SerialName("FIAT_ON_RAMP_CURRENCY_COP")
  FIAT_ON_RAMP_CURRENCY_COP,
  @SerialName("FIAT_ON_RAMP_CURRENCY_CZK")
  FIAT_ON_RAMP_CURRENCY_CZK,
  @SerialName("FIAT_ON_RAMP_CURRENCY_DKK")
  FIAT_ON_RAMP_CURRENCY_DKK,
  @SerialName("FIAT_ON_RAMP_CURRENCY_DOP")
  FIAT_ON_RAMP_CURRENCY_DOP,
  @SerialName("FIAT_ON_RAMP_CURRENCY_EGP")
  FIAT_ON_RAMP_CURRENCY_EGP,
  @SerialName("FIAT_ON_RAMP_CURRENCY_EUR")
  FIAT_ON_RAMP_CURRENCY_EUR,
  @SerialName("FIAT_ON_RAMP_CURRENCY_GBP")
  FIAT_ON_RAMP_CURRENCY_GBP,
  @SerialName("FIAT_ON_RAMP_CURRENCY_HKD")
  FIAT_ON_RAMP_CURRENCY_HKD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_IDR")
  FIAT_ON_RAMP_CURRENCY_IDR,
  @SerialName("FIAT_ON_RAMP_CURRENCY_ILS")
  FIAT_ON_RAMP_CURRENCY_ILS,
  @SerialName("FIAT_ON_RAMP_CURRENCY_JOD")
  FIAT_ON_RAMP_CURRENCY_JOD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_KES")
  FIAT_ON_RAMP_CURRENCY_KES,
  @SerialName("FIAT_ON_RAMP_CURRENCY_KWD")
  FIAT_ON_RAMP_CURRENCY_KWD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_LKR")
  FIAT_ON_RAMP_CURRENCY_LKR,
  @SerialName("FIAT_ON_RAMP_CURRENCY_MXN")
  FIAT_ON_RAMP_CURRENCY_MXN,
  @SerialName("FIAT_ON_RAMP_CURRENCY_NGN")
  FIAT_ON_RAMP_CURRENCY_NGN,
  @SerialName("FIAT_ON_RAMP_CURRENCY_NOK")
  FIAT_ON_RAMP_CURRENCY_NOK,
  @SerialName("FIAT_ON_RAMP_CURRENCY_NZD")
  FIAT_ON_RAMP_CURRENCY_NZD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_OMR")
  FIAT_ON_RAMP_CURRENCY_OMR,
  @SerialName("FIAT_ON_RAMP_CURRENCY_PEN")
  FIAT_ON_RAMP_CURRENCY_PEN,
  @SerialName("FIAT_ON_RAMP_CURRENCY_PLN")
  FIAT_ON_RAMP_CURRENCY_PLN,
  @SerialName("FIAT_ON_RAMP_CURRENCY_RON")
  FIAT_ON_RAMP_CURRENCY_RON,
  @SerialName("FIAT_ON_RAMP_CURRENCY_SEK")
  FIAT_ON_RAMP_CURRENCY_SEK,
  @SerialName("FIAT_ON_RAMP_CURRENCY_THB")
  FIAT_ON_RAMP_CURRENCY_THB,
  @SerialName("FIAT_ON_RAMP_CURRENCY_TRY")
  FIAT_ON_RAMP_CURRENCY_TRY,
  @SerialName("FIAT_ON_RAMP_CURRENCY_TWD")
  FIAT_ON_RAMP_CURRENCY_TWD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_USD")
  FIAT_ON_RAMP_CURRENCY_USD,
  @SerialName("FIAT_ON_RAMP_CURRENCY_VND")
  FIAT_ON_RAMP_CURRENCY_VND,
  @SerialName("FIAT_ON_RAMP_CURRENCY_ZAR")
  FIAT_ON_RAMP_CURRENCY_ZAR,
}

@Serializable
public enum class V1FiatOnRampPaymentMethod {
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_CREDIT_DEBIT_CARD")
  FIAT_ON_RAMP_PAYMENT_METHOD_CREDIT_DEBIT_CARD,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_APPLE_PAY")
  FIAT_ON_RAMP_PAYMENT_METHOD_APPLE_PAY,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_GBP_BANK_TRANSFER")
  FIAT_ON_RAMP_PAYMENT_METHOD_GBP_BANK_TRANSFER,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_GBP_OPEN_BANKING_PAYMENT")
  FIAT_ON_RAMP_PAYMENT_METHOD_GBP_OPEN_BANKING_PAYMENT,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_GOOGLE_PAY")
  FIAT_ON_RAMP_PAYMENT_METHOD_GOOGLE_PAY,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_SEPA_BANK_TRANSFER")
  FIAT_ON_RAMP_PAYMENT_METHOD_SEPA_BANK_TRANSFER,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_PIX_INSTANT_PAYMENT")
  FIAT_ON_RAMP_PAYMENT_METHOD_PIX_INSTANT_PAYMENT,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_PAYPAL")
  FIAT_ON_RAMP_PAYMENT_METHOD_PAYPAL,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_VENMO")
  FIAT_ON_RAMP_PAYMENT_METHOD_VENMO,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_MOONPAY_BALANCE")
  FIAT_ON_RAMP_PAYMENT_METHOD_MOONPAY_BALANCE,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_CRYPTO_ACCOUNT")
  FIAT_ON_RAMP_PAYMENT_METHOD_CRYPTO_ACCOUNT,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_FIAT_WALLET")
  FIAT_ON_RAMP_PAYMENT_METHOD_FIAT_WALLET,
  @SerialName("FIAT_ON_RAMP_PAYMENT_METHOD_ACH_BANK_ACCOUNT")
  FIAT_ON_RAMP_PAYMENT_METHOD_ACH_BANK_ACCOUNT,
}

@Serializable
public enum class V1FiatOnRampProvider {
  @SerialName("FIAT_ON_RAMP_PROVIDER_COINBASE")
  FIAT_ON_RAMP_PROVIDER_COINBASE,
  @SerialName("FIAT_ON_RAMP_PROVIDER_MOONPAY")
  FIAT_ON_RAMP_PROVIDER_MOONPAY,
}

@Serializable
public enum class V1HashFunction {
  @SerialName("HASH_FUNCTION_NO_OP")
  HASH_FUNCTION_NO_OP,
  @SerialName("HASH_FUNCTION_SHA256")
  HASH_FUNCTION_SHA256,
  @SerialName("HASH_FUNCTION_KECCAK256")
  HASH_FUNCTION_KECCAK256,
  @SerialName("HASH_FUNCTION_NOT_APPLICABLE")
  HASH_FUNCTION_NOT_APPLICABLE,
}

@Serializable
public enum class V1InvitationStatus {
  @SerialName("INVITATION_STATUS_CREATED")
  INVITATION_STATUS_CREATED,
  @SerialName("INVITATION_STATUS_ACCEPTED")
  INVITATION_STATUS_ACCEPTED,
  @SerialName("INVITATION_STATUS_REVOKED")
  INVITATION_STATUS_REVOKED,
}

@Serializable
public enum class V1MnemonicLanguage {
  @SerialName("MNEMONIC_LANGUAGE_ENGLISH")
  MNEMONIC_LANGUAGE_ENGLISH,
  @SerialName("MNEMONIC_LANGUAGE_SIMPLIFIED_CHINESE")
  MNEMONIC_LANGUAGE_SIMPLIFIED_CHINESE,
  @SerialName("MNEMONIC_LANGUAGE_TRADITIONAL_CHINESE")
  MNEMONIC_LANGUAGE_TRADITIONAL_CHINESE,
  @SerialName("MNEMONIC_LANGUAGE_CZECH")
  MNEMONIC_LANGUAGE_CZECH,
  @SerialName("MNEMONIC_LANGUAGE_FRENCH")
  MNEMONIC_LANGUAGE_FRENCH,
  @SerialName("MNEMONIC_LANGUAGE_ITALIAN")
  MNEMONIC_LANGUAGE_ITALIAN,
  @SerialName("MNEMONIC_LANGUAGE_JAPANESE")
  MNEMONIC_LANGUAGE_JAPANESE,
  @SerialName("MNEMONIC_LANGUAGE_KOREAN")
  MNEMONIC_LANGUAGE_KOREAN,
  @SerialName("MNEMONIC_LANGUAGE_SPANISH")
  MNEMONIC_LANGUAGE_SPANISH,
}

@Serializable
public enum class V1Oauth2Provider {
  @SerialName("OAUTH2_PROVIDER_X")
  OAUTH2_PROVIDER_X,
  @SerialName("OAUTH2_PROVIDER_DISCORD")
  OAUTH2_PROVIDER_DISCORD,
}

@Serializable
public enum class V1Operator {
  @SerialName("OPERATOR_EQUAL")
  OPERATOR_EQUAL,
  @SerialName("OPERATOR_MORE_THAN")
  OPERATOR_MORE_THAN,
  @SerialName("OPERATOR_MORE_THAN_OR_EQUAL")
  OPERATOR_MORE_THAN_OR_EQUAL,
  @SerialName("OPERATOR_LESS_THAN")
  OPERATOR_LESS_THAN,
  @SerialName("OPERATOR_LESS_THAN_OR_EQUAL")
  OPERATOR_LESS_THAN_OR_EQUAL,
  @SerialName("OPERATOR_CONTAINS")
  OPERATOR_CONTAINS,
  @SerialName("OPERATOR_NOT_EQUAL")
  OPERATOR_NOT_EQUAL,
  @SerialName("OPERATOR_IN")
  OPERATOR_IN,
  @SerialName("OPERATOR_NOT_IN")
  OPERATOR_NOT_IN,
  @SerialName("OPERATOR_CONTAINS_ONE")
  OPERATOR_CONTAINS_ONE,
  @SerialName("OPERATOR_CONTAINS_ALL")
  OPERATOR_CONTAINS_ALL,
}

@Serializable
public enum class V1Outcome {
  @SerialName("OUTCOME_ALLOW")
  OUTCOME_ALLOW,
  @SerialName("OUTCOME_DENY_EXPLICIT")
  OUTCOME_DENY_EXPLICIT,
  @SerialName("OUTCOME_DENY_IMPLICIT")
  OUTCOME_DENY_IMPLICIT,
  @SerialName("OUTCOME_REQUIRES_CONSENSUS")
  OUTCOME_REQUIRES_CONSENSUS,
  @SerialName("OUTCOME_REJECTED")
  OUTCOME_REJECTED,
  @SerialName("OUTCOME_ERROR")
  OUTCOME_ERROR,
}

@Serializable
public enum class V1PathFormat {
  @SerialName("PATH_FORMAT_BIP32")
  PATH_FORMAT_BIP32,
}

@Serializable
public enum class V1PayloadEncoding {
  @SerialName("PAYLOAD_ENCODING_HEXADECIMAL")
  PAYLOAD_ENCODING_HEXADECIMAL,
  @SerialName("PAYLOAD_ENCODING_TEXT_UTF8")
  PAYLOAD_ENCODING_TEXT_UTF8,
  @SerialName("PAYLOAD_ENCODING_EIP712")
  PAYLOAD_ENCODING_EIP712,
  @SerialName("PAYLOAD_ENCODING_EIP7702_AUTHORIZATION")
  PAYLOAD_ENCODING_EIP7702_AUTHORIZATION,
}

@Serializable
public enum class V1SignatureScheme {
  @SerialName("SIGNATURE_SCHEME_EPHEMERAL_KEY_P256")
  SIGNATURE_SCHEME_EPHEMERAL_KEY_P256,
}

@Serializable
public enum class V1SmartContractInterfaceType {
  @SerialName("SMART_CONTRACT_INTERFACE_TYPE_ETHEREUM")
  SMART_CONTRACT_INTERFACE_TYPE_ETHEREUM,
  @SerialName("SMART_CONTRACT_INTERFACE_TYPE_SOLANA")
  SMART_CONTRACT_INTERFACE_TYPE_SOLANA,
}

@Serializable
public enum class V1TagType {
  @SerialName("TAG_TYPE_USER")
  TAG_TYPE_USER,
  @SerialName("TAG_TYPE_PRIVATE_KEY")
  TAG_TYPE_PRIVATE_KEY,
}

@Serializable
public enum class V1TransactionType {
  @SerialName("TRANSACTION_TYPE_ETHEREUM")
  TRANSACTION_TYPE_ETHEREUM,
  @SerialName("TRANSACTION_TYPE_SOLANA")
  TRANSACTION_TYPE_SOLANA,
  @SerialName("TRANSACTION_TYPE_TRON")
  TRANSACTION_TYPE_TRON,
}

@Serializable
public class TGetActivityResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetActivityBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetActivityInput(
  @SerialName("body")
  public val body: TGetActivityBody,
)

@Serializable
public class TGetApiKeyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetApiKeyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetApiKeyInput(
  @SerialName("body")
  public val body: TGetApiKeyBody,
)

@Serializable
public class TGetApiKeysResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetApiKeysBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetApiKeysInput(
  @SerialName("body")
  public val body: TGetApiKeysBody,
)

@Serializable
public class TGetAttestationDocumentResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetAttestationDocumentBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetAttestationDocumentInput(
  @SerialName("body")
  public val body: TGetAttestationDocumentBody,
)

@Serializable
public class TGetAuthenticatorResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetAuthenticatorBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetAuthenticatorInput(
  @SerialName("body")
  public val body: TGetAuthenticatorBody,
)

@Serializable
public class TGetAuthenticatorsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetAuthenticatorsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetAuthenticatorsInput(
  @SerialName("body")
  public val body: TGetAuthenticatorsBody,
)

@Serializable
public class TGetBootProofResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetBootProofBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetBootProofInput(
  @SerialName("body")
  public val body: TGetBootProofBody,
)

@Serializable
public class TGetLatestBootProofResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetLatestBootProofBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetLatestBootProofInput(
  @SerialName("body")
  public val body: TGetLatestBootProofBody,
)

@Serializable
public class TGetOauth2CredentialResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetOauth2CredentialBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetOauth2CredentialInput(
  @SerialName("body")
  public val body: TGetOauth2CredentialBody,
)

@Serializable
public class TGetOauthProvidersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetOauthProvidersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetOauthProvidersInput(
  @SerialName("body")
  public val body: TGetOauthProvidersBody,
)

@Serializable
public class TGetOrganizationResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetOrganizationBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetOrganizationInput(
  @SerialName("body")
  public val body: TGetOrganizationBody,
)

@Serializable
public class TGetOrganizationConfigsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetOrganizationConfigsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetOrganizationConfigsInput(
  @SerialName("body")
  public val body: TGetOrganizationConfigsBody,
)

@Serializable
public class TGetPolicyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetPolicyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetPolicyInput(
  @SerialName("body")
  public val body: TGetPolicyBody,
)

@Serializable
public class TGetPolicyEvaluationsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetPolicyEvaluationsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetPolicyEvaluationsInput(
  @SerialName("body")
  public val body: TGetPolicyEvaluationsBody,
)

@Serializable
public class TGetPrivateKeyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetPrivateKeyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetPrivateKeyInput(
  @SerialName("body")
  public val body: TGetPrivateKeyBody,
)

@Serializable
public class TGetSmartContractInterfaceResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetSmartContractInterfaceBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetSmartContractInterfaceInput(
  @SerialName("body")
  public val body: TGetSmartContractInterfaceBody,
)

@Serializable
public class TGetUserResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetUserBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetUserInput(
  @SerialName("body")
  public val body: TGetUserBody,
)

@Serializable
public class TGetWalletResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetWalletBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetWalletInput(
  @SerialName("body")
  public val body: TGetWalletBody,
)

@Serializable
public class TGetWalletAccountResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetWalletAccountBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetWalletAccountInput(
  @SerialName("body")
  public val body: TGetWalletAccountBody,
)

@Serializable
public class TGetActivitiesResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetActivitiesBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetActivitiesInput(
  @SerialName("body")
  public val body: TGetActivitiesBody,
)

@Serializable
public class TGetAppProofsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetAppProofsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetAppProofsInput(
  @SerialName("body")
  public val body: TGetAppProofsBody,
)

@Serializable
public class TListOauth2CredentialsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TListOauth2CredentialsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TListOauth2CredentialsInput(
  @SerialName("body")
  public val body: TListOauth2CredentialsBody,
)

@Serializable
public class TGetPoliciesResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetPoliciesBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetPoliciesInput(
  @SerialName("body")
  public val body: TGetPoliciesBody,
)

@Serializable
public class TListPrivateKeyTagsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TListPrivateKeyTagsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TListPrivateKeyTagsInput(
  @SerialName("body")
  public val body: TListPrivateKeyTagsBody,
)

@Serializable
public class TGetPrivateKeysResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetPrivateKeysBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetPrivateKeysInput(
  @SerialName("body")
  public val body: TGetPrivateKeysBody,
)

@Serializable
public class TGetSmartContractInterfacesResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetSmartContractInterfacesBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetSmartContractInterfacesInput(
  @SerialName("body")
  public val body: TGetSmartContractInterfacesBody,
)

@Serializable
public class TGetSubOrgIdsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetSubOrgIdsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetSubOrgIdsInput(
  @SerialName("body")
  public val body: TGetSubOrgIdsBody,
)

@Serializable
public class TListUserTagsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TListUserTagsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TListUserTagsInput(
  @SerialName("body")
  public val body: TListUserTagsBody,
)

@Serializable
public class TGetUsersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetUsersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetUsersInput(
  @SerialName("body")
  public val body: TGetUsersBody,
)

@Serializable
public class TGetVerifiedSubOrgIdsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetVerifiedSubOrgIdsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetVerifiedSubOrgIdsInput(
  @SerialName("body")
  public val body: TGetVerifiedSubOrgIdsBody,
)

@Serializable
public class TGetWalletAccountsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetWalletAccountsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetWalletAccountsInput(
  @SerialName("body")
  public val body: TGetWalletAccountsBody,
)

@Serializable
public class TGetWalletsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetWalletsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetWalletsInput(
  @SerialName("body")
  public val body: TGetWalletsBody,
)

@Serializable
public class TGetWhoamiResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TGetWhoamiBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TGetWhoamiInput(
  @SerialName("body")
  public val body: TGetWhoamiBody,
)

@Serializable
public class TApproveActivityResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TApproveActivityBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TApproveActivityInput(
  @SerialName("body")
  public val body: TApproveActivityBody,
)

@Serializable
public class TCreateApiKeysResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateApiKeysBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateApiKeysInput(
  @SerialName("body")
  public val body: TCreateApiKeysBody,
)

@Serializable
public class TCreateApiOnlyUsersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateApiOnlyUsersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateApiOnlyUsersInput(
  @SerialName("body")
  public val body: TCreateApiOnlyUsersBody,
)

@Serializable
public class TCreateAuthenticatorsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateAuthenticatorsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateAuthenticatorsInput(
  @SerialName("body")
  public val body: TCreateAuthenticatorsBody,
)

@Serializable
public class TCreateInvitationsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateInvitationsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateInvitationsInput(
  @SerialName("body")
  public val body: TCreateInvitationsBody,
)

@Serializable
public class TCreateOauth2CredentialResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateOauth2CredentialBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateOauth2CredentialInput(
  @SerialName("body")
  public val body: TCreateOauth2CredentialBody,
)

@Serializable
public class TCreateOauthProvidersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateOauthProvidersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateOauthProvidersInput(
  @SerialName("body")
  public val body: TCreateOauthProvidersBody,
)

@Serializable
public class TCreatePoliciesResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreatePoliciesBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreatePoliciesInput(
  @SerialName("body")
  public val body: TCreatePoliciesBody,
)

@Serializable
public class TCreatePolicyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreatePolicyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreatePolicyInput(
  @SerialName("body")
  public val body: TCreatePolicyBody,
)

@Serializable
public class TCreatePrivateKeyTagResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreatePrivateKeyTagBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreatePrivateKeyTagInput(
  @SerialName("body")
  public val body: TCreatePrivateKeyTagBody,
)

@Serializable
public class TCreatePrivateKeysResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreatePrivateKeysBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreatePrivateKeysInput(
  @SerialName("body")
  public val body: TCreatePrivateKeysBody,
)

@Serializable
public class TCreateReadOnlySessionResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateReadOnlySessionBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateReadOnlySessionInput(
  @SerialName("body")
  public val body: TCreateReadOnlySessionBody,
)

@Serializable
public class TCreateReadWriteSessionResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateReadWriteSessionBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateReadWriteSessionInput(
  @SerialName("body")
  public val body: TCreateReadWriteSessionBody,
)

@Serializable
public class TCreateSmartContractInterfaceResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateSmartContractInterfaceBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateSmartContractInterfaceInput(
  @SerialName("body")
  public val body: TCreateSmartContractInterfaceBody,
)

@Serializable
public class TCreateSubOrganizationResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateSubOrganizationBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateSubOrganizationInput(
  @SerialName("body")
  public val body: TCreateSubOrganizationBody,
)

@Serializable
public class TCreateUserTagResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateUserTagBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateUserTagInput(
  @SerialName("body")
  public val body: TCreateUserTagBody,
)

@Serializable
public class TCreateUsersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateUsersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateUsersInput(
  @SerialName("body")
  public val body: TCreateUsersBody,
)

@Serializable
public class TCreateWalletResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateWalletBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateWalletInput(
  @SerialName("body")
  public val body: TCreateWalletBody,
)

@Serializable
public class TCreateWalletAccountsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TCreateWalletAccountsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TCreateWalletAccountsInput(
  @SerialName("body")
  public val body: TCreateWalletAccountsBody,
)

@Serializable
public class TDeleteApiKeysResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteApiKeysBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteApiKeysInput(
  @SerialName("body")
  public val body: TDeleteApiKeysBody,
)

@Serializable
public class TDeleteAuthenticatorsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteAuthenticatorsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteAuthenticatorsInput(
  @SerialName("body")
  public val body: TDeleteAuthenticatorsBody,
)

@Serializable
public class TDeleteInvitationResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteInvitationBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteInvitationInput(
  @SerialName("body")
  public val body: TDeleteInvitationBody,
)

@Serializable
public class TDeleteOauth2CredentialResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteOauth2CredentialBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteOauth2CredentialInput(
  @SerialName("body")
  public val body: TDeleteOauth2CredentialBody,
)

@Serializable
public class TDeleteOauthProvidersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteOauthProvidersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteOauthProvidersInput(
  @SerialName("body")
  public val body: TDeleteOauthProvidersBody,
)

@Serializable
public class TDeletePolicyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeletePolicyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeletePolicyInput(
  @SerialName("body")
  public val body: TDeletePolicyBody,
)

@Serializable
public class TDeletePrivateKeyTagsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeletePrivateKeyTagsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeletePrivateKeyTagsInput(
  @SerialName("body")
  public val body: TDeletePrivateKeyTagsBody,
)

@Serializable
public class TDeletePrivateKeysResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeletePrivateKeysBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeletePrivateKeysInput(
  @SerialName("body")
  public val body: TDeletePrivateKeysBody,
)

@Serializable
public class TDeleteSmartContractInterfaceResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteSmartContractInterfaceBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteSmartContractInterfaceInput(
  @SerialName("body")
  public val body: TDeleteSmartContractInterfaceBody,
)

@Serializable
public class TDeleteSubOrganizationResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteSubOrganizationBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteSubOrganizationInput(
  @SerialName("body")
  public val body: TDeleteSubOrganizationBody,
)

@Serializable
public class TDeleteUserTagsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteUserTagsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteUserTagsInput(
  @SerialName("body")
  public val body: TDeleteUserTagsBody,
)

@Serializable
public class TDeleteUsersResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteUsersBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteUsersInput(
  @SerialName("body")
  public val body: TDeleteUsersBody,
)

@Serializable
public class TDeleteWalletsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TDeleteWalletsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TDeleteWalletsInput(
  @SerialName("body")
  public val body: TDeleteWalletsBody,
)

@Serializable
public class TEmailAuthResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TEmailAuthBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TEmailAuthInput(
  @SerialName("body")
  public val body: TEmailAuthBody,
)

@Serializable
public class TExportPrivateKeyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TExportPrivateKeyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TExportPrivateKeyInput(
  @SerialName("body")
  public val body: TExportPrivateKeyBody,
)

@Serializable
public class TExportWalletResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TExportWalletBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TExportWalletInput(
  @SerialName("body")
  public val body: TExportWalletBody,
)

@Serializable
public class TExportWalletAccountResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TExportWalletAccountBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TExportWalletAccountInput(
  @SerialName("body")
  public val body: TExportWalletAccountBody,
)

@Serializable
public class TImportPrivateKeyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TImportPrivateKeyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TImportPrivateKeyInput(
  @SerialName("body")
  public val body: TImportPrivateKeyBody,
)

@Serializable
public class TImportWalletResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TImportWalletBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TImportWalletInput(
  @SerialName("body")
  public val body: TImportWalletBody,
)

@Serializable
public class TInitFiatOnRampResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TInitFiatOnRampBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TInitFiatOnRampInput(
  @SerialName("body")
  public val body: TInitFiatOnRampBody,
)

@Serializable
public class TInitImportPrivateKeyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TInitImportPrivateKeyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TInitImportPrivateKeyInput(
  @SerialName("body")
  public val body: TInitImportPrivateKeyBody,
)

@Serializable
public class TInitImportWalletResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TInitImportWalletBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TInitImportWalletInput(
  @SerialName("body")
  public val body: TInitImportWalletBody,
)

@Serializable
public class TInitOtpResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TInitOtpBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TInitOtpInput(
  @SerialName("body")
  public val body: TInitOtpBody,
)

@Serializable
public class TInitOtpAuthResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TInitOtpAuthBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TInitOtpAuthInput(
  @SerialName("body")
  public val body: TInitOtpAuthBody,
)

@Serializable
public class TInitUserEmailRecoveryResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TInitUserEmailRecoveryBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TInitUserEmailRecoveryInput(
  @SerialName("body")
  public val body: TInitUserEmailRecoveryBody,
)

@Serializable
public class TOauthResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TOauthBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TOauthInput(
  @SerialName("body")
  public val body: TOauthBody,
)

@Serializable
public class TOauth2AuthenticateResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TOauth2AuthenticateBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TOauth2AuthenticateInput(
  @SerialName("body")
  public val body: TOauth2AuthenticateBody,
)

@Serializable
public class TOauthLoginResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TOauthLoginBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TOauthLoginInput(
  @SerialName("body")
  public val body: TOauthLoginBody,
)

@Serializable
public class TOtpAuthResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TOtpAuthBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TOtpAuthInput(
  @SerialName("body")
  public val body: TOtpAuthBody,
)

@Serializable
public class TOtpLoginResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TOtpLoginBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TOtpLoginInput(
  @SerialName("body")
  public val body: TOtpLoginBody,
)

@Serializable
public class TRecoverUserResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TRecoverUserBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TRecoverUserInput(
  @SerialName("body")
  public val body: TRecoverUserBody,
)

@Serializable
public class TRejectActivityResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TRejectActivityBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TRejectActivityInput(
  @SerialName("body")
  public val body: TRejectActivityBody,
)

@Serializable
public class TRemoveOrganizationFeatureResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TRemoveOrganizationFeatureBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TRemoveOrganizationFeatureInput(
  @SerialName("body")
  public val body: TRemoveOrganizationFeatureBody,
)

@Serializable
public class TSetOrganizationFeatureResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TSetOrganizationFeatureBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TSetOrganizationFeatureInput(
  @SerialName("body")
  public val body: TSetOrganizationFeatureBody,
)

@Serializable
public class TSignRawPayloadResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TSignRawPayloadBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TSignRawPayloadInput(
  @SerialName("body")
  public val body: TSignRawPayloadBody,
)

@Serializable
public class TSignRawPayloadsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TSignRawPayloadsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TSignRawPayloadsInput(
  @SerialName("body")
  public val body: TSignRawPayloadsBody,
)

@Serializable
public class TSignTransactionResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TSignTransactionBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TSignTransactionInput(
  @SerialName("body")
  public val body: TSignTransactionBody,
)

@Serializable
public class TStampLoginResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TStampLoginBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TStampLoginInput(
  @SerialName("body")
  public val body: TStampLoginBody,
)

@Serializable
public class TUpdateOauth2CredentialResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateOauth2CredentialBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateOauth2CredentialInput(
  @SerialName("body")
  public val body: TUpdateOauth2CredentialBody,
)

@Serializable
public class TUpdatePolicyResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdatePolicyBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdatePolicyInput(
  @SerialName("body")
  public val body: TUpdatePolicyBody,
)

@Serializable
public class TUpdatePrivateKeyTagResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdatePrivateKeyTagBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdatePrivateKeyTagInput(
  @SerialName("body")
  public val body: TUpdatePrivateKeyTagBody,
)

@Serializable
public class TUpdateRootQuorumResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateRootQuorumBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateRootQuorumInput(
  @SerialName("body")
  public val body: TUpdateRootQuorumBody,
)

@Serializable
public class TUpdateUserResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateUserBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateUserInput(
  @SerialName("body")
  public val body: TUpdateUserBody,
)

@Serializable
public class TUpdateUserEmailResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateUserEmailBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateUserEmailInput(
  @SerialName("body")
  public val body: TUpdateUserEmailBody,
)

@Serializable
public class TUpdateUserNameResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateUserNameBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateUserNameInput(
  @SerialName("body")
  public val body: TUpdateUserNameBody,
)

@Serializable
public class TUpdateUserPhoneNumberResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateUserPhoneNumberBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateUserPhoneNumberInput(
  @SerialName("body")
  public val body: TUpdateUserPhoneNumberBody,
)

@Serializable
public class TUpdateUserTagResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateUserTagBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateUserTagInput(
  @SerialName("body")
  public val body: TUpdateUserTagBody,
)

@Serializable
public class TUpdateWalletResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TUpdateWalletBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TUpdateWalletInput(
  @SerialName("body")
  public val body: TUpdateWalletBody,
)

@Serializable
public class TVerifyOtpResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TVerifyOtpBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TVerifyOtpInput(
  @SerialName("body")
  public val body: TVerifyOtpBody,
)

@Serializable
public class TNOOPCodegenAnchorResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TTestRateLimitsResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class TTestRateLimitsBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class TTestRateLimitsInput(
  @SerialName("body")
  public val body: TTestRateLimitsBody,
)

@Serializable
public class ProxyTGetAccountResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTGetAccountBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTGetAccountInput(
  @SerialName("body")
  public val body: ProxyTGetAccountBody,
)

@Serializable
public class ProxyTOAuth2AuthenticateResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTOAuth2AuthenticateBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTOAuth2AuthenticateInput(
  @SerialName("body")
  public val body: ProxyTOAuth2AuthenticateBody,
)

@Serializable
public class ProxyTOAuthLoginResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTOAuthLoginBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTOAuthLoginInput(
  @SerialName("body")
  public val body: ProxyTOAuthLoginBody,
)

@Serializable
public class ProxyTInitOtpResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTInitOtpBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTInitOtpInput(
  @SerialName("body")
  public val body: ProxyTInitOtpBody,
)

@Serializable
public class ProxyTOtpLoginResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTOtpLoginBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTOtpLoginInput(
  @SerialName("body")
  public val body: ProxyTOtpLoginBody,
)

@Serializable
public class ProxyTVerifyOtpResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTVerifyOtpBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTVerifyOtpInput(
  @SerialName("body")
  public val body: ProxyTVerifyOtpBody,
)

@Serializable
public class ProxyTSignupResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTSignupBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTSignupInput(
  @SerialName("body")
  public val body: ProxyTSignupBody,
)

@Serializable
public class ProxyTGetWalletKitConfigResponse(
  @SerialName("activity")
  public val activity: V1Activity,
)

@Serializable
public class ProxyTGetWalletKitConfigBody(
  @SerialName("timestampMs")
  public val timestampMs: String?,
  @SerialName("organizationId")
  public val organizationId: String?,
)

@Serializable
public class ProxyTGetWalletKitConfigInput(
  @SerialName("body")
  public val body: ProxyTGetWalletKitConfigBody,
)
