// @generated by turnkey_codegen. DO NOT EDIT BY HAND
package com.turnkey.http

import com.turnkey.http.model.ProxyV1GetAccountRequest
import com.turnkey.http.model.ProxyV1GetAccountResponse
import com.turnkey.http.model.ProxyV1GetWalletKitConfigRequest
import com.turnkey.http.model.ProxyV1GetWalletKitConfigResponse
import com.turnkey.http.model.ProxyV1InitOtpRequest
import com.turnkey.http.model.ProxyV1InitOtpResponse
import com.turnkey.http.model.ProxyV1OAuth2AuthenticateRequest
import com.turnkey.http.model.ProxyV1OAuth2AuthenticateResponse
import com.turnkey.http.model.ProxyV1OAuthLoginRequest
import com.turnkey.http.model.ProxyV1OAuthLoginResponse
import com.turnkey.http.model.ProxyV1OtpLoginRequest
import com.turnkey.http.model.ProxyV1OtpLoginResponse
import com.turnkey.http.model.ProxyV1SignupRequest
import com.turnkey.http.model.ProxyV1SignupResponse
import com.turnkey.http.model.ProxyV1VerifyOtpRequest
import com.turnkey.http.model.ProxyV1VerifyOtpResponse
import com.turnkey.http.model.V1ActivityResponse
import com.turnkey.http.model.V1ApproveActivityRequest
import com.turnkey.http.model.V1BootProofResponse
import com.turnkey.http.model.V1CreateApiKeysRequest
import com.turnkey.http.model.V1CreateApiOnlyUsersRequest
import com.turnkey.http.model.V1CreateAuthenticatorsRequest
import com.turnkey.http.model.V1CreateInvitationsRequest
import com.turnkey.http.model.V1CreateOauth2CredentialRequest
import com.turnkey.http.model.V1CreateOauthProvidersRequest
import com.turnkey.http.model.V1CreatePoliciesRequest
import com.turnkey.http.model.V1CreatePolicyRequest
import com.turnkey.http.model.V1CreatePrivateKeyTagRequest
import com.turnkey.http.model.V1CreatePrivateKeysRequest
import com.turnkey.http.model.V1CreateReadOnlySessionRequest
import com.turnkey.http.model.V1CreateReadWriteSessionRequest
import com.turnkey.http.model.V1CreateSmartContractInterfaceRequest
import com.turnkey.http.model.V1CreateSubOrganizationRequest
import com.turnkey.http.model.V1CreateUserTagRequest
import com.turnkey.http.model.V1CreateUsersRequest
import com.turnkey.http.model.V1CreateWalletAccountsRequest
import com.turnkey.http.model.V1CreateWalletRequest
import com.turnkey.http.model.V1DeleteApiKeysRequest
import com.turnkey.http.model.V1DeleteAuthenticatorsRequest
import com.turnkey.http.model.V1DeleteInvitationRequest
import com.turnkey.http.model.V1DeleteOauth2CredentialRequest
import com.turnkey.http.model.V1DeleteOauthProvidersRequest
import com.turnkey.http.model.V1DeletePolicyRequest
import com.turnkey.http.model.V1DeletePrivateKeyTagsRequest
import com.turnkey.http.model.V1DeletePrivateKeysRequest
import com.turnkey.http.model.V1DeleteSmartContractInterfaceRequest
import com.turnkey.http.model.V1DeleteSubOrganizationRequest
import com.turnkey.http.model.V1DeleteUserTagsRequest
import com.turnkey.http.model.V1DeleteUsersRequest
import com.turnkey.http.model.V1DeleteWalletsRequest
import com.turnkey.http.model.V1EmailAuthRequest
import com.turnkey.http.model.V1ExportPrivateKeyRequest
import com.turnkey.http.model.V1ExportWalletAccountRequest
import com.turnkey.http.model.V1ExportWalletRequest
import com.turnkey.http.model.V1GetActivitiesRequest
import com.turnkey.http.model.V1GetActivitiesResponse
import com.turnkey.http.model.V1GetActivityRequest
import com.turnkey.http.model.V1GetApiKeyRequest
import com.turnkey.http.model.V1GetApiKeyResponse
import com.turnkey.http.model.V1GetApiKeysRequest
import com.turnkey.http.model.V1GetApiKeysResponse
import com.turnkey.http.model.V1GetAppProofsRequest
import com.turnkey.http.model.V1GetAppProofsResponse
import com.turnkey.http.model.V1GetAttestationDocumentRequest
import com.turnkey.http.model.V1GetAttestationDocumentResponse
import com.turnkey.http.model.V1GetAuthenticatorRequest
import com.turnkey.http.model.V1GetAuthenticatorResponse
import com.turnkey.http.model.V1GetAuthenticatorsRequest
import com.turnkey.http.model.V1GetAuthenticatorsResponse
import com.turnkey.http.model.V1GetBootProofRequest
import com.turnkey.http.model.V1GetLatestBootProofRequest
import com.turnkey.http.model.V1GetOauth2CredentialRequest
import com.turnkey.http.model.V1GetOauth2CredentialResponse
import com.turnkey.http.model.V1GetOauthProvidersRequest
import com.turnkey.http.model.V1GetOauthProvidersResponse
import com.turnkey.http.model.V1GetOrganizationConfigsRequest
import com.turnkey.http.model.V1GetOrganizationConfigsResponse
import com.turnkey.http.model.V1GetOrganizationRequest
import com.turnkey.http.model.V1GetOrganizationResponse
import com.turnkey.http.model.V1GetPoliciesRequest
import com.turnkey.http.model.V1GetPoliciesResponse
import com.turnkey.http.model.V1GetPolicyEvaluationsRequest
import com.turnkey.http.model.V1GetPolicyEvaluationsResponse
import com.turnkey.http.model.V1GetPolicyRequest
import com.turnkey.http.model.V1GetPolicyResponse
import com.turnkey.http.model.V1GetPrivateKeyRequest
import com.turnkey.http.model.V1GetPrivateKeyResponse
import com.turnkey.http.model.V1GetPrivateKeysRequest
import com.turnkey.http.model.V1GetPrivateKeysResponse
import com.turnkey.http.model.V1GetSmartContractInterfaceRequest
import com.turnkey.http.model.V1GetSmartContractInterfaceResponse
import com.turnkey.http.model.V1GetSmartContractInterfacesRequest
import com.turnkey.http.model.V1GetSmartContractInterfacesResponse
import com.turnkey.http.model.V1GetSubOrgIdsRequest
import com.turnkey.http.model.V1GetSubOrgIdsResponse
import com.turnkey.http.model.V1GetUserRequest
import com.turnkey.http.model.V1GetUserResponse
import com.turnkey.http.model.V1GetUsersRequest
import com.turnkey.http.model.V1GetUsersResponse
import com.turnkey.http.model.V1GetVerifiedSubOrgIdsRequest
import com.turnkey.http.model.V1GetVerifiedSubOrgIdsResponse
import com.turnkey.http.model.V1GetWalletAccountRequest
import com.turnkey.http.model.V1GetWalletAccountResponse
import com.turnkey.http.model.V1GetWalletAccountsRequest
import com.turnkey.http.model.V1GetWalletAccountsResponse
import com.turnkey.http.model.V1GetWalletRequest
import com.turnkey.http.model.V1GetWalletResponse
import com.turnkey.http.model.V1GetWalletsRequest
import com.turnkey.http.model.V1GetWalletsResponse
import com.turnkey.http.model.V1GetWhoamiRequest
import com.turnkey.http.model.V1GetWhoamiResponse
import com.turnkey.http.model.V1ImportPrivateKeyRequest
import com.turnkey.http.model.V1ImportWalletRequest
import com.turnkey.http.model.V1InitFiatOnRampRequest
import com.turnkey.http.model.V1InitImportPrivateKeyRequest
import com.turnkey.http.model.V1InitImportWalletRequest
import com.turnkey.http.model.V1InitOtpAuthRequest
import com.turnkey.http.model.V1InitOtpRequest
import com.turnkey.http.model.V1InitUserEmailRecoveryRequest
import com.turnkey.http.model.V1ListOauth2CredentialsRequest
import com.turnkey.http.model.V1ListOauth2CredentialsResponse
import com.turnkey.http.model.V1ListPrivateKeyTagsRequest
import com.turnkey.http.model.V1ListPrivateKeyTagsResponse
import com.turnkey.http.model.V1ListUserTagsRequest
import com.turnkey.http.model.V1ListUserTagsResponse
import com.turnkey.http.model.V1NOOPCodegenAnchorResponse
import com.turnkey.http.model.V1Oauth2AuthenticateRequest
import com.turnkey.http.model.V1OauthLoginRequest
import com.turnkey.http.model.V1OauthRequest
import com.turnkey.http.model.V1OtpAuthRequest
import com.turnkey.http.model.V1OtpLoginRequest
import com.turnkey.http.model.V1RecoverUserRequest
import com.turnkey.http.model.V1RejectActivityRequest
import com.turnkey.http.model.V1RemoveOrganizationFeatureRequest
import com.turnkey.http.model.V1SetOrganizationFeatureRequest
import com.turnkey.http.model.V1SignRawPayloadRequest
import com.turnkey.http.model.V1SignRawPayloadsRequest
import com.turnkey.http.model.V1SignTransactionRequest
import com.turnkey.http.model.V1StampLoginRequest
import com.turnkey.http.model.V1TestRateLimitsRequest
import com.turnkey.http.model.V1TestRateLimitsResponse
import com.turnkey.http.model.V1UpdateOauth2CredentialRequest
import com.turnkey.http.model.V1UpdatePolicyRequest
import com.turnkey.http.model.V1UpdatePrivateKeyTagRequest
import com.turnkey.http.model.V1UpdateRootQuorumRequest
import com.turnkey.http.model.V1UpdateUserEmailRequest
import com.turnkey.http.model.V1UpdateUserNameRequest
import com.turnkey.http.model.V1UpdateUserPhoneNumberRequest
import com.turnkey.http.model.V1UpdateUserRequest
import com.turnkey.http.model.V1UpdateUserTagRequest
import com.turnkey.http.model.V1UpdateWalletRequest
import com.turnkey.http.model.V1VerifyOtpRequest
import kotlin.String
import kotlinx.serialization.Serializable

@Serializable
public data class TStamp(
  public val stampHeaderName: String,
  public val stampHeaderValue: String,
)

@Serializable
public data class TSignedRequest(
  public val body: String,
  public val stamp: TStamp,
  public val url: String,
)

public typealias TGetActivityResponse = V1ActivityResponse

public typealias TGetActivityBody = V1GetActivityRequest

public typealias TGetApiKeyResponse = V1GetApiKeyResponse

public typealias TGetApiKeyBody = V1GetApiKeyRequest

public typealias TGetApiKeysResponse = V1GetApiKeysResponse

public typealias TGetApiKeysBody = V1GetApiKeysRequest

public typealias TGetAttestationDocumentResponse = V1GetAttestationDocumentResponse

public typealias TGetAttestationDocumentBody = V1GetAttestationDocumentRequest

public typealias TGetAuthenticatorResponse = V1GetAuthenticatorResponse

public typealias TGetAuthenticatorBody = V1GetAuthenticatorRequest

public typealias TGetAuthenticatorsResponse = V1GetAuthenticatorsResponse

public typealias TGetAuthenticatorsBody = V1GetAuthenticatorsRequest

public typealias TGetBootProofResponse = V1BootProofResponse

public typealias TGetBootProofBody = V1GetBootProofRequest

public typealias TGetLatestBootProofResponse = V1BootProofResponse

public typealias TGetLatestBootProofBody = V1GetLatestBootProofRequest

public typealias TGetOauth2CredentialResponse = V1GetOauth2CredentialResponse

public typealias TGetOauth2CredentialBody = V1GetOauth2CredentialRequest

public typealias TGetOauthProvidersResponse = V1GetOauthProvidersResponse

public typealias TGetOauthProvidersBody = V1GetOauthProvidersRequest

public typealias TGetOrganizationResponse = V1GetOrganizationResponse

public typealias TGetOrganizationBody = V1GetOrganizationRequest

public typealias TGetOrganizationConfigsResponse = V1GetOrganizationConfigsResponse

public typealias TGetOrganizationConfigsBody = V1GetOrganizationConfigsRequest

public typealias TGetPolicyResponse = V1GetPolicyResponse

public typealias TGetPolicyBody = V1GetPolicyRequest

public typealias TGetPolicyEvaluationsResponse = V1GetPolicyEvaluationsResponse

public typealias TGetPolicyEvaluationsBody = V1GetPolicyEvaluationsRequest

public typealias TGetPrivateKeyResponse = V1GetPrivateKeyResponse

public typealias TGetPrivateKeyBody = V1GetPrivateKeyRequest

public typealias TGetSmartContractInterfaceResponse = V1GetSmartContractInterfaceResponse

public typealias TGetSmartContractInterfaceBody = V1GetSmartContractInterfaceRequest

public typealias TGetUserResponse = V1GetUserResponse

public typealias TGetUserBody = V1GetUserRequest

public typealias TGetWalletResponse = V1GetWalletResponse

public typealias TGetWalletBody = V1GetWalletRequest

public typealias TGetWalletAccountResponse = V1GetWalletAccountResponse

public typealias TGetWalletAccountBody = V1GetWalletAccountRequest

public typealias TGetActivitiesResponse = V1GetActivitiesResponse

public typealias TGetActivitiesBody = V1GetActivitiesRequest

public typealias TGetAppProofsResponse = V1GetAppProofsResponse

public typealias TGetAppProofsBody = V1GetAppProofsRequest

public typealias TListOauth2CredentialsResponse = V1ListOauth2CredentialsResponse

public typealias TListOauth2CredentialsBody = V1ListOauth2CredentialsRequest

public typealias TGetPoliciesResponse = V1GetPoliciesResponse

public typealias TGetPoliciesBody = V1GetPoliciesRequest

public typealias TListPrivateKeyTagsResponse = V1ListPrivateKeyTagsResponse

public typealias TListPrivateKeyTagsBody = V1ListPrivateKeyTagsRequest

public typealias TGetPrivateKeysResponse = V1GetPrivateKeysResponse

public typealias TGetPrivateKeysBody = V1GetPrivateKeysRequest

public typealias TGetSmartContractInterfacesResponse = V1GetSmartContractInterfacesResponse

public typealias TGetSmartContractInterfacesBody = V1GetSmartContractInterfacesRequest

public typealias TGetSubOrgIdsResponse = V1GetSubOrgIdsResponse

public typealias TGetSubOrgIdsBody = V1GetSubOrgIdsRequest

public typealias TListUserTagsResponse = V1ListUserTagsResponse

public typealias TListUserTagsBody = V1ListUserTagsRequest

public typealias TGetUsersResponse = V1GetUsersResponse

public typealias TGetUsersBody = V1GetUsersRequest

public typealias TGetVerifiedSubOrgIdsResponse = V1GetVerifiedSubOrgIdsResponse

public typealias TGetVerifiedSubOrgIdsBody = V1GetVerifiedSubOrgIdsRequest

public typealias TGetWalletAccountsResponse = V1GetWalletAccountsResponse

public typealias TGetWalletAccountsBody = V1GetWalletAccountsRequest

public typealias TGetWalletsResponse = V1GetWalletsResponse

public typealias TGetWalletsBody = V1GetWalletsRequest

public typealias TGetWhoamiResponse = V1GetWhoamiResponse

public typealias TGetWhoamiBody = V1GetWhoamiRequest

public typealias TApproveActivityResponse = V1ActivityResponse

public typealias TApproveActivityBody = V1ApproveActivityRequest

public typealias TCreateApiKeysResponse = V1ActivityResponse

public typealias TCreateApiKeysBody = V1CreateApiKeysRequest

public typealias TCreateApiOnlyUsersResponse = V1ActivityResponse

public typealias TCreateApiOnlyUsersBody = V1CreateApiOnlyUsersRequest

public typealias TCreateAuthenticatorsResponse = V1ActivityResponse

public typealias TCreateAuthenticatorsBody = V1CreateAuthenticatorsRequest

public typealias TCreateInvitationsResponse = V1ActivityResponse

public typealias TCreateInvitationsBody = V1CreateInvitationsRequest

public typealias TCreateOauth2CredentialResponse = V1ActivityResponse

public typealias TCreateOauth2CredentialBody = V1CreateOauth2CredentialRequest

public typealias TCreateOauthProvidersResponse = V1ActivityResponse

public typealias TCreateOauthProvidersBody = V1CreateOauthProvidersRequest

public typealias TCreatePoliciesResponse = V1ActivityResponse

public typealias TCreatePoliciesBody = V1CreatePoliciesRequest

public typealias TCreatePolicyResponse = V1ActivityResponse

public typealias TCreatePolicyBody = V1CreatePolicyRequest

public typealias TCreatePrivateKeyTagResponse = V1ActivityResponse

public typealias TCreatePrivateKeyTagBody = V1CreatePrivateKeyTagRequest

public typealias TCreatePrivateKeysResponse = V1ActivityResponse

public typealias TCreatePrivateKeysBody = V1CreatePrivateKeysRequest

public typealias TCreateReadOnlySessionResponse = V1ActivityResponse

public typealias TCreateReadOnlySessionBody = V1CreateReadOnlySessionRequest

public typealias TCreateReadWriteSessionResponse = V1ActivityResponse

public typealias TCreateReadWriteSessionBody = V1CreateReadWriteSessionRequest

public typealias TCreateSmartContractInterfaceResponse = V1ActivityResponse

public typealias TCreateSmartContractInterfaceBody = V1CreateSmartContractInterfaceRequest

public typealias TCreateSubOrganizationResponse = V1ActivityResponse

public typealias TCreateSubOrganizationBody = V1CreateSubOrganizationRequest

public typealias TCreateUserTagResponse = V1ActivityResponse

public typealias TCreateUserTagBody = V1CreateUserTagRequest

public typealias TCreateUsersResponse = V1ActivityResponse

public typealias TCreateUsersBody = V1CreateUsersRequest

public typealias TCreateWalletResponse = V1ActivityResponse

public typealias TCreateWalletBody = V1CreateWalletRequest

public typealias TCreateWalletAccountsResponse = V1ActivityResponse

public typealias TCreateWalletAccountsBody = V1CreateWalletAccountsRequest

public typealias TDeleteApiKeysResponse = V1ActivityResponse

public typealias TDeleteApiKeysBody = V1DeleteApiKeysRequest

public typealias TDeleteAuthenticatorsResponse = V1ActivityResponse

public typealias TDeleteAuthenticatorsBody = V1DeleteAuthenticatorsRequest

public typealias TDeleteInvitationResponse = V1ActivityResponse

public typealias TDeleteInvitationBody = V1DeleteInvitationRequest

public typealias TDeleteOauth2CredentialResponse = V1ActivityResponse

public typealias TDeleteOauth2CredentialBody = V1DeleteOauth2CredentialRequest

public typealias TDeleteOauthProvidersResponse = V1ActivityResponse

public typealias TDeleteOauthProvidersBody = V1DeleteOauthProvidersRequest

public typealias TDeletePolicyResponse = V1ActivityResponse

public typealias TDeletePolicyBody = V1DeletePolicyRequest

public typealias TDeletePrivateKeyTagsResponse = V1ActivityResponse

public typealias TDeletePrivateKeyTagsBody = V1DeletePrivateKeyTagsRequest

public typealias TDeletePrivateKeysResponse = V1ActivityResponse

public typealias TDeletePrivateKeysBody = V1DeletePrivateKeysRequest

public typealias TDeleteSmartContractInterfaceResponse = V1ActivityResponse

public typealias TDeleteSmartContractInterfaceBody = V1DeleteSmartContractInterfaceRequest

public typealias TDeleteSubOrganizationResponse = V1ActivityResponse

public typealias TDeleteSubOrganizationBody = V1DeleteSubOrganizationRequest

public typealias TDeleteUserTagsResponse = V1ActivityResponse

public typealias TDeleteUserTagsBody = V1DeleteUserTagsRequest

public typealias TDeleteUsersResponse = V1ActivityResponse

public typealias TDeleteUsersBody = V1DeleteUsersRequest

public typealias TDeleteWalletsResponse = V1ActivityResponse

public typealias TDeleteWalletsBody = V1DeleteWalletsRequest

public typealias TEmailAuthResponse = V1ActivityResponse

public typealias TEmailAuthBody = V1EmailAuthRequest

public typealias TExportPrivateKeyResponse = V1ActivityResponse

public typealias TExportPrivateKeyBody = V1ExportPrivateKeyRequest

public typealias TExportWalletResponse = V1ActivityResponse

public typealias TExportWalletBody = V1ExportWalletRequest

public typealias TExportWalletAccountResponse = V1ActivityResponse

public typealias TExportWalletAccountBody = V1ExportWalletAccountRequest

public typealias TImportPrivateKeyResponse = V1ActivityResponse

public typealias TImportPrivateKeyBody = V1ImportPrivateKeyRequest

public typealias TImportWalletResponse = V1ActivityResponse

public typealias TImportWalletBody = V1ImportWalletRequest

public typealias TInitFiatOnRampResponse = V1ActivityResponse

public typealias TInitFiatOnRampBody = V1InitFiatOnRampRequest

public typealias TInitImportPrivateKeyResponse = V1ActivityResponse

public typealias TInitImportPrivateKeyBody = V1InitImportPrivateKeyRequest

public typealias TInitImportWalletResponse = V1ActivityResponse

public typealias TInitImportWalletBody = V1InitImportWalletRequest

public typealias TInitOtpResponse = V1ActivityResponse

public typealias TInitOtpBody = V1InitOtpRequest

public typealias TInitOtpAuthResponse = V1ActivityResponse

public typealias TInitOtpAuthBody = V1InitOtpAuthRequest

public typealias TInitUserEmailRecoveryResponse = V1ActivityResponse

public typealias TInitUserEmailRecoveryBody = V1InitUserEmailRecoveryRequest

public typealias TOauthResponse = V1ActivityResponse

public typealias TOauthBody = V1OauthRequest

public typealias TOauth2AuthenticateResponse = V1ActivityResponse

public typealias TOauth2AuthenticateBody = V1Oauth2AuthenticateRequest

public typealias TOauthLoginResponse = V1ActivityResponse

public typealias TOauthLoginBody = V1OauthLoginRequest

public typealias TOtpAuthResponse = V1ActivityResponse

public typealias TOtpAuthBody = V1OtpAuthRequest

public typealias TOtpLoginResponse = V1ActivityResponse

public typealias TOtpLoginBody = V1OtpLoginRequest

public typealias TRecoverUserResponse = V1ActivityResponse

public typealias TRecoverUserBody = V1RecoverUserRequest

public typealias TRejectActivityResponse = V1ActivityResponse

public typealias TRejectActivityBody = V1RejectActivityRequest

public typealias TRemoveOrganizationFeatureResponse = V1ActivityResponse

public typealias TRemoveOrganizationFeatureBody = V1RemoveOrganizationFeatureRequest

public typealias TSetOrganizationFeatureResponse = V1ActivityResponse

public typealias TSetOrganizationFeatureBody = V1SetOrganizationFeatureRequest

public typealias TSignRawPayloadResponse = V1ActivityResponse

public typealias TSignRawPayloadBody = V1SignRawPayloadRequest

public typealias TSignRawPayloadsResponse = V1ActivityResponse

public typealias TSignRawPayloadsBody = V1SignRawPayloadsRequest

public typealias TSignTransactionResponse = V1ActivityResponse

public typealias TSignTransactionBody = V1SignTransactionRequest

public typealias TStampLoginResponse = V1ActivityResponse

public typealias TStampLoginBody = V1StampLoginRequest

public typealias TUpdateOauth2CredentialResponse = V1ActivityResponse

public typealias TUpdateOauth2CredentialBody = V1UpdateOauth2CredentialRequest

public typealias TUpdatePolicyResponse = V1ActivityResponse

public typealias TUpdatePolicyBody = V1UpdatePolicyRequest

public typealias TUpdatePrivateKeyTagResponse = V1ActivityResponse

public typealias TUpdatePrivateKeyTagBody = V1UpdatePrivateKeyTagRequest

public typealias TUpdateRootQuorumResponse = V1ActivityResponse

public typealias TUpdateRootQuorumBody = V1UpdateRootQuorumRequest

public typealias TUpdateUserResponse = V1ActivityResponse

public typealias TUpdateUserBody = V1UpdateUserRequest

public typealias TUpdateUserEmailResponse = V1ActivityResponse

public typealias TUpdateUserEmailBody = V1UpdateUserEmailRequest

public typealias TUpdateUserNameResponse = V1ActivityResponse

public typealias TUpdateUserNameBody = V1UpdateUserNameRequest

public typealias TUpdateUserPhoneNumberResponse = V1ActivityResponse

public typealias TUpdateUserPhoneNumberBody = V1UpdateUserPhoneNumberRequest

public typealias TUpdateUserTagResponse = V1ActivityResponse

public typealias TUpdateUserTagBody = V1UpdateUserTagRequest

public typealias TUpdateWalletResponse = V1ActivityResponse

public typealias TUpdateWalletBody = V1UpdateWalletRequest

public typealias TVerifyOtpResponse = V1ActivityResponse

public typealias TVerifyOtpBody = V1VerifyOtpRequest

public typealias TNOOPCodegenAnchorResponse = V1NOOPCodegenAnchorResponse

public typealias TTestRateLimitsResponse = V1TestRateLimitsResponse

public typealias TTestRateLimitsBody = V1TestRateLimitsRequest

public typealias ProxyTGetAccountResponse = ProxyV1GetAccountResponse

public typealias ProxyTGetAccountBody = ProxyV1GetAccountRequest

public typealias ProxyTOAuth2AuthenticateResponse = ProxyV1OAuth2AuthenticateResponse

public typealias ProxyTOAuth2AuthenticateBody = ProxyV1OAuth2AuthenticateRequest

public typealias ProxyTOAuthLoginResponse = ProxyV1OAuthLoginResponse

public typealias ProxyTOAuthLoginBody = ProxyV1OAuthLoginRequest

public typealias ProxyTInitOtpResponse = ProxyV1InitOtpResponse

public typealias ProxyTInitOtpBody = ProxyV1InitOtpRequest

public typealias ProxyTOtpLoginResponse = ProxyV1OtpLoginResponse

public typealias ProxyTOtpLoginBody = ProxyV1OtpLoginRequest

public typealias ProxyTVerifyOtpResponse = ProxyV1VerifyOtpResponse

public typealias ProxyTVerifyOtpBody = ProxyV1VerifyOtpRequest

public typealias ProxyTSignupResponse = ProxyV1SignupResponse

public typealias ProxyTSignupBody = ProxyV1SignupRequest

public typealias ProxyTGetWalletKitConfigResponse = ProxyV1GetWalletKitConfigResponse

public typealias ProxyTGetWalletKitConfigBody = ProxyV1GetWalletKitConfigRequest
